// sketchlib.proto — Portable wire format for sketchlib-go and sketchlib-rust.
//
// Design goals:
//   - Cross-language: Go (sketchlib-go) ↔ Rust (sketchlib-rust) round-trips.
//   - Forward-compatible: new fields use reserved numbers; old readers skip them.
//   - Logical state only: no pointers, no runtime caches, no gob/msgpack artefacts.
//   - Derived values (gamma, L2 norms, capacity caches) are always recomputed on load.
//   - Flat row-major arrays for all 2-D matrices.
//   - Hash specification is explicit so consumers can detect configuration mismatches.
//
// Version history:
//   1 — initial portable format (CountMin, Count, HLL, KLL, DDSketch)
//   2 — extended to UnivMon and Hydra (reserved, not yet stable)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sketchlib.proto

package sketchlibpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HashAlgorithm enumerates supported hash algorithms.
// Only XXH3_64 is cross-language stable for the current implementation.
type HashAlgorithm int32

const (
	HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED HashAlgorithm = 0
	// xxHash3 64-bit with seed (zeebo/xxh3 in Go; twox-hash XxHash3_64 in Rust).
	// This is the standard algorithm for both libraries.
	HashAlgorithm_HASH_ALGORITHM_XXH3_64 HashAlgorithm = 1
	// xxHash3 128-bit with seed. Used for HLL register indexing and packed matrix
	// hashes that exceed 64 bits.
	HashAlgorithm_HASH_ALGORITHM_XXH3_128 HashAlgorithm = 2
	// xxHash 64-bit (non-XXH3). Reserved for legacy data; not produced by either
	// current library.
	HashAlgorithm_HASH_ALGORITHM_XXHASH64 HashAlgorithm = 3
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0: "HASH_ALGORITHM_UNSPECIFIED",
		1: "HASH_ALGORITHM_XXH3_64",
		2: "HASH_ALGORITHM_XXH3_128",
		3: "HASH_ALGORITHM_XXHASH64",
	}
	HashAlgorithm_value = map[string]int32{
		"HASH_ALGORITHM_UNSPECIFIED": 0,
		"HASH_ALGORITHM_XXH3_64":     1,
		"HASH_ALGORITHM_XXH3_128":    2,
		"HASH_ALGORITHM_XXHASH64":    3,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_sketchlib_proto_enumTypes[0].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_sketchlib_proto_enumTypes[0]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{0}
}

// SeedDerivation describes how per-row seed indices are produced.
type SeedDerivation int32

const (
	SeedDerivation_SEED_DERIVATION_UNSPECIFIED SeedDerivation = 0
	// Each row r uses seed_list[(base + r) % len(seed_list)].
	// Standard derivation for multi-row sketches (CountMin, CountSketch).
	SeedDerivation_SEED_DERIVATION_ADDITIVE_OFFSET SeedDerivation = 1
	// All rows share a single hash (Packed64 or Packed128 fast-path).
	// Applicable only when the total bit-width fits in 64 or 128 bits.
	SeedDerivation_SEED_DERIVATION_PACKED SeedDerivation = 2
)

// Enum value maps for SeedDerivation.
var (
	SeedDerivation_name = map[int32]string{
		0: "SEED_DERIVATION_UNSPECIFIED",
		1: "SEED_DERIVATION_ADDITIVE_OFFSET",
		2: "SEED_DERIVATION_PACKED",
	}
	SeedDerivation_value = map[string]int32{
		"SEED_DERIVATION_UNSPECIFIED":     0,
		"SEED_DERIVATION_ADDITIVE_OFFSET": 1,
		"SEED_DERIVATION_PACKED":          2,
	}
)

func (x SeedDerivation) Enum() *SeedDerivation {
	p := new(SeedDerivation)
	*p = x
	return p
}

func (x SeedDerivation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeedDerivation) Descriptor() protoreflect.EnumDescriptor {
	return file_sketchlib_proto_enumTypes[1].Descriptor()
}

func (SeedDerivation) Type() protoreflect.EnumType {
	return &file_sketchlib_proto_enumTypes[1]
}

func (x SeedDerivation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeedDerivation.Descriptor instead.
func (SeedDerivation) EnumDescriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{1}
}

// CounterType identifies the numeric type used to store matrix counters.
// Go defaults to FLOAT64; Rust defaults to INT32.
// Determines which counts_* array is populated in CountMinState and
// CountSketchState.
type CounterType int32

const (
	CounterType_COUNTER_TYPE_UNSPECIFIED CounterType = 0
	CounterType_COUNTER_TYPE_INT32       CounterType = 1 // Rust default for CountMin / CountSketch.
	CounterType_COUNTER_TYPE_INT64       CounterType = 2
	// INT128 is stored as pairs of int64 (hi, lo) interleaved in counts_int.
	CounterType_COUNTER_TYPE_INT128  CounterType = 3
	CounterType_COUNTER_TYPE_FLOAT64 CounterType = 4 // Go default for CountMin / CountSketch.
)

// Enum value maps for CounterType.
var (
	CounterType_name = map[int32]string{
		0: "COUNTER_TYPE_UNSPECIFIED",
		1: "COUNTER_TYPE_INT32",
		2: "COUNTER_TYPE_INT64",
		3: "COUNTER_TYPE_INT128",
		4: "COUNTER_TYPE_FLOAT64",
	}
	CounterType_value = map[string]int32{
		"COUNTER_TYPE_UNSPECIFIED": 0,
		"COUNTER_TYPE_INT32":       1,
		"COUNTER_TYPE_INT64":       2,
		"COUNTER_TYPE_INT128":      3,
		"COUNTER_TYPE_FLOAT64":     4,
	}
)

func (x CounterType) Enum() *CounterType {
	p := new(CounterType)
	*p = x
	return p
}

func (x CounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_sketchlib_proto_enumTypes[2].Descriptor()
}

func (CounterType) Type() protoreflect.EnumType {
	return &file_sketchlib_proto_enumTypes[2]
}

func (x CounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CounterType.Descriptor instead.
func (CounterType) EnumDescriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{2}
}

// HLLVariant identifies which HLL estimator algorithm the registers belong to.
type HLLVariant int32

const (
	HLLVariant_HLL_VARIANT_UNSPECIFIED HLLVariant = 0
	// Classic HLL with bias-correction tables (Flajolet et al. 2007).
	HLLVariant_HLL_VARIANT_REGULAR HLLVariant = 1
	// Otmar Ertl's improved estimator used by Apache DataFusion.
	// Not compatible with REGULAR registers.
	HLLVariant_HLL_VARIANT_DATAFUSION HLLVariant = 2
	// Kevin Lang's HyperLogLog++ Improved Proposal (HIP).
	// Requires hip_kxq0, hip_kxq1, hip_est to be populated.
	HLLVariant_HLL_VARIANT_HIP HLLVariant = 3
)

// Enum value maps for HLLVariant.
var (
	HLLVariant_name = map[int32]string{
		0: "HLL_VARIANT_UNSPECIFIED",
		1: "HLL_VARIANT_REGULAR",
		2: "HLL_VARIANT_DATAFUSION",
		3: "HLL_VARIANT_HIP",
	}
	HLLVariant_value = map[string]int32{
		"HLL_VARIANT_UNSPECIFIED": 0,
		"HLL_VARIANT_REGULAR":     1,
		"HLL_VARIANT_DATAFUSION":  2,
		"HLL_VARIANT_HIP":         3,
	}
)

func (x HLLVariant) Enum() *HLLVariant {
	p := new(HLLVariant)
	*p = x
	return p
}

func (x HLLVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HLLVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_sketchlib_proto_enumTypes[3].Descriptor()
}

func (HLLVariant) Type() protoreflect.EnumType {
	return &file_sketchlib_proto_enumTypes[3]
}

func (x HLLVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HLLVariant.Descriptor instead.
func (HLLVariant) EnumDescriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{3}
}

// HydraCounterType identifies the sketch algorithm used inside Hydra cells.
type HydraCounterType int32

const (
	HydraCounterType_HYDRA_COUNTER_TYPE_UNSPECIFIED  HydraCounterType = 0
	HydraCounterType_HYDRA_COUNTER_TYPE_COUNT_MIN    HydraCounterType = 1
	HydraCounterType_HYDRA_COUNTER_TYPE_COUNT_SKETCH HydraCounterType = 2
	HydraCounterType_HYDRA_COUNTER_TYPE_HLL          HydraCounterType = 3
	HydraCounterType_HYDRA_COUNTER_TYPE_KLL          HydraCounterType = 4
	HydraCounterType_HYDRA_COUNTER_TYPE_UNIVMON      HydraCounterType = 5
)

// Enum value maps for HydraCounterType.
var (
	HydraCounterType_name = map[int32]string{
		0: "HYDRA_COUNTER_TYPE_UNSPECIFIED",
		1: "HYDRA_COUNTER_TYPE_COUNT_MIN",
		2: "HYDRA_COUNTER_TYPE_COUNT_SKETCH",
		3: "HYDRA_COUNTER_TYPE_HLL",
		4: "HYDRA_COUNTER_TYPE_KLL",
		5: "HYDRA_COUNTER_TYPE_UNIVMON",
	}
	HydraCounterType_value = map[string]int32{
		"HYDRA_COUNTER_TYPE_UNSPECIFIED":  0,
		"HYDRA_COUNTER_TYPE_COUNT_MIN":    1,
		"HYDRA_COUNTER_TYPE_COUNT_SKETCH": 2,
		"HYDRA_COUNTER_TYPE_HLL":          3,
		"HYDRA_COUNTER_TYPE_KLL":          4,
		"HYDRA_COUNTER_TYPE_UNIVMON":      5,
	}
)

func (x HydraCounterType) Enum() *HydraCounterType {
	p := new(HydraCounterType)
	*p = x
	return p
}

func (x HydraCounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HydraCounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_sketchlib_proto_enumTypes[4].Descriptor()
}

func (HydraCounterType) Type() protoreflect.EnumType {
	return &file_sketchlib_proto_enumTypes[4]
}

func (x HydraCounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HydraCounterType.Descriptor instead.
func (HydraCounterType) EnumDescriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{4}
}

// SketchEnvelope is the portable container for all sketch transfers.
// Producers fill exactly one field inside sketch_state.
// Consumers check format_version first, then dispatch on the oneof.
type SketchEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version. Consumers should reject envelopes whose version exceeds
	// the highest version they understand.
	//
	//	1 = CountMin, Count, HLL, KLL, DDSketch
	//	2 = UnivMon, Hydra (reserved)
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Library and build info of the producing side.
	Producer *ProducerInfo `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Complete hashing configuration. Consumers must validate this against their
	// own configuration before performing updates or queries on the loaded sketch.
	// Mismatches do not prevent loading but will cause diverging results.
	HashSpec *HashSpec `protobuf:"bytes,3,opt,name=hash_spec,json=hashSpec,proto3" json:"hash_spec,omitempty"`
	// The sketch payload. Exactly one field must be set.
	//
	// Types that are valid to be assigned to SketchState:
	//
	//	*SketchEnvelope_CountMin
	//	*SketchEnvelope_CountSketch
	//	*SketchEnvelope_Hll
	//	*SketchEnvelope_Kll
	//	*SketchEnvelope_Ddsketch
	//	*SketchEnvelope_Univmon
	//	*SketchEnvelope_Hydra
	//	*SketchEnvelope_Coco
	//	*SketchEnvelope_Elastic
	SketchState   isSketchEnvelope_SketchState `protobuf_oneof:"sketch_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchEnvelope) Reset() {
	*x = SketchEnvelope{}
	mi := &file_sketchlib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchEnvelope) ProtoMessage() {}

func (x *SketchEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchEnvelope.ProtoReflect.Descriptor instead.
func (*SketchEnvelope) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{0}
}

func (x *SketchEnvelope) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SketchEnvelope) GetProducer() *ProducerInfo {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *SketchEnvelope) GetHashSpec() *HashSpec {
	if x != nil {
		return x.HashSpec
	}
	return nil
}

func (x *SketchEnvelope) GetSketchState() isSketchEnvelope_SketchState {
	if x != nil {
		return x.SketchState
	}
	return nil
}

func (x *SketchEnvelope) GetCountMin() *CountMinState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_CountMin); ok {
			return x.CountMin
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCountSketch() *CountSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_CountSketch); ok {
			return x.CountSketch
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHll() *HyperLogLogState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hll); ok {
			return x.Hll
		}
	}
	return nil
}

func (x *SketchEnvelope) GetKll() *KLLState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Kll); ok {
			return x.Kll
		}
	}
	return nil
}

func (x *SketchEnvelope) GetDdsketch() *DDSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Ddsketch); ok {
			return x.Ddsketch
		}
	}
	return nil
}

func (x *SketchEnvelope) GetUnivmon() *UnivMonState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Univmon); ok {
			return x.Univmon
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHydra() *HydraState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hydra); ok {
			return x.Hydra
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCoco() *CocoSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Coco); ok {
			return x.Coco
		}
	}
	return nil
}

func (x *SketchEnvelope) GetElastic() *ElasticState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Elastic); ok {
			return x.Elastic
		}
	}
	return nil
}

type isSketchEnvelope_SketchState interface {
	isSketchEnvelope_SketchState()
}

type SketchEnvelope_CountMin struct {
	CountMin *CountMinState `protobuf:"bytes,10,opt,name=count_min,json=countMin,proto3,oneof"`
}

type SketchEnvelope_CountSketch struct {
	CountSketch *CountSketchState `protobuf:"bytes,11,opt,name=count_sketch,json=countSketch,proto3,oneof"`
}

type SketchEnvelope_Hll struct {
	Hll *HyperLogLogState `protobuf:"bytes,12,opt,name=hll,proto3,oneof"`
}

type SketchEnvelope_Kll struct {
	Kll *KLLState `protobuf:"bytes,13,opt,name=kll,proto3,oneof"`
}

type SketchEnvelope_Ddsketch struct {
	Ddsketch *DDSketchState `protobuf:"bytes,14,opt,name=ddsketch,proto3,oneof"`
}

type SketchEnvelope_Univmon struct {
	Univmon *UnivMonState `protobuf:"bytes,15,opt,name=univmon,proto3,oneof"`
}

type SketchEnvelope_Hydra struct {
	Hydra *HydraState `protobuf:"bytes,16,opt,name=hydra,proto3,oneof"`
}

type SketchEnvelope_Coco struct {
	Coco *CocoSketchState `protobuf:"bytes,17,opt,name=coco,proto3,oneof"`
}

type SketchEnvelope_Elastic struct {
	Elastic *ElasticState `protobuf:"bytes,18,opt,name=elastic,proto3,oneof"`
}

func (*SketchEnvelope_CountMin) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_CountSketch) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hll) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Kll) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Ddsketch) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Univmon) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hydra) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Coco) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Elastic) isSketchEnvelope_SketchState() {}

// ProducerInfo records which library version created this envelope.
type ProducerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of "sketchlib-go" or "sketchlib-rust".
	Library string `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	// Semantic version string of the producing library, e.g. "0.1.0".
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerInfo) Reset() {
	*x = ProducerInfo{}
	mi := &file_sketchlib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerInfo) ProtoMessage() {}

func (x *ProducerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerInfo.ProtoReflect.Descriptor instead.
func (*ProducerInfo) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{1}
}

func (x *ProducerInfo) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *ProducerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// HashSpec fully describes the hashing configuration so both sides can confirm
// they will compute identical bucket indices.
//
// Both libraries share:
//
//	canonical_seed_index = 5  (CanonicalHashSeed / CANONICAL_HASH_SEED)
//	seed_list            = the 20-entry table in hash.go / hash.rs
//	seed_derivation      = ADDITIVE_OFFSET for per-row seeds
type HashSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash algorithm used for all sketch operations.
	Algorithm HashAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=sketchlib.v1.HashAlgorithm" json:"algorithm,omitempty"`
	// Index into seed_list used as the primary (canonical) hash seed.
	// Both libraries default to 5.
	CanonicalSeedIndex uint32 `protobuf:"varint,2,opt,name=canonical_seed_index,json=canonicalSeedIndex,proto3" json:"canonical_seed_index,omitempty"`
	// Complete seed table. Must be identical on both sides for correct results.
	// Both libraries currently use exactly 20 seeds; producers always emit all 20.
	SeedList []uint64 `protobuf:"varint,3,rep,packed,name=seed_list,json=seedList,proto3" json:"seed_list,omitempty"`
	// How per-row seeds are derived from the base seed index.
	SeedDerivation SeedDerivation `protobuf:"varint,4,opt,name=seed_derivation,json=seedDerivation,proto3,enum=sketchlib.v1.SeedDerivation" json:"seed_derivation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HashSpec) Reset() {
	*x = HashSpec{}
	mi := &file_sketchlib_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashSpec) ProtoMessage() {}

func (x *HashSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashSpec.ProtoReflect.Descriptor instead.
func (*HashSpec) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{2}
}

func (x *HashSpec) GetAlgorithm() HashAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
}

func (x *HashSpec) GetCanonicalSeedIndex() uint32 {
	if x != nil {
		return x.CanonicalSeedIndex
	}
	return 0
}

func (x *HashSpec) GetSeedList() []uint64 {
	if x != nil {
		return x.SeedList
	}
	return nil
}

func (x *HashSpec) GetSeedDerivation() SeedDerivation {
	if x != nil {
		return x.SeedDerivation
	}
	return SeedDerivation_SEED_DERIVATION_UNSPECIFIED
}

// CountMinState is the portable state of a Count-Min Sketch.
//
// The counter matrix is stored flat in row-major order:
//
//	element [r][c] is at index r * cols + c.
//
// The Go implementation tracks auxiliary sum/L1/L2 arrays that the Rust
// implementation does not produce. These fields are optional; consumers
// that need them must recompute from raw insertions if absent.
type CountMinState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matrix dimensions. Both must be > 0.
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Indicates which counts_* field below is populated.
	CounterType CounterType `protobuf:"varint,3,opt,name=counter_type,json=counterType,proto3,enum=sketchlib.v1.CounterType" json:"counter_type,omitempty"`
	// Integer counters in row-major order, length = rows * cols.
	// Populated when counter_type ∈ {INT32, INT64}.
	// Use sint64 for efficient varint encoding of near-zero values.
	// For INT128 counters, values are interleaved as (hi_i, lo_i) pairs,
	// making the effective length 2 * rows * cols.
	CountsInt []int64 `protobuf:"zigzag64,4,rep,packed,name=counts_int,json=countsInt,proto3" json:"counts_int,omitempty"`
	// Floating-point counters in row-major order, length = rows * cols.
	// Populated when counter_type = FLOAT64 (Go producer).
	CountsFloat []float64 `protobuf:"fixed64,5,rep,packed,name=counts_float,json=countsFloat,proto3" json:"counts_float,omitempty"`
	// Sum-weighted counter matrix (same layout as counts_*), length = rows * cols.
	SumCounts []float64 `protobuf:"fixed64,6,rep,packed,name=sum_counts,json=sumCounts,proto3" json:"sum_counts,omitempty"`
	// Sum-of-squares counter matrix, length = rows * cols.
	Sum2Counts []float64 `protobuf:"fixed64,7,rep,packed,name=sum2_counts,json=sum2Counts,proto3" json:"sum2_counts,omitempty"`
	// Per-row L1 norms, length = rows.
	L1 []float64 `protobuf:"fixed64,8,rep,packed,name=l1,proto3" json:"l1,omitempty"`
	// Per-row L2 norms, length = rows. Recompute if absent.
	L2            []float64 `protobuf:"fixed64,9,rep,packed,name=l2,proto3" json:"l2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountMinState) Reset() {
	*x = CountMinState{}
	mi := &file_sketchlib_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountMinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountMinState) ProtoMessage() {}

func (x *CountMinState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountMinState.ProtoReflect.Descriptor instead.
func (*CountMinState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{3}
}

func (x *CountMinState) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CountMinState) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CountMinState) GetCounterType() CounterType {
	if x != nil {
		return x.CounterType
	}
	return CounterType_COUNTER_TYPE_UNSPECIFIED
}

func (x *CountMinState) GetCountsInt() []int64 {
	if x != nil {
		return x.CountsInt
	}
	return nil
}

func (x *CountMinState) GetCountsFloat() []float64 {
	if x != nil {
		return x.CountsFloat
	}
	return nil
}

func (x *CountMinState) GetSumCounts() []float64 {
	if x != nil {
		return x.SumCounts
	}
	return nil
}

func (x *CountMinState) GetSum2Counts() []float64 {
	if x != nil {
		return x.Sum2Counts
	}
	return nil
}

func (x *CountMinState) GetL1() []float64 {
	if x != nil {
		return x.L1
	}
	return nil
}

func (x *CountMinState) GetL2() []float64 {
	if x != nil {
		return x.L2
	}
	return nil
}

// CountSketchState is the portable state of a Count (±1) Sketch.
//
// The counter matrix is signed because Count Sketch uses ±1 increments.
// The matrix layout is identical to CountMinState (row-major, flat).
//
// L2 norms are derived values and must be recomputed on load:
//
//	l2[r] = sqrt( sum_c counts[r][c]^2 )
//
// Producers may include them as a convenience for consumers that only query.
type CountSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matrix dimensions. Both must be > 0.
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Indicates which counts_* field below is populated.
	CounterType CounterType `protobuf:"varint,3,opt,name=counter_type,json=counterType,proto3,enum=sketchlib.v1.CounterType" json:"counter_type,omitempty"`
	// Signed integer counters in row-major order, length = rows * cols.
	// Populated when counter_type ∈ {INT32, INT64}.
	CountsInt []int64 `protobuf:"zigzag64,4,rep,packed,name=counts_int,json=countsInt,proto3" json:"counts_int,omitempty"`
	// Floating-point counters in row-major order, length = rows * cols.
	// Populated when counter_type = FLOAT64 (Go producer).
	CountsFloat []float64 `protobuf:"fixed64,5,rep,packed,name=counts_float,json=countsFloat,proto3" json:"counts_float,omitempty"`
	// Per-row L2 norms, length = rows. Derived — recompute on load if absent.
	L2 []float64 `protobuf:"fixed64,6,rep,packed,name=l2,proto3" json:"l2,omitempty"`
	// Optional heavy-hitter (TopK min-heap) state.
	// Absent when TopK tracking is disabled.
	Topk          *TopKState `protobuf:"bytes,7,opt,name=topk,proto3" json:"topk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountSketchState) Reset() {
	*x = CountSketchState{}
	mi := &file_sketchlib_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountSketchState) ProtoMessage() {}

func (x *CountSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountSketchState.ProtoReflect.Descriptor instead.
func (*CountSketchState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{4}
}

func (x *CountSketchState) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CountSketchState) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CountSketchState) GetCounterType() CounterType {
	if x != nil {
		return x.CounterType
	}
	return CounterType_COUNTER_TYPE_UNSPECIFIED
}

func (x *CountSketchState) GetCountsInt() []int64 {
	if x != nil {
		return x.CountsInt
	}
	return nil
}

func (x *CountSketchState) GetCountsFloat() []float64 {
	if x != nil {
		return x.CountsFloat
	}
	return nil
}

func (x *CountSketchState) GetL2() []float64 {
	if x != nil {
		return x.L2
	}
	return nil
}

func (x *CountSketchState) GetTopk() *TopKState {
	if x != nil {
		return x.Topk
	}
	return nil
}

// TopKState is the serialized state of a min-heap heavy-hitter tracker.
type TopKState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of entries retained.
	K uint32 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	// All retained entries. Order is not guaranteed (heap order is not preserved).
	Entries       []*HeapEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopKState) Reset() {
	*x = TopKState{}
	mi := &file_sketchlib_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopKState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopKState) ProtoMessage() {}

func (x *TopKState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopKState.ProtoReflect.Descriptor instead.
func (*TopKState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{5}
}

func (x *TopKState) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *TopKState) GetEntries() []*HeapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// HeapEntry is one heavy-hitter record inside a TopKState.
type HeapEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String key identifying the heavy hitter (e.g. flow ID, IP address).
	// For binary keys, producers should use base64 or hex encoding and document
	// their choice; a future bytes_key field is reserved at number 3.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Approximate frequency or weight accumulated for this key.
	Count         float64 `protobuf:"fixed64,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapEntry) Reset() {
	*x = HeapEntry{}
	mi := &file_sketchlib_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapEntry) ProtoMessage() {}

func (x *HeapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapEntry.ProtoReflect.Descriptor instead.
func (*HeapEntry) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{6}
}

func (x *HeapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeapEntry) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// HyperLogLogState is the portable state of a HyperLogLog cardinality sketch.
//
// Precision p determines the register count: num_registers = 2^precision.
// Both libraries default to precision = 14 (16 384 registers).
//
// The variant field is required because the three estimator algorithms are
// not interchangeable: loading a DataFusion state into a Regular estimator
// (or vice versa) produces incorrect cardinality estimates.
type HyperLogLogState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HLL estimator variant. Required.
	Variant HLLVariant `protobuf:"varint,1,opt,name=variant,proto3,enum=sketchlib.v1.HLLVariant" json:"variant,omitempty"`
	// Log₂ of the number of registers (precision parameter p).
	// Default = 14 → 16 384 registers.
	Precision uint32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// Raw register values, length = 2^precision.
	// Each byte stores the maximum (leading-zeros + 1) seen for that bucket.
	// Stored as a raw byte string for compact encoding (1 byte per register).
	Registers []byte `protobuf:"bytes,3,opt,name=registers,proto3" json:"registers,omitempty"`
	// HIP accumulator component kxq0.
	HipKxq0 float64 `protobuf:"fixed64,4,opt,name=hip_kxq0,json=hipKxq0,proto3" json:"hip_kxq0,omitempty"`
	// HIP accumulator component kxq1.
	HipKxq1 float64 `protobuf:"fixed64,5,opt,name=hip_kxq1,json=hipKxq1,proto3" json:"hip_kxq1,omitempty"`
	// HIP running cardinality estimate.
	HipEst        float64 `protobuf:"fixed64,6,opt,name=hip_est,json=hipEst,proto3" json:"hip_est,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HyperLogLogState) Reset() {
	*x = HyperLogLogState{}
	mi := &file_sketchlib_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HyperLogLogState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperLogLogState) ProtoMessage() {}

func (x *HyperLogLogState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperLogLogState.ProtoReflect.Descriptor instead.
func (*HyperLogLogState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{7}
}

func (x *HyperLogLogState) GetVariant() HLLVariant {
	if x != nil {
		return x.Variant
	}
	return HLLVariant_HLL_VARIANT_UNSPECIFIED
}

func (x *HyperLogLogState) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *HyperLogLogState) GetRegisters() []byte {
	if x != nil {
		return x.Registers
	}
	return nil
}

func (x *HyperLogLogState) GetHipKxq0() float64 {
	if x != nil {
		return x.HipKxq0
	}
	return 0
}

func (x *HyperLogLogState) GetHipKxq1() float64 {
	if x != nil {
		return x.HipKxq1
	}
	return 0
}

func (x *HyperLogLogState) GetHipEst() float64 {
	if x != nil {
		return x.HipEst
	}
	return 0
}

// KLLState is the portable state of a KLL quantile sketch.
//
// The items array is partitioned into compaction levels by the levels[] array:
//
//	items[ levels[i] .. levels[i+1] )  are the retained items at level i.
//
// Derived state that must be recomputed on load (not serialized):
//
//	capacity_cache  — computed from k, m, and level boundaries.
//	level0_capacity — computed from k and num_levels.
//	top_height      — equals num_levels - 1.
type KLLState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target compactor capacity k. Must be >= 8.
	K uint32 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	// Minimum compactor size m. Must satisfy 2 <= m <= k.
	M uint32 `protobuf:"varint,2,opt,name=m,proto3" json:"m,omitempty"`
	// Number of levels currently in use.
	NumLevels uint32 `protobuf:"varint,3,opt,name=num_levels,json=numLevels,proto3" json:"num_levels,omitempty"`
	// Level boundary indices into items[], length = num_levels + 1.
	// levels[0] is always 0; levels[num_levels] = len(items).
	Levels []uint32 `protobuf:"varint,4,rep,packed,name=levels,proto3" json:"levels,omitempty"`
	// All retained samples in level order, length = levels[num_levels].
	Items []float64 `protobuf:"fixed64,5,rep,packed,name=items,proto3" json:"items,omitempty"`
	// Random bit generator state for deterministic compaction continuation.
	// Required for sketches that will receive further updates after loading.
	// Consumers that only query may ignore this field.
	Coin          *CoinState `protobuf:"bytes,6,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KLLState) Reset() {
	*x = KLLState{}
	mi := &file_sketchlib_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KLLState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KLLState) ProtoMessage() {}

func (x *KLLState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KLLState.ProtoReflect.Descriptor instead.
func (*KLLState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{8}
}

func (x *KLLState) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *KLLState) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *KLLState) GetNumLevels() uint32 {
	if x != nil {
		return x.NumLevels
	}
	return 0
}

func (x *KLLState) GetLevels() []uint32 {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *KLLState) GetItems() []float64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *KLLState) GetCoin() *CoinState {
	if x != nil {
		return x.Coin
	}
	return nil
}

// CoinState is the RNG used by KLL's probabilistic compaction.
// Both Go and Rust use an identical xorshift-based generator.
type CoinState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Xorshift generator internal state word.
	State uint64 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	// Up to 64 random bits buffered for single-bit coin flips.
	BitCache uint64 `protobuf:"varint,2,opt,name=bit_cache,json=bitCache,proto3" json:"bit_cache,omitempty"`
	// Number of valid bits remaining in bit_cache (0–64).
	RemainingBits uint32 `protobuf:"varint,3,opt,name=remaining_bits,json=remainingBits,proto3" json:"remaining_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinState) Reset() {
	*x = CoinState{}
	mi := &file_sketchlib_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinState) ProtoMessage() {}

func (x *CoinState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinState.ProtoReflect.Descriptor instead.
func (*CoinState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{9}
}

func (x *CoinState) GetState() uint64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CoinState) GetBitCache() uint64 {
	if x != nil {
		return x.BitCache
	}
	return 0
}

func (x *CoinState) GetRemainingBits() uint32 {
	if x != nil {
		return x.RemainingBits
	}
	return 0
}

// DDSketchState is the portable state of a DDSketch quantile sketch.
//
// Only alpha is required to reconstruct the index mapping. Consumers must
// recompute all derived mapping values on load:
//
//	gamma        = (1.0 + alpha) / (1.0 - alpha)
//	log_gamma    = ln(gamma)
//	inv_log_gamma = 1.0 / log_gamma
//
// Bucket indices: a value v maps to bucket floor(ln(v) * inv_log_gamma).
// Stored bucket absolute_index = array_index + store_offset.
type DDSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative accuracy guarantee. Required. Must satisfy 0 < alpha < 1.
	Alpha float64 `protobuf:"fixed64,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	// Bucket count array in index order (ascending absolute bucket index).
	// Absolute index of store_counts[i] is i + store_offset.
	StoreCounts []uint64 `protobuf:"varint,2,rep,packed,name=store_counts,json=storeCounts,proto3" json:"store_counts,omitempty"`
	// Absolute bucket index corresponding to store_counts[0].
	// May be negative (values < 1.0 map to negative bucket indices).
	StoreOffset int32 `protobuf:"zigzag32,3,opt,name=store_offset,json=storeOffset,proto3" json:"store_offset,omitempty"`
	// Total number of values added.
	Count uint64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Sum of all values added (for mean computation).
	Sum float64 `protobuf:"fixed64,5,opt,name=sum,proto3" json:"sum,omitempty"`
	// Minimum value observed. +Inf when the sketch is empty.
	Min float64 `protobuf:"fixed64,6,opt,name=min,proto3" json:"min,omitempty"`
	// Maximum value observed. -Inf when the sketch is empty.
	Max           float64 `protobuf:"fixed64,7,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchState) Reset() {
	*x = DDSketchState{}
	mi := &file_sketchlib_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchState) ProtoMessage() {}

func (x *DDSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchState.ProtoReflect.Descriptor instead.
func (*DDSketchState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{10}
}

func (x *DDSketchState) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *DDSketchState) GetStoreCounts() []uint64 {
	if x != nil {
		return x.StoreCounts
	}
	return nil
}

func (x *DDSketchState) GetStoreOffset() int32 {
	if x != nil {
		return x.StoreOffset
	}
	return 0
}

func (x *DDSketchState) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DDSketchState) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *DDSketchState) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DDSketchState) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// UnivMonState is the portable state of a Universal Monitoring (UnivMon) sketch.
//
// UnivMon is a hierarchy of L Count Sketches paired with L heavy-hitter heaps.
// An item's hash trailing-zero count determines which layers receive it, giving
// each layer a geometrically decreasing sample of the stream.
//
// All layers share the same sketch dimensions and heap capacity.
type UnivMonState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of layers L in the hierarchy (inclusive of all levels).
	LayerSize uint32 `protobuf:"varint,1,opt,name=layer_size,json=layerSize,proto3" json:"layer_size,omitempty"`
	// Count Sketch dimensions shared by all layers.
	SketchRows uint32 `protobuf:"varint,2,opt,name=sketch_rows,json=sketchRows,proto3" json:"sketch_rows,omitempty"`
	SketchCols uint32 `protobuf:"varint,3,opt,name=sketch_cols,json=sketchCols,proto3" json:"sketch_cols,omitempty"`
	// Heavy-hitter heap capacity shared by all layers.
	HeapSize uint32 `protobuf:"varint,4,opt,name=heap_size,json=heapSize,proto3" json:"heap_size,omitempty"`
	// Total items inserted across all layers (the "bucket size" counter).
	BucketSize uint64 `protobuf:"varint,5,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	// Per-layer state, in order from layer 0 (finest) to layer_size-1 (coarsest).
	// Length must equal layer_size.
	Layers        []*UnivMonLayer `protobuf:"bytes,6,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnivMonState) Reset() {
	*x = UnivMonState{}
	mi := &file_sketchlib_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnivMonState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnivMonState) ProtoMessage() {}

func (x *UnivMonState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnivMonState.ProtoReflect.Descriptor instead.
func (*UnivMonState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{11}
}

func (x *UnivMonState) GetLayerSize() uint32 {
	if x != nil {
		return x.LayerSize
	}
	return 0
}

func (x *UnivMonState) GetSketchRows() uint32 {
	if x != nil {
		return x.SketchRows
	}
	return 0
}

func (x *UnivMonState) GetSketchCols() uint32 {
	if x != nil {
		return x.SketchCols
	}
	return 0
}

func (x *UnivMonState) GetHeapSize() uint32 {
	if x != nil {
		return x.HeapSize
	}
	return 0
}

func (x *UnivMonState) GetBucketSize() uint64 {
	if x != nil {
		return x.BucketSize
	}
	return 0
}

func (x *UnivMonState) GetLayers() []*UnivMonLayer {
	if x != nil {
		return x.Layers
	}
	return nil
}

// UnivMonLayer is the joint state of one UnivMon layer.
type UnivMonLayer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Count Sketch accumulating items at this layer.
	Sketch *CountSketchState `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	// The heavy-hitter heap for this layer.
	Heap          *TopKState `protobuf:"bytes,2,opt,name=heap,proto3" json:"heap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnivMonLayer) Reset() {
	*x = UnivMonLayer{}
	mi := &file_sketchlib_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnivMonLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnivMonLayer) ProtoMessage() {}

func (x *UnivMonLayer) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnivMonLayer.ProtoReflect.Descriptor instead.
func (*UnivMonLayer) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{12}
}

func (x *UnivMonLayer) GetSketch() *CountSketchState {
	if x != nil {
		return x.Sketch
	}
	return nil
}

func (x *UnivMonLayer) GetHeap() *TopKState {
	if x != nil {
		return x.Heap
	}
	return nil
}

// HydraState is the portable state of a Hydra multi-sketch framework.
//
// Hydra maintains a grid of row_num child sketches (cells), each of the
// same type (counter_type). Items are routed to a specific row cell using a
// position hash derived from the item's subkey. An optional global "big
// counter" sketch aggregates the full stream.
//
// Current implementations set col_num = 1 (one sketch per row). The field is
// included for schema completeness and future extensions.
type HydraState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of sketch rows (D / number of subpopulations).
	RowNum uint32 `protobuf:"varint,1,opt,name=row_num,json=rowNum,proto3" json:"row_num,omitempty"`
	// Number of sketch columns per row. Currently always 1.
	ColNum uint32 `protobuf:"varint,2,opt,name=col_num,json=colNum,proto3" json:"col_num,omitempty"`
	// The sketch type used for every cell.
	CounterType HydraCounterType `protobuf:"varint,3,opt,name=counter_type,json=counterType,proto3,enum=sketchlib.v1.HydraCounterType" json:"counter_type,omitempty"`
	// Serialized cells in row-major order, length = row_num * col_num.
	// Each cell's oneof field must match counter_type.
	Cells []*HydraCell `protobuf:"bytes,4,rep,name=cells,proto3" json:"cells,omitempty"`
	// Optional global sketch covering the entire stream.
	// Absent when global counter is disabled (enable_global_counter = false).
	BigCounter *HydraCell `protobuf:"bytes,5,opt,name=big_counter,json=bigCounter,proto3" json:"big_counter,omitempty"`
	// Seed index used for subpopulation routing (Go: seedHydra, Rust: HYDRA_SEED).
	// Both libraries default to 6.
	SeedIndex uint32 `protobuf:"varint,6,opt,name=seed_index,json=seedIndex,proto3" json:"seed_index,omitempty"`
	// True when per-cell TopK tracking is enabled.
	EnableTopk bool `protobuf:"varint,7,opt,name=enable_topk,json=enableTopk,proto3" json:"enable_topk,omitempty"`
	// True when fanout subkey expansion is active.
	FanoutSubkeys bool `protobuf:"varint,8,opt,name=fanout_subkeys,json=fanoutSubkeys,proto3" json:"fanout_subkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HydraState) Reset() {
	*x = HydraState{}
	mi := &file_sketchlib_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HydraState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HydraState) ProtoMessage() {}

func (x *HydraState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HydraState.ProtoReflect.Descriptor instead.
func (*HydraState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{13}
}

func (x *HydraState) GetRowNum() uint32 {
	if x != nil {
		return x.RowNum
	}
	return 0
}

func (x *HydraState) GetColNum() uint32 {
	if x != nil {
		return x.ColNum
	}
	return 0
}

func (x *HydraState) GetCounterType() HydraCounterType {
	if x != nil {
		return x.CounterType
	}
	return HydraCounterType_HYDRA_COUNTER_TYPE_UNSPECIFIED
}

func (x *HydraState) GetCells() []*HydraCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *HydraState) GetBigCounter() *HydraCell {
	if x != nil {
		return x.BigCounter
	}
	return nil
}

func (x *HydraState) GetSeedIndex() uint32 {
	if x != nil {
		return x.SeedIndex
	}
	return 0
}

func (x *HydraState) GetEnableTopk() bool {
	if x != nil {
		return x.EnableTopk
	}
	return false
}

func (x *HydraState) GetFanoutSubkeys() bool {
	if x != nil {
		return x.FanoutSubkeys
	}
	return false
}

// CocoSketchState is the portable state of a CocoSketch flow-size estimator.
//
// The bucket table is stored flat in row-major order (d rows × width cols).
// Element [r][c] is at index r * width + c.
type CocoSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of hash rows.
	D uint32 `protobuf:"varint,1,opt,name=d,proto3" json:"d,omitempty"`
	// Number of buckets per row.
	Width uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// Full hash stored in each bucket, length = d * width.
	// Zero means the bucket is empty (has_keys[i] == false).
	Hashes []uint64 `protobuf:"varint,3,rep,packed,name=hashes,proto3" json:"hashes,omitempty"`
	// Cumulative count value per bucket, length = d * width.
	Vals []uint64 `protobuf:"varint,4,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	// Whether each bucket holds a valid key entry, length = d * width.
	HasKeys       []bool `protobuf:"varint,5,rep,packed,name=has_keys,json=hasKeys,proto3" json:"has_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CocoSketchState) Reset() {
	*x = CocoSketchState{}
	mi := &file_sketchlib_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CocoSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CocoSketchState) ProtoMessage() {}

func (x *CocoSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CocoSketchState.ProtoReflect.Descriptor instead.
func (*CocoSketchState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{14}
}

func (x *CocoSketchState) GetD() uint32 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *CocoSketchState) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CocoSketchState) GetHashes() []uint64 {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *CocoSketchState) GetVals() []uint64 {
	if x != nil {
		return x.Vals
	}
	return nil
}

func (x *CocoSketchState) GetHasKeys() []bool {
	if x != nil {
		return x.HasKeys
	}
	return nil
}

// ElasticState is the portable state of an Elastic Sketch.
//
// The Elastic Sketch has a heavy part (one bucket per index) and a light
// Count-Min layer. The heavy part is serialized as parallel arrays.
// The light layer is stored as a CountMinState with FLOAT64 counters.
type ElasticState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of heavy buckets.
	BucketCount uint32 `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount,proto3" json:"bucket_count,omitempty"`
	// Per-bucket flow identifiers (strings), length = bucket_count.
	// Empty string means the bucket is unoccupied.
	FlowIds []string `protobuf:"bytes,2,rep,name=flow_ids,json=flowIds,proto3" json:"flow_ids,omitempty"`
	// Positive vote counts per bucket, length = bucket_count.
	VotePos []int32 `protobuf:"zigzag32,3,rep,packed,name=vote_pos,json=votePos,proto3" json:"vote_pos,omitempty"`
	// Negative vote counts per bucket, length = bucket_count.
	VoteNeg []int32 `protobuf:"zigzag32,4,rep,packed,name=vote_neg,json=voteNeg,proto3" json:"vote_neg,omitempty"`
	// Whether each bucket is in eviction state, length = bucket_count.
	Evictions []bool `protobuf:"varint,5,rep,packed,name=evictions,proto3" json:"evictions,omitempty"`
	// Light Count-Min layer (FLOAT64 counters).
	Light         *CountMinState `protobuf:"bytes,6,opt,name=light,proto3" json:"light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElasticState) Reset() {
	*x = ElasticState{}
	mi := &file_sketchlib_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElasticState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticState) ProtoMessage() {}

func (x *ElasticState) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticState.ProtoReflect.Descriptor instead.
func (*ElasticState) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{15}
}

func (x *ElasticState) GetBucketCount() uint32 {
	if x != nil {
		return x.BucketCount
	}
	return 0
}

func (x *ElasticState) GetFlowIds() []string {
	if x != nil {
		return x.FlowIds
	}
	return nil
}

func (x *ElasticState) GetVotePos() []int32 {
	if x != nil {
		return x.VotePos
	}
	return nil
}

func (x *ElasticState) GetVoteNeg() []int32 {
	if x != nil {
		return x.VoteNeg
	}
	return nil
}

func (x *ElasticState) GetEvictions() []bool {
	if x != nil {
		return x.Evictions
	}
	return nil
}

func (x *ElasticState) GetLight() *CountMinState {
	if x != nil {
		return x.Light
	}
	return nil
}

// HydraCell holds the serialized state of one Hydra grid cell.
// Exactly one field in the oneof must be set, and it must match the parent
// HydraState.counter_type.
type HydraCell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sketch:
	//
	//	*HydraCell_CountMin
	//	*HydraCell_CountSketch
	//	*HydraCell_Hll
	//	*HydraCell_Kll
	//	*HydraCell_Univmon
	Sketch        isHydraCell_Sketch `protobuf_oneof:"sketch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HydraCell) Reset() {
	*x = HydraCell{}
	mi := &file_sketchlib_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HydraCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HydraCell) ProtoMessage() {}

func (x *HydraCell) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HydraCell.ProtoReflect.Descriptor instead.
func (*HydraCell) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{16}
}

func (x *HydraCell) GetSketch() isHydraCell_Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

func (x *HydraCell) GetCountMin() *CountMinState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_CountMin); ok {
			return x.CountMin
		}
	}
	return nil
}

func (x *HydraCell) GetCountSketch() *CountSketchState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_CountSketch); ok {
			return x.CountSketch
		}
	}
	return nil
}

func (x *HydraCell) GetHll() *HyperLogLogState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_Hll); ok {
			return x.Hll
		}
	}
	return nil
}

func (x *HydraCell) GetKll() *KLLState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_Kll); ok {
			return x.Kll
		}
	}
	return nil
}

func (x *HydraCell) GetUnivmon() *UnivMonState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_Univmon); ok {
			return x.Univmon
		}
	}
	return nil
}

type isHydraCell_Sketch interface {
	isHydraCell_Sketch()
}

type HydraCell_CountMin struct {
	CountMin *CountMinState `protobuf:"bytes,1,opt,name=count_min,json=countMin,proto3,oneof"`
}

type HydraCell_CountSketch struct {
	CountSketch *CountSketchState `protobuf:"bytes,2,opt,name=count_sketch,json=countSketch,proto3,oneof"`
}

type HydraCell_Hll struct {
	Hll *HyperLogLogState `protobuf:"bytes,3,opt,name=hll,proto3,oneof"`
}

type HydraCell_Kll struct {
	Kll *KLLState `protobuf:"bytes,4,opt,name=kll,proto3,oneof"`
}

type HydraCell_Univmon struct {
	Univmon *UnivMonState `protobuf:"bytes,5,opt,name=univmon,proto3,oneof"`
}

func (*HydraCell_CountMin) isHydraCell_Sketch() {}

func (*HydraCell_CountSketch) isHydraCell_Sketch() {}

func (*HydraCell_Hll) isHydraCell_Sketch() {}

func (*HydraCell_Kll) isHydraCell_Sketch() {}

func (*HydraCell_Univmon) isHydraCell_Sketch() {}

var File_sketchlib_proto protoreflect.FileDescriptor

const file_sketchlib_proto_rawDesc = "" +
	"\n" +
	"\x0fsketchlib.proto\x12\fsketchlib.v1\"\xad\x05\n" +
	"\x0eSketchEnvelope\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x126\n" +
	"\bproducer\x18\x02 \x01(\v2\x1a.sketchlib.v1.ProducerInfoR\bproducer\x123\n" +
	"\thash_spec\x18\x03 \x01(\v2\x16.sketchlib.v1.HashSpecR\bhashSpec\x12:\n" +
	"\tcount_min\x18\n" +
	" \x01(\v2\x1b.sketchlib.v1.CountMinStateH\x00R\bcountMin\x12C\n" +
	"\fcount_sketch\x18\v \x01(\v2\x1e.sketchlib.v1.CountSketchStateH\x00R\vcountSketch\x122\n" +
	"\x03hll\x18\f \x01(\v2\x1e.sketchlib.v1.HyperLogLogStateH\x00R\x03hll\x12*\n" +
	"\x03kll\x18\r \x01(\v2\x16.sketchlib.v1.KLLStateH\x00R\x03kll\x129\n" +
	"\bddsketch\x18\x0e \x01(\v2\x1b.sketchlib.v1.DDSketchStateH\x00R\bddsketch\x126\n" +
	"\aunivmon\x18\x0f \x01(\v2\x1a.sketchlib.v1.UnivMonStateH\x00R\aunivmon\x120\n" +
	"\x05hydra\x18\x10 \x01(\v2\x18.sketchlib.v1.HydraStateH\x00R\x05hydra\x123\n" +
	"\x04coco\x18\x11 \x01(\v2\x1d.sketchlib.v1.CocoSketchStateH\x00R\x04coco\x126\n" +
	"\aelastic\x18\x12 \x01(\v2\x1a.sketchlib.v1.ElasticStateH\x00R\aelasticB\x0e\n" +
	"\fsketch_stateJ\x04\b\x13\x10 \"B\n" +
	"\fProducerInfo\x12\x18\n" +
	"\alibrary\x18\x01 \x01(\tR\alibrary\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xdf\x01\n" +
	"\bHashSpec\x129\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1b.sketchlib.v1.HashAlgorithmR\talgorithm\x120\n" +
	"\x14canonical_seed_index\x18\x02 \x01(\rR\x12canonicalSeedIndex\x12\x1f\n" +
	"\tseed_list\x18\x03 \x03(\x04B\x02\x10\x01R\bseedList\x12E\n" +
	"\x0fseed_derivation\x18\x04 \x01(\x0e2\x1c.sketchlib.v1.SeedDerivationR\x0eseedDerivation\"\xb5\x02\n" +
	"\rCountMinState\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12<\n" +
	"\fcounter_type\x18\x03 \x01(\x0e2\x19.sketchlib.v1.CounterTypeR\vcounterType\x12!\n" +
	"\n" +
	"counts_int\x18\x04 \x03(\x12B\x02\x10\x01R\tcountsInt\x12%\n" +
	"\fcounts_float\x18\x05 \x03(\x01B\x02\x10\x01R\vcountsFloat\x12!\n" +
	"\n" +
	"sum_counts\x18\x06 \x03(\x01B\x02\x10\x01R\tsumCounts\x12#\n" +
	"\vsum2_counts\x18\a \x03(\x01B\x02\x10\x01R\n" +
	"sum2Counts\x12\x12\n" +
	"\x02l1\x18\b \x03(\x01B\x02\x10\x01R\x02l1\x12\x12\n" +
	"\x02l2\x18\t \x03(\x01B\x02\x10\x01R\x02l2J\x04\b\n" +
	"\x10\x10\"\x89\x02\n" +
	"\x10CountSketchState\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12<\n" +
	"\fcounter_type\x18\x03 \x01(\x0e2\x19.sketchlib.v1.CounterTypeR\vcounterType\x12!\n" +
	"\n" +
	"counts_int\x18\x04 \x03(\x12B\x02\x10\x01R\tcountsInt\x12%\n" +
	"\fcounts_float\x18\x05 \x03(\x01B\x02\x10\x01R\vcountsFloat\x12\x12\n" +
	"\x02l2\x18\x06 \x03(\x01B\x02\x10\x01R\x02l2\x12+\n" +
	"\x04topk\x18\a \x01(\v2\x17.sketchlib.v1.TopKStateR\x04topkJ\x04\b\b\x10\x10\"L\n" +
	"\tTopKState\x12\f\n" +
	"\x01k\x18\x01 \x01(\rR\x01k\x121\n" +
	"\aentries\x18\x02 \x03(\v2\x17.sketchlib.v1.HeapEntryR\aentries\"9\n" +
	"\tHeapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x01R\x05countJ\x04\b\x03\x10\x04\"\xd7\x01\n" +
	"\x10HyperLogLogState\x122\n" +
	"\avariant\x18\x01 \x01(\x0e2\x18.sketchlib.v1.HLLVariantR\avariant\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\rR\tprecision\x12\x1c\n" +
	"\tregisters\x18\x03 \x01(\fR\tregisters\x12\x19\n" +
	"\bhip_kxq0\x18\x04 \x01(\x01R\ahipKxq0\x12\x19\n" +
	"\bhip_kxq1\x18\x05 \x01(\x01R\ahipKxq1\x12\x17\n" +
	"\ahip_est\x18\x06 \x01(\x01R\x06hipEstJ\x04\b\a\x10\x10\"\xae\x01\n" +
	"\bKLLState\x12\f\n" +
	"\x01k\x18\x01 \x01(\rR\x01k\x12\f\n" +
	"\x01m\x18\x02 \x01(\rR\x01m\x12\x1d\n" +
	"\n" +
	"num_levels\x18\x03 \x01(\rR\tnumLevels\x12\x1a\n" +
	"\x06levels\x18\x04 \x03(\rB\x02\x10\x01R\x06levels\x12\x18\n" +
	"\x05items\x18\x05 \x03(\x01B\x02\x10\x01R\x05items\x12+\n" +
	"\x04coin\x18\x06 \x01(\v2\x17.sketchlib.v1.CoinStateR\x04coinJ\x04\b\a\x10\x10\"e\n" +
	"\tCoinState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x04R\x05state\x12\x1b\n" +
	"\tbit_cache\x18\x02 \x01(\x04R\bbitCache\x12%\n" +
	"\x0eremaining_bits\x18\x03 \x01(\rR\rremainingBits\"\xc1\x01\n" +
	"\rDDSketchState\x12\x14\n" +
	"\x05alpha\x18\x01 \x01(\x01R\x05alpha\x12%\n" +
	"\fstore_counts\x18\x02 \x03(\x04B\x02\x10\x01R\vstoreCounts\x12!\n" +
	"\fstore_offset\x18\x03 \x01(\x11R\vstoreOffset\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\x12\x10\n" +
	"\x03sum\x18\x05 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03min\x18\x06 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\a \x01(\x01R\x03maxJ\x04\b\b\x10\x10\"\xe7\x01\n" +
	"\fUnivMonState\x12\x1d\n" +
	"\n" +
	"layer_size\x18\x01 \x01(\rR\tlayerSize\x12\x1f\n" +
	"\vsketch_rows\x18\x02 \x01(\rR\n" +
	"sketchRows\x12\x1f\n" +
	"\vsketch_cols\x18\x03 \x01(\rR\n" +
	"sketchCols\x12\x1b\n" +
	"\theap_size\x18\x04 \x01(\rR\bheapSize\x12\x1f\n" +
	"\vbucket_size\x18\x05 \x01(\x04R\n" +
	"bucketSize\x122\n" +
	"\x06layers\x18\x06 \x03(\v2\x1a.sketchlib.v1.UnivMonLayerR\x06layersJ\x04\b\a\x10\x10\"s\n" +
	"\fUnivMonLayer\x126\n" +
	"\x06sketch\x18\x01 \x01(\v2\x1e.sketchlib.v1.CountSketchStateR\x06sketch\x12+\n" +
	"\x04heap\x18\x02 \x01(\v2\x17.sketchlib.v1.TopKStateR\x04heap\"\xd7\x02\n" +
	"\n" +
	"HydraState\x12\x17\n" +
	"\arow_num\x18\x01 \x01(\rR\x06rowNum\x12\x17\n" +
	"\acol_num\x18\x02 \x01(\rR\x06colNum\x12A\n" +
	"\fcounter_type\x18\x03 \x01(\x0e2\x1e.sketchlib.v1.HydraCounterTypeR\vcounterType\x12-\n" +
	"\x05cells\x18\x04 \x03(\v2\x17.sketchlib.v1.HydraCellR\x05cells\x128\n" +
	"\vbig_counter\x18\x05 \x01(\v2\x17.sketchlib.v1.HydraCellR\n" +
	"bigCounter\x12\x1d\n" +
	"\n" +
	"seed_index\x18\x06 \x01(\rR\tseedIndex\x12\x1f\n" +
	"\venable_topk\x18\a \x01(\bR\n" +
	"enableTopk\x12%\n" +
	"\x0efanout_subkeys\x18\b \x01(\bR\rfanoutSubkeysJ\x04\b\t\x10\x10\"\x8e\x01\n" +
	"\x0fCocoSketchState\x12\f\n" +
	"\x01d\x18\x01 \x01(\rR\x01d\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x1a\n" +
	"\x06hashes\x18\x03 \x03(\x04B\x02\x10\x01R\x06hashes\x12\x16\n" +
	"\x04vals\x18\x04 \x03(\x04B\x02\x10\x01R\x04vals\x12\x1d\n" +
	"\bhas_keys\x18\x05 \x03(\bB\x02\x10\x01R\ahasKeysJ\x04\b\x06\x10\x10\"\xe5\x01\n" +
	"\fElasticState\x12!\n" +
	"\fbucket_count\x18\x01 \x01(\rR\vbucketCount\x12\x19\n" +
	"\bflow_ids\x18\x02 \x03(\tR\aflowIds\x12\x1d\n" +
	"\bvote_pos\x18\x03 \x03(\x11B\x02\x10\x01R\avotePos\x12\x1d\n" +
	"\bvote_neg\x18\x04 \x03(\x11B\x02\x10\x01R\avoteNeg\x12 \n" +
	"\tevictions\x18\x05 \x03(\bB\x02\x10\x01R\tevictions\x121\n" +
	"\x05light\x18\x06 \x01(\v2\x1b.sketchlib.v1.CountMinStateR\x05lightJ\x04\b\a\x10\x10\"\xae\x02\n" +
	"\tHydraCell\x12:\n" +
	"\tcount_min\x18\x01 \x01(\v2\x1b.sketchlib.v1.CountMinStateH\x00R\bcountMin\x12C\n" +
	"\fcount_sketch\x18\x02 \x01(\v2\x1e.sketchlib.v1.CountSketchStateH\x00R\vcountSketch\x122\n" +
	"\x03hll\x18\x03 \x01(\v2\x1e.sketchlib.v1.HyperLogLogStateH\x00R\x03hll\x12*\n" +
	"\x03kll\x18\x04 \x01(\v2\x16.sketchlib.v1.KLLStateH\x00R\x03kll\x126\n" +
	"\aunivmon\x18\x05 \x01(\v2\x1a.sketchlib.v1.UnivMonStateH\x00R\aunivmonB\b\n" +
	"\x06sketch*\x85\x01\n" +
	"\rHashAlgorithm\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HASH_ALGORITHM_XXH3_64\x10\x01\x12\x1b\n" +
	"\x17HASH_ALGORITHM_XXH3_128\x10\x02\x12\x1b\n" +
	"\x17HASH_ALGORITHM_XXHASH64\x10\x03*r\n" +
	"\x0eSeedDerivation\x12\x1f\n" +
	"\x1bSEED_DERIVATION_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSEED_DERIVATION_ADDITIVE_OFFSET\x10\x01\x12\x1a\n" +
	"\x16SEED_DERIVATION_PACKED\x10\x02*\x8e\x01\n" +
	"\vCounterType\x12\x1c\n" +
	"\x18COUNTER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COUNTER_TYPE_INT32\x10\x01\x12\x16\n" +
	"\x12COUNTER_TYPE_INT64\x10\x02\x12\x17\n" +
	"\x13COUNTER_TYPE_INT128\x10\x03\x12\x18\n" +
	"\x14COUNTER_TYPE_FLOAT64\x10\x04*s\n" +
	"\n" +
	"HLLVariant\x12\x1b\n" +
	"\x17HLL_VARIANT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HLL_VARIANT_REGULAR\x10\x01\x12\x1a\n" +
	"\x16HLL_VARIANT_DATAFUSION\x10\x02\x12\x13\n" +
	"\x0fHLL_VARIANT_HIP\x10\x03*\xd5\x01\n" +
	"\x10HydraCounterType\x12\"\n" +
	"\x1eHYDRA_COUNTER_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cHYDRA_COUNTER_TYPE_COUNT_MIN\x10\x01\x12#\n" +
	"\x1fHYDRA_COUNTER_TYPE_COUNT_SKETCH\x10\x02\x12\x1a\n" +
	"\x16HYDRA_COUNTER_TYPE_HLL\x10\x03\x12\x1a\n" +
	"\x16HYDRA_COUNTER_TYPE_KLL\x10\x04\x12\x1e\n" +
	"\x1aHYDRA_COUNTER_TYPE_UNIVMON\x10\x05B7Z5github.com/ProjectASAP/sketchlib-go/proto/sketchlibpbb\x06proto3"

var (
	file_sketchlib_proto_rawDescOnce sync.Once
	file_sketchlib_proto_rawDescData []byte
)

func file_sketchlib_proto_rawDescGZIP() []byte {
	file_sketchlib_proto_rawDescOnce.Do(func() {
		file_sketchlib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)))
	})
	return file_sketchlib_proto_rawDescData
}

var file_sketchlib_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_sketchlib_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_sketchlib_proto_goTypes = []any{
	(HashAlgorithm)(0),       // 0: sketchlib.v1.HashAlgorithm
	(SeedDerivation)(0),      // 1: sketchlib.v1.SeedDerivation
	(CounterType)(0),         // 2: sketchlib.v1.CounterType
	(HLLVariant)(0),          // 3: sketchlib.v1.HLLVariant
	(HydraCounterType)(0),    // 4: sketchlib.v1.HydraCounterType
	(*SketchEnvelope)(nil),   // 5: sketchlib.v1.SketchEnvelope
	(*ProducerInfo)(nil),     // 6: sketchlib.v1.ProducerInfo
	(*HashSpec)(nil),         // 7: sketchlib.v1.HashSpec
	(*CountMinState)(nil),    // 8: sketchlib.v1.CountMinState
	(*CountSketchState)(nil), // 9: sketchlib.v1.CountSketchState
	(*TopKState)(nil),        // 10: sketchlib.v1.TopKState
	(*HeapEntry)(nil),        // 11: sketchlib.v1.HeapEntry
	(*HyperLogLogState)(nil), // 12: sketchlib.v1.HyperLogLogState
	(*KLLState)(nil),         // 13: sketchlib.v1.KLLState
	(*CoinState)(nil),        // 14: sketchlib.v1.CoinState
	(*DDSketchState)(nil),    // 15: sketchlib.v1.DDSketchState
	(*UnivMonState)(nil),     // 16: sketchlib.v1.UnivMonState
	(*UnivMonLayer)(nil),     // 17: sketchlib.v1.UnivMonLayer
	(*HydraState)(nil),       // 18: sketchlib.v1.HydraState
	(*CocoSketchState)(nil),  // 19: sketchlib.v1.CocoSketchState
	(*ElasticState)(nil),     // 20: sketchlib.v1.ElasticState
	(*HydraCell)(nil),        // 21: sketchlib.v1.HydraCell
}
var file_sketchlib_proto_depIdxs = []int32{
	6,  // 0: sketchlib.v1.SketchEnvelope.producer:type_name -> sketchlib.v1.ProducerInfo
	7,  // 1: sketchlib.v1.SketchEnvelope.hash_spec:type_name -> sketchlib.v1.HashSpec
	8,  // 2: sketchlib.v1.SketchEnvelope.count_min:type_name -> sketchlib.v1.CountMinState
	9,  // 3: sketchlib.v1.SketchEnvelope.count_sketch:type_name -> sketchlib.v1.CountSketchState
	12, // 4: sketchlib.v1.SketchEnvelope.hll:type_name -> sketchlib.v1.HyperLogLogState
	13, // 5: sketchlib.v1.SketchEnvelope.kll:type_name -> sketchlib.v1.KLLState
	15, // 6: sketchlib.v1.SketchEnvelope.ddsketch:type_name -> sketchlib.v1.DDSketchState
	16, // 7: sketchlib.v1.SketchEnvelope.univmon:type_name -> sketchlib.v1.UnivMonState
	18, // 8: sketchlib.v1.SketchEnvelope.hydra:type_name -> sketchlib.v1.HydraState
	19, // 9: sketchlib.v1.SketchEnvelope.coco:type_name -> sketchlib.v1.CocoSketchState
	20, // 10: sketchlib.v1.SketchEnvelope.elastic:type_name -> sketchlib.v1.ElasticState
	0,  // 11: sketchlib.v1.HashSpec.algorithm:type_name -> sketchlib.v1.HashAlgorithm
	1,  // 12: sketchlib.v1.HashSpec.seed_derivation:type_name -> sketchlib.v1.SeedDerivation
	2,  // 13: sketchlib.v1.CountMinState.counter_type:type_name -> sketchlib.v1.CounterType
	2,  // 14: sketchlib.v1.CountSketchState.counter_type:type_name -> sketchlib.v1.CounterType
	10, // 15: sketchlib.v1.CountSketchState.topk:type_name -> sketchlib.v1.TopKState
	11, // 16: sketchlib.v1.TopKState.entries:type_name -> sketchlib.v1.HeapEntry
	3,  // 17: sketchlib.v1.HyperLogLogState.variant:type_name -> sketchlib.v1.HLLVariant
	14, // 18: sketchlib.v1.KLLState.coin:type_name -> sketchlib.v1.CoinState
	17, // 19: sketchlib.v1.UnivMonState.layers:type_name -> sketchlib.v1.UnivMonLayer
	9,  // 20: sketchlib.v1.UnivMonLayer.sketch:type_name -> sketchlib.v1.CountSketchState
	10, // 21: sketchlib.v1.UnivMonLayer.heap:type_name -> sketchlib.v1.TopKState
	4,  // 22: sketchlib.v1.HydraState.counter_type:type_name -> sketchlib.v1.HydraCounterType
	21, // 23: sketchlib.v1.HydraState.cells:type_name -> sketchlib.v1.HydraCell
	21, // 24: sketchlib.v1.HydraState.big_counter:type_name -> sketchlib.v1.HydraCell
	8,  // 25: sketchlib.v1.ElasticState.light:type_name -> sketchlib.v1.CountMinState
	8,  // 26: sketchlib.v1.HydraCell.count_min:type_name -> sketchlib.v1.CountMinState
	9,  // 27: sketchlib.v1.HydraCell.count_sketch:type_name -> sketchlib.v1.CountSketchState
	12, // 28: sketchlib.v1.HydraCell.hll:type_name -> sketchlib.v1.HyperLogLogState
	13, // 29: sketchlib.v1.HydraCell.kll:type_name -> sketchlib.v1.KLLState
	16, // 30: sketchlib.v1.HydraCell.univmon:type_name -> sketchlib.v1.UnivMonState
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_sketchlib_proto_init() }
func file_sketchlib_proto_init() {
	if File_sketchlib_proto != nil {
		return
	}
	file_sketchlib_proto_msgTypes[0].OneofWrappers = []any{
		(*SketchEnvelope_CountMin)(nil),
		(*SketchEnvelope_CountSketch)(nil),
		(*SketchEnvelope_Hll)(nil),
		(*SketchEnvelope_Kll)(nil),
		(*SketchEnvelope_Ddsketch)(nil),
		(*SketchEnvelope_Univmon)(nil),
		(*SketchEnvelope_Hydra)(nil),
		(*SketchEnvelope_Coco)(nil),
		(*SketchEnvelope_Elastic)(nil),
	}
	file_sketchlib_proto_msgTypes[16].OneofWrappers = []any{
		(*HydraCell_CountMin)(nil),
		(*HydraCell_CountSketch)(nil),
		(*HydraCell_Hll)(nil),
		(*HydraCell_Kll)(nil),
		(*HydraCell_Univmon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sketchlib_proto_goTypes,
		DependencyIndexes: file_sketchlib_proto_depIdxs,
		EnumInfos:         file_sketchlib_proto_enumTypes,
		MessageInfos:      file_sketchlib_proto_msgTypes,
	}.Build()
	File_sketchlib_proto = out.File
	file_sketchlib_proto_goTypes = nil
	file_sketchlib_proto_depIdxs = nil
}
