// countsketch.proto — Portable wire format for Count Sketch state.
// Also contains TopKState and HeapEntry used by CountSketch and UnivMon.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: countsketch/countsketch.proto

package countsketchpb

import (
	common "github.com/ProjectASAP/sketchlib-go/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CountSketchState is the portable state of a Count (±1) Sketch.
//
// The counter matrix is signed because Count Sketch uses ±1 increments.
// The matrix layout is identical to CountMinState (row-major, flat).
//
// L2 norms are derived values and must be recomputed on load:
//
//	l2[r] = sqrt( sum_c counts[r][c]^2 )
//
// Producers may include them as a convenience for consumers that only query.
type CountSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matrix dimensions. Both must be > 0.
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Indicates which counts_* field below is populated.
	CounterType common.CounterType `protobuf:"varint,3,opt,name=counter_type,json=counterType,proto3,enum=sketchlib.v1.CounterType" json:"counter_type,omitempty"`
	// Signed integer counters in row-major order, length = rows * cols.
	// Populated when counter_type ∈ {INT32, INT64}.
	CountsInt []int64 `protobuf:"zigzag64,4,rep,packed,name=counts_int,json=countsInt,proto3" json:"counts_int,omitempty"`
	// Floating-point counters in row-major order, length = rows * cols.
	// Populated when counter_type = FLOAT64 (Go producer).
	CountsFloat []float64 `protobuf:"fixed64,5,rep,packed,name=counts_float,json=countsFloat,proto3" json:"counts_float,omitempty"`
	// Per-row L2 norms, length = rows. Derived — recompute on load if absent.
	L2 []float64 `protobuf:"fixed64,6,rep,packed,name=l2,proto3" json:"l2,omitempty"`
	// Optional heavy-hitter (TopK min-heap) state.
	// Absent when TopK tracking is disabled.
	Topk          *TopKState `protobuf:"bytes,7,opt,name=topk,proto3" json:"topk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountSketchState) Reset() {
	*x = CountSketchState{}
	mi := &file_countsketch_countsketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountSketchState) ProtoMessage() {}

func (x *CountSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_countsketch_countsketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountSketchState.ProtoReflect.Descriptor instead.
func (*CountSketchState) Descriptor() ([]byte, []int) {
	return file_countsketch_countsketch_proto_rawDescGZIP(), []int{0}
}

func (x *CountSketchState) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CountSketchState) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CountSketchState) GetCounterType() common.CounterType {
	if x != nil {
		return x.CounterType
	}
	return common.CounterType(0)
}

func (x *CountSketchState) GetCountsInt() []int64 {
	if x != nil {
		return x.CountsInt
	}
	return nil
}

func (x *CountSketchState) GetCountsFloat() []float64 {
	if x != nil {
		return x.CountsFloat
	}
	return nil
}

func (x *CountSketchState) GetL2() []float64 {
	if x != nil {
		return x.L2
	}
	return nil
}

func (x *CountSketchState) GetTopk() *TopKState {
	if x != nil {
		return x.Topk
	}
	return nil
}

// TopKState is the serialized state of a min-heap heavy-hitter tracker.
type TopKState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of entries retained.
	K uint32 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	// All retained entries. Order is not guaranteed (heap order is not preserved).
	Entries       []*HeapEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopKState) Reset() {
	*x = TopKState{}
	mi := &file_countsketch_countsketch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopKState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopKState) ProtoMessage() {}

func (x *TopKState) ProtoReflect() protoreflect.Message {
	mi := &file_countsketch_countsketch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopKState.ProtoReflect.Descriptor instead.
func (*TopKState) Descriptor() ([]byte, []int) {
	return file_countsketch_countsketch_proto_rawDescGZIP(), []int{1}
}

func (x *TopKState) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *TopKState) GetEntries() []*HeapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// HeapEntry is one heavy-hitter record inside a TopKState.
type HeapEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String key identifying the heavy hitter (e.g. flow ID, IP address).
	// For binary keys, producers should use base64 or hex encoding and document
	// their choice; a future bytes_key field is reserved at number 3.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Approximate frequency or weight accumulated for this key.
	Count         float64 `protobuf:"fixed64,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapEntry) Reset() {
	*x = HeapEntry{}
	mi := &file_countsketch_countsketch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapEntry) ProtoMessage() {}

func (x *HeapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_countsketch_countsketch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapEntry.ProtoReflect.Descriptor instead.
func (*HeapEntry) Descriptor() ([]byte, []int) {
	return file_countsketch_countsketch_proto_rawDescGZIP(), []int{2}
}

func (x *HeapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeapEntry) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_countsketch_countsketch_proto protoreflect.FileDescriptor

const file_countsketch_countsketch_proto_rawDesc = "" +
	"\n" +
	"\x1dcountsketch/countsketch.proto\x12\fsketchlib.v1\x1a\x13common/common.proto\"\x89\x02\n" +
	"\x10CountSketchState\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12<\n" +
	"\fcounter_type\x18\x03 \x01(\x0e2\x19.sketchlib.v1.CounterTypeR\vcounterType\x12!\n" +
	"\n" +
	"counts_int\x18\x04 \x03(\x12B\x02\x10\x01R\tcountsInt\x12%\n" +
	"\fcounts_float\x18\x05 \x03(\x01B\x02\x10\x01R\vcountsFloat\x12\x12\n" +
	"\x02l2\x18\x06 \x03(\x01B\x02\x10\x01R\x02l2\x12+\n" +
	"\x04topk\x18\a \x01(\v2\x17.sketchlib.v1.TopKStateR\x04topkJ\x04\b\b\x10\x10\"L\n" +
	"\tTopKState\x12\f\n" +
	"\x01k\x18\x01 \x01(\rR\x01k\x121\n" +
	"\aentries\x18\x02 \x03(\v2\x17.sketchlib.v1.HeapEntryR\aentries\"9\n" +
	"\tHeapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x01R\x05countJ\x04\b\x03\x10\x04BEZCgithub.com/ProjectASAP/sketchlib-go/proto/countsketch;countsketchpbb\x06proto3"

var (
	file_countsketch_countsketch_proto_rawDescOnce sync.Once
	file_countsketch_countsketch_proto_rawDescData []byte
)

func file_countsketch_countsketch_proto_rawDescGZIP() []byte {
	file_countsketch_countsketch_proto_rawDescOnce.Do(func() {
		file_countsketch_countsketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_countsketch_countsketch_proto_rawDesc), len(file_countsketch_countsketch_proto_rawDesc)))
	})
	return file_countsketch_countsketch_proto_rawDescData
}

var file_countsketch_countsketch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_countsketch_countsketch_proto_goTypes = []any{
	(*CountSketchState)(nil), // 0: sketchlib.v1.CountSketchState
	(*TopKState)(nil),        // 1: sketchlib.v1.TopKState
	(*HeapEntry)(nil),        // 2: sketchlib.v1.HeapEntry
	(common.CounterType)(0),  // 3: sketchlib.v1.CounterType
}
var file_countsketch_countsketch_proto_depIdxs = []int32{
	3, // 0: sketchlib.v1.CountSketchState.counter_type:type_name -> sketchlib.v1.CounterType
	1, // 1: sketchlib.v1.CountSketchState.topk:type_name -> sketchlib.v1.TopKState
	2, // 2: sketchlib.v1.TopKState.entries:type_name -> sketchlib.v1.HeapEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_countsketch_countsketch_proto_init() }
func file_countsketch_countsketch_proto_init() {
	if File_countsketch_countsketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_countsketch_countsketch_proto_rawDesc), len(file_countsketch_countsketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_countsketch_countsketch_proto_goTypes,
		DependencyIndexes: file_countsketch_countsketch_proto_depIdxs,
		MessageInfos:      file_countsketch_countsketch_proto_msgTypes,
	}.Build()
	File_countsketch_countsketch_proto = out.File
	file_countsketch_countsketch_proto_goTypes = nil
	file_countsketch_countsketch_proto_depIdxs = nil
}
