// kll.proto — Portable wire format for KLL quantile sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kll/kll.proto

package kllpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KLLState is the portable state of a KLL quantile sketch.
//
// The items array is partitioned into compaction levels by the levels[] array:
//
//	items[ levels[i] .. levels[i+1] )  are the retained items at level i.
//
// Derived state that must be recomputed on load (not serialized):
//
//	capacity_cache  — computed from k, m, and level boundaries.
//	level0_capacity — computed from k and num_levels.
//	top_height      — equals num_levels - 1.
type KLLState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target compactor capacity k. Must be >= 8.
	K uint32 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	// Minimum compactor size m. Must satisfy 2 <= m <= k.
	M uint32 `protobuf:"varint,2,opt,name=m,proto3" json:"m,omitempty"`
	// Number of levels currently in use.
	NumLevels uint32 `protobuf:"varint,3,opt,name=num_levels,json=numLevels,proto3" json:"num_levels,omitempty"`
	// Level boundary indices into items[], length = num_levels + 1.
	// levels[0] is always 0; levels[num_levels] = len(items).
	Levels []uint32 `protobuf:"varint,4,rep,packed,name=levels,proto3" json:"levels,omitempty"`
	// All retained samples in level order, length = levels[num_levels].
	Items []float64 `protobuf:"fixed64,5,rep,packed,name=items,proto3" json:"items,omitempty"`
	// Random bit generator state for deterministic compaction continuation.
	// Required for sketches that will receive further updates after loading.
	// Consumers that only query may ignore this field.
	Coin          *CoinState `protobuf:"bytes,6,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KLLState) Reset() {
	*x = KLLState{}
	mi := &file_kll_kll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KLLState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KLLState) ProtoMessage() {}

func (x *KLLState) ProtoReflect() protoreflect.Message {
	mi := &file_kll_kll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KLLState.ProtoReflect.Descriptor instead.
func (*KLLState) Descriptor() ([]byte, []int) {
	return file_kll_kll_proto_rawDescGZIP(), []int{0}
}

func (x *KLLState) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *KLLState) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *KLLState) GetNumLevels() uint32 {
	if x != nil {
		return x.NumLevels
	}
	return 0
}

func (x *KLLState) GetLevels() []uint32 {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *KLLState) GetItems() []float64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *KLLState) GetCoin() *CoinState {
	if x != nil {
		return x.Coin
	}
	return nil
}

// CoinState is the RNG used by KLL's probabilistic compaction.
// Both Go and Rust use an identical xorshift-based generator.
type CoinState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Xorshift generator internal state word.
	State uint64 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	// Up to 64 random bits buffered for single-bit coin flips.
	BitCache uint64 `protobuf:"varint,2,opt,name=bit_cache,json=bitCache,proto3" json:"bit_cache,omitempty"`
	// Number of valid bits remaining in bit_cache (0–64).
	RemainingBits uint32 `protobuf:"varint,3,opt,name=remaining_bits,json=remainingBits,proto3" json:"remaining_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinState) Reset() {
	*x = CoinState{}
	mi := &file_kll_kll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinState) ProtoMessage() {}

func (x *CoinState) ProtoReflect() protoreflect.Message {
	mi := &file_kll_kll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinState.ProtoReflect.Descriptor instead.
func (*CoinState) Descriptor() ([]byte, []int) {
	return file_kll_kll_proto_rawDescGZIP(), []int{1}
}

func (x *CoinState) GetState() uint64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CoinState) GetBitCache() uint64 {
	if x != nil {
		return x.BitCache
	}
	return 0
}

func (x *CoinState) GetRemainingBits() uint32 {
	if x != nil {
		return x.RemainingBits
	}
	return 0
}

var File_kll_kll_proto protoreflect.FileDescriptor

const file_kll_kll_proto_rawDesc = "" +
	"\n" +
	"\rkll/kll.proto\x12\fsketchlib.v1\"\xae\x01\n" +
	"\bKLLState\x12\f\n" +
	"\x01k\x18\x01 \x01(\rR\x01k\x12\f\n" +
	"\x01m\x18\x02 \x01(\rR\x01m\x12\x1d\n" +
	"\n" +
	"num_levels\x18\x03 \x01(\rR\tnumLevels\x12\x1a\n" +
	"\x06levels\x18\x04 \x03(\rB\x02\x10\x01R\x06levels\x12\x18\n" +
	"\x05items\x18\x05 \x03(\x01B\x02\x10\x01R\x05items\x12+\n" +
	"\x04coin\x18\x06 \x01(\v2\x17.sketchlib.v1.CoinStateR\x04coinJ\x04\b\a\x10\x10\"e\n" +
	"\tCoinState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x04R\x05state\x12\x1b\n" +
	"\tbit_cache\x18\x02 \x01(\x04R\bbitCache\x12%\n" +
	"\x0eremaining_bits\x18\x03 \x01(\rR\rremainingBitsB5Z3github.com/ProjectASAP/sketchlib-go/proto/kll;kllpbb\x06proto3"

var (
	file_kll_kll_proto_rawDescOnce sync.Once
	file_kll_kll_proto_rawDescData []byte
)

func file_kll_kll_proto_rawDescGZIP() []byte {
	file_kll_kll_proto_rawDescOnce.Do(func() {
		file_kll_kll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kll_kll_proto_rawDesc), len(file_kll_kll_proto_rawDesc)))
	})
	return file_kll_kll_proto_rawDescData
}

var file_kll_kll_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kll_kll_proto_goTypes = []any{
	(*KLLState)(nil),  // 0: sketchlib.v1.KLLState
	(*CoinState)(nil), // 1: sketchlib.v1.CoinState
}
var file_kll_kll_proto_depIdxs = []int32{
	1, // 0: sketchlib.v1.KLLState.coin:type_name -> sketchlib.v1.CoinState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kll_kll_proto_init() }
func file_kll_kll_proto_init() {
	if File_kll_kll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kll_kll_proto_rawDesc), len(file_kll_kll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kll_kll_proto_goTypes,
		DependencyIndexes: file_kll_kll_proto_depIdxs,
		MessageInfos:      file_kll_kll_proto_msgTypes,
	}.Build()
	File_kll_kll_proto = out.File
	file_kll_kll_proto_goTypes = nil
	file_kll_kll_proto_depIdxs = nil
}
