// elasticsketch.proto — Portable wire format for Elastic Sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: elasticsketch/elasticsketch.proto

package elasticsketchpb

import (
	countminsketch "github.com/ProjectASAP/sketchlib-go/proto/countminsketch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ElasticState is the portable state of an Elastic Sketch.
//
// The Elastic Sketch has a heavy part (one bucket per index) and a light
// Count-Min layer. The heavy part is serialized as parallel arrays.
// The light layer is stored as a CountMinState with FLOAT64 counters.
type ElasticState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of heavy buckets.
	BucketCount uint32 `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount,proto3" json:"bucket_count,omitempty"`
	// Per-bucket flow identifiers (strings), length = bucket_count.
	// Empty string means the bucket is unoccupied.
	FlowIds []string `protobuf:"bytes,2,rep,name=flow_ids,json=flowIds,proto3" json:"flow_ids,omitempty"`
	// Positive vote counts per bucket, length = bucket_count.
	VotePos []int32 `protobuf:"zigzag32,3,rep,packed,name=vote_pos,json=votePos,proto3" json:"vote_pos,omitempty"`
	// Negative vote counts per bucket, length = bucket_count.
	VoteNeg []int32 `protobuf:"zigzag32,4,rep,packed,name=vote_neg,json=voteNeg,proto3" json:"vote_neg,omitempty"`
	// Whether each bucket is in eviction state, length = bucket_count.
	Evictions []bool `protobuf:"varint,5,rep,packed,name=evictions,proto3" json:"evictions,omitempty"`
	// Light Count-Min layer (FLOAT64 counters).
	Light         *countminsketch.CountMinState `protobuf:"bytes,6,opt,name=light,proto3" json:"light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElasticState) Reset() {
	*x = ElasticState{}
	mi := &file_elasticsketch_elasticsketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElasticState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticState) ProtoMessage() {}

func (x *ElasticState) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsketch_elasticsketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticState.ProtoReflect.Descriptor instead.
func (*ElasticState) Descriptor() ([]byte, []int) {
	return file_elasticsketch_elasticsketch_proto_rawDescGZIP(), []int{0}
}

func (x *ElasticState) GetBucketCount() uint32 {
	if x != nil {
		return x.BucketCount
	}
	return 0
}

func (x *ElasticState) GetFlowIds() []string {
	if x != nil {
		return x.FlowIds
	}
	return nil
}

func (x *ElasticState) GetVotePos() []int32 {
	if x != nil {
		return x.VotePos
	}
	return nil
}

func (x *ElasticState) GetVoteNeg() []int32 {
	if x != nil {
		return x.VoteNeg
	}
	return nil
}

func (x *ElasticState) GetEvictions() []bool {
	if x != nil {
		return x.Evictions
	}
	return nil
}

func (x *ElasticState) GetLight() *countminsketch.CountMinState {
	if x != nil {
		return x.Light
	}
	return nil
}

var File_elasticsketch_elasticsketch_proto protoreflect.FileDescriptor

const file_elasticsketch_elasticsketch_proto_rawDesc = "" +
	"\n" +
	"!elasticsketch/elasticsketch.proto\x12\fsketchlib.v1\x1a#countminsketch/countminsketch.proto\"\xe5\x01\n" +
	"\fElasticState\x12!\n" +
	"\fbucket_count\x18\x01 \x01(\rR\vbucketCount\x12\x19\n" +
	"\bflow_ids\x18\x02 \x03(\tR\aflowIds\x12\x1d\n" +
	"\bvote_pos\x18\x03 \x03(\x11B\x02\x10\x01R\avotePos\x12\x1d\n" +
	"\bvote_neg\x18\x04 \x03(\x11B\x02\x10\x01R\avoteNeg\x12 \n" +
	"\tevictions\x18\x05 \x03(\bB\x02\x10\x01R\tevictions\x121\n" +
	"\x05light\x18\x06 \x01(\v2\x1b.sketchlib.v1.CountMinStateR\x05lightJ\x04\b\a\x10\x10BIZGgithub.com/ProjectASAP/sketchlib-go/proto/elasticsketch;elasticsketchpbb\x06proto3"

var (
	file_elasticsketch_elasticsketch_proto_rawDescOnce sync.Once
	file_elasticsketch_elasticsketch_proto_rawDescData []byte
)

func file_elasticsketch_elasticsketch_proto_rawDescGZIP() []byte {
	file_elasticsketch_elasticsketch_proto_rawDescOnce.Do(func() {
		file_elasticsketch_elasticsketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elasticsketch_elasticsketch_proto_rawDesc), len(file_elasticsketch_elasticsketch_proto_rawDesc)))
	})
	return file_elasticsketch_elasticsketch_proto_rawDescData
}

var file_elasticsketch_elasticsketch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_elasticsketch_elasticsketch_proto_goTypes = []any{
	(*ElasticState)(nil),                 // 0: sketchlib.v1.ElasticState
	(*countminsketch.CountMinState)(nil), // 1: sketchlib.v1.CountMinState
}
var file_elasticsketch_elasticsketch_proto_depIdxs = []int32{
	1, // 0: sketchlib.v1.ElasticState.light:type_name -> sketchlib.v1.CountMinState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_elasticsketch_elasticsketch_proto_init() }
func file_elasticsketch_elasticsketch_proto_init() {
	if File_elasticsketch_elasticsketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elasticsketch_elasticsketch_proto_rawDesc), len(file_elasticsketch_elasticsketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elasticsketch_elasticsketch_proto_goTypes,
		DependencyIndexes: file_elasticsketch_elasticsketch_proto_depIdxs,
		MessageInfos:      file_elasticsketch_elasticsketch_proto_msgTypes,
	}.Build()
	File_elasticsketch_elasticsketch_proto = out.File
	file_elasticsketch_elasticsketch_proto_goTypes = nil
	file_elasticsketch_elasticsketch_proto_depIdxs = nil
}
