// sketchlib.proto — Top-level envelope for sketchlib portable wire format.
//
// This file defines only the SketchEnvelope message. All sketch-specific
// message types live in their per-sketch proto files:
//
//   common/common.proto              — HashSpec, ProducerInfo, CounterType, ...
//   countminsketch/countminsketch.proto — CountMinState (embedded by Hydra and Elastic)
//   countsketch/countsketch.proto    — CountSketchState, TopKState, HeapEntry
//   kll/kll.proto                    — KLLState, CoinState
//   univmon/univmon.proto            — UnivMonState, UnivMonLayer
//   hydra/hydra.proto                — HydraState, HydraCounterType, HydraCell
//
// Design goals:
//   - Cross-language: Go (sketchlib-go) ↔ Rust (sketchlib-rust) round-trips.
//   - Forward-compatible: new fields use reserved numbers; old readers skip them.
//   - Logical state only: no pointers, no runtime caches, no gob/msgpack artefacts.
//   - Derived values (gamma, L2 norms, capacity caches) are always recomputed on load.
//   - Flat row-major arrays for all 2-D matrices.
//   - Hash specification is explicit so consumers can detect configuration mismatches.
//
// Version history:
//   1 — initial portable format (CountMin, Count, HLL, KLL)
//   2 — extended to UnivMon and Hydra (reserved, not yet stable)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: sketchlib.proto

package sketch_envelopepb

import (
	cocosketch "github.com/ProjectASAP/sketchlib-go/proto/cocosketch"
	common "github.com/ProjectASAP/sketchlib-go/proto/common"
	elasticsketch "github.com/ProjectASAP/sketchlib-go/proto/elasticsketch"
	hydra "github.com/ProjectASAP/sketchlib-go/proto/hydra"
	univmon "github.com/ProjectASAP/sketchlib-go/proto/univmon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SketchEnvelope is the portable container for all sketch transfers.
// Producers fill exactly one field inside sketch_state.
// Consumers check format_version first, then dispatch on the oneof.
type SketchEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version. Consumers should reject envelopes whose version exceeds
	// the highest version they understand.
	//
	//	1 = CountMin, Count, HLL, KLL
	//	2 = UnivMon, Hydra (reserved)
	//	3 = CocoSketch, ElasticSketch (reserved)
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Library and build info of the producing side.
	Producer *common.ProducerInfo `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Complete hashing configuration. Consumers must validate this against their
	// own configuration before performing updates or queries on the loaded sketch.
	// Mismatches do not prevent loading but will cause diverging results.
	HashSpec *common.HashSpec `protobuf:"bytes,3,opt,name=hash_spec,json=hashSpec,proto3" json:"hash_spec,omitempty"`
	// The sketch payload. Exactly one field must be set.
	//
	// Types that are valid to be assigned to SketchState:
	//
	//	*SketchEnvelope_Univmon
	//	*SketchEnvelope_Hydra
	//	*SketchEnvelope_Coco
	//	*SketchEnvelope_Elastic
	SketchState isSketchEnvelope_SketchState `protobuf_oneof:"sketch_state"`
	// Geometric / NitroSketch sampling probability for the producing sketch.
	//
	// The producer admits each stream update with probability `sample_p` (using
	// geometric skip-sampling, statistically identical to per-update Bernoulli(p))
	// and stores the RAW SAMPLED sketch state — never the rescaled state. The
	// consumer applies the `× 1/sample_p` rescale at QUERY time on the count-like
	// estimators (HLL cardinality, CountMin / CountSketch frequency, SUM / COUNT);
	// quantile estimators (KLL) are scale-invariant under uniform
	// sampling so they carry `sample_p` but need no rescale.
	//
	// Lives on the envelope (not per-sketch state) so downstream consumers that
	// construct per-sketch state structs by literal are unaffected.
	//
	// Dual-read default: a value of 0.0 (the proto3 default for an unset field)
	// is interpreted as 1.0 (exact, no sampling) for backward compatibility with
	// producers that predate this field. With sample_p = 1.0 a 0.0/unset envelope
	// is byte-identical to the pre-sampling format.
	SampleP       float64 `protobuf:"fixed64,4,opt,name=sample_p,json=sampleP,proto3" json:"sample_p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchEnvelope) Reset() {
	*x = SketchEnvelope{}
	mi := &file_sketchlib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchEnvelope) ProtoMessage() {}

func (x *SketchEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchEnvelope.ProtoReflect.Descriptor instead.
func (*SketchEnvelope) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{0}
}

func (x *SketchEnvelope) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SketchEnvelope) GetProducer() *common.ProducerInfo {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *SketchEnvelope) GetHashSpec() *common.HashSpec {
	if x != nil {
		return x.HashSpec
	}
	return nil
}

func (x *SketchEnvelope) GetSketchState() isSketchEnvelope_SketchState {
	if x != nil {
		return x.SketchState
	}
	return nil
}

func (x *SketchEnvelope) GetUnivmon() *univmon.UnivMonState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Univmon); ok {
			return x.Univmon
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHydra() *hydra.HydraState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hydra); ok {
			return x.Hydra
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCoco() *cocosketch.CocoSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Coco); ok {
			return x.Coco
		}
	}
	return nil
}

func (x *SketchEnvelope) GetElastic() *elasticsketch.ElasticState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Elastic); ok {
			return x.Elastic
		}
	}
	return nil
}

func (x *SketchEnvelope) GetSampleP() float64 {
	if x != nil {
		return x.SampleP
	}
	return 0
}

type isSketchEnvelope_SketchState interface {
	isSketchEnvelope_SketchState()
}

type SketchEnvelope_Univmon struct {
	Univmon *univmon.UnivMonState `protobuf:"bytes,15,opt,name=univmon,proto3,oneof"`
}

type SketchEnvelope_Hydra struct {
	Hydra *hydra.HydraState `protobuf:"bytes,16,opt,name=hydra,proto3,oneof"`
}

type SketchEnvelope_Coco struct {
	Coco *cocosketch.CocoSketchState `protobuf:"bytes,17,opt,name=coco,proto3,oneof"`
}

type SketchEnvelope_Elastic struct {
	Elastic *elasticsketch.ElasticState `protobuf:"bytes,18,opt,name=elastic,proto3,oneof"`
}

func (*SketchEnvelope_Univmon) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hydra) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Coco) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Elastic) isSketchEnvelope_SketchState() {}

// SketchDeltaEnvelope is the top-level wire container for delta payloads.
type SketchDeltaEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies which partition this delta belongs to.
	PartitionKey string `protobuf:"bytes,1,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// Unix milliseconds of the current window start. 0 when no window (Mode 1).
	WindowStartMs int64 `protobuf:"varint,2,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	// When true, the receiver should finalize and reset its accumulator for
	// this (partition_key, window_start_ms) after applying this delta.
	IsWindowClose bool `protobuf:"varint,3,opt,name=is_window_close,json=isWindowClose,proto3" json:"is_window_close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchDeltaEnvelope) Reset() {
	*x = SketchDeltaEnvelope{}
	mi := &file_sketchlib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchDeltaEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchDeltaEnvelope) ProtoMessage() {}

func (x *SketchDeltaEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchDeltaEnvelope.ProtoReflect.Descriptor instead.
func (*SketchDeltaEnvelope) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{1}
}

func (x *SketchDeltaEnvelope) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *SketchDeltaEnvelope) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *SketchDeltaEnvelope) GetIsWindowClose() bool {
	if x != nil {
		return x.IsWindowClose
	}
	return false
}

var File_sketchlib_proto protoreflect.FileDescriptor

const file_sketchlib_proto_rawDesc = "" +
	"\n" +
	"\x0fsketchlib.proto\x12\fsketchlib.v1\x1a\x13common/common.proto\x1a\x15univmon/univmon.proto\x1a\x11hydra/hydra.proto\x1a\x1bcocosketch/cocosketch.proto\x1a!elasticsketch/elasticsketch.proto\"\xf7\x03\n" +
	"\x0eSketchEnvelope\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x126\n" +
	"\bproducer\x18\x02 \x01(\v2\x1a.sketchlib.v1.ProducerInfoR\bproducer\x123\n" +
	"\thash_spec\x18\x03 \x01(\v2\x16.sketchlib.v1.HashSpecR\bhashSpec\x126\n" +
	"\aunivmon\x18\x0f \x01(\v2\x1a.sketchlib.v1.UnivMonStateH\x00R\aunivmon\x120\n" +
	"\x05hydra\x18\x10 \x01(\v2\x18.sketchlib.v1.HydraStateH\x00R\x05hydra\x123\n" +
	"\x04coco\x18\x11 \x01(\v2\x1d.sketchlib.v1.CocoSketchStateH\x00R\x04coco\x126\n" +
	"\aelastic\x18\x12 \x01(\v2\x1a.sketchlib.v1.ElasticStateH\x00R\aelastic\x12\x19\n" +
	"\bsample_p\x18\x04 \x01(\x01R\asamplePB\x0e\n" +
	"\fsketch_stateJ\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x13\x10 R\tcount_minR\fcount_sketchR\x03hllR\x03kllR\bddsketch\"\xca\x01\n" +
	"\x13SketchDeltaEnvelope\x12#\n" +
	"\rpartition_key\x18\x01 \x01(\tR\fpartitionKey\x12&\n" +
	"\x0fwindow_start_ms\x18\x02 \x01(\x03R\rwindowStartMs\x12&\n" +
	"\x0fis_window_close\x18\x03 \x01(\bR\risWindowCloseJ\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eR\tcount_minR\fcount_sketchR\x03hllR\bddsketchBMZKgithub.com/ProjectASAP/sketchlib-go/proto/sketch_envelope;sketch_envelopepbb\x06proto3"

var (
	file_sketchlib_proto_rawDescOnce sync.Once
	file_sketchlib_proto_rawDescData []byte
)

func file_sketchlib_proto_rawDescGZIP() []byte {
	file_sketchlib_proto_rawDescOnce.Do(func() {
		file_sketchlib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)))
	})
	return file_sketchlib_proto_rawDescData
}

var file_sketchlib_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sketchlib_proto_goTypes = []any{
	(*SketchEnvelope)(nil),             // 0: sketchlib.v1.SketchEnvelope
	(*SketchDeltaEnvelope)(nil),        // 1: sketchlib.v1.SketchDeltaEnvelope
	(*common.ProducerInfo)(nil),        // 2: sketchlib.v1.ProducerInfo
	(*common.HashSpec)(nil),            // 3: sketchlib.v1.HashSpec
	(*univmon.UnivMonState)(nil),       // 4: sketchlib.v1.UnivMonState
	(*hydra.HydraState)(nil),           // 5: sketchlib.v1.HydraState
	(*cocosketch.CocoSketchState)(nil), // 6: sketchlib.v1.CocoSketchState
	(*elasticsketch.ElasticState)(nil), // 7: sketchlib.v1.ElasticState
}
var file_sketchlib_proto_depIdxs = []int32{
	2, // 0: sketchlib.v1.SketchEnvelope.producer:type_name -> sketchlib.v1.ProducerInfo
	3, // 1: sketchlib.v1.SketchEnvelope.hash_spec:type_name -> sketchlib.v1.HashSpec
	4, // 2: sketchlib.v1.SketchEnvelope.univmon:type_name -> sketchlib.v1.UnivMonState
	5, // 3: sketchlib.v1.SketchEnvelope.hydra:type_name -> sketchlib.v1.HydraState
	6, // 4: sketchlib.v1.SketchEnvelope.coco:type_name -> sketchlib.v1.CocoSketchState
	7, // 5: sketchlib.v1.SketchEnvelope.elastic:type_name -> sketchlib.v1.ElasticState
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sketchlib_proto_init() }
func file_sketchlib_proto_init() {
	if File_sketchlib_proto != nil {
		return
	}
	file_sketchlib_proto_msgTypes[0].OneofWrappers = []any{
		(*SketchEnvelope_Univmon)(nil),
		(*SketchEnvelope_Hydra)(nil),
		(*SketchEnvelope_Coco)(nil),
		(*SketchEnvelope_Elastic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sketchlib_proto_goTypes,
		DependencyIndexes: file_sketchlib_proto_depIdxs,
		MessageInfos:      file_sketchlib_proto_msgTypes,
	}.Build()
	File_sketchlib_proto = out.File
	file_sketchlib_proto_goTypes = nil
	file_sketchlib_proto_depIdxs = nil
}
