// sketchlib.proto — Top-level envelope for sketchlib portable wire format.
//
// This file defines only the SketchEnvelope message. All sketch-specific
// message types live in their per-sketch proto files:
//
//   common/common.proto              — HashSpec, ProducerInfo, CounterType, ...
//   countminsketch/countminsketch.proto — CountMinState
//   countsketch/countsketch.proto    — CountSketchState, TopKState, HeapEntry
//   hll/hll.proto                    — HyperLogLogState, HLLVariant
//   kll/kll.proto                    — KLLState, CoinState
//   ddsketch/ddsketch.proto          — DDSketchState
//   univmon/univmon.proto            — UnivMonState, UnivMonLayer
//   hydra/hydra.proto                — HydraState, HydraCounterType, HydraCell
//
// Design goals:
//   - Cross-language: Go (sketchlib-go) ↔ Rust (sketchlib-rust) round-trips.
//   - Forward-compatible: new fields use reserved numbers; old readers skip them.
//   - Logical state only: no pointers, no runtime caches, no gob/msgpack artefacts.
//   - Derived values (gamma, L2 norms, capacity caches) are always recomputed on load.
//   - Flat row-major arrays for all 2-D matrices.
//   - Hash specification is explicit so consumers can detect configuration mismatches.
//
// Version history:
//   1 — initial portable format (CountMin, Count, HLL, KLL, DDSketch)
//   2 — extended to UnivMon and Hydra (reserved, not yet stable)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sketchlib.proto

package sketch_envelopepb

import (
	cocosketch "github.com/ProjectASAP/sketchlib-go/proto/cocosketch"
	common "github.com/ProjectASAP/sketchlib-go/proto/common"
	countminsketch "github.com/ProjectASAP/sketchlib-go/proto/countminsketch"
	countsketch "github.com/ProjectASAP/sketchlib-go/proto/countsketch"
	ddsketch "github.com/ProjectASAP/sketchlib-go/proto/ddsketch"
	elasticsketch "github.com/ProjectASAP/sketchlib-go/proto/elasticsketch"
	hll "github.com/ProjectASAP/sketchlib-go/proto/hll"
	hydra "github.com/ProjectASAP/sketchlib-go/proto/hydra"
	kll "github.com/ProjectASAP/sketchlib-go/proto/kll"
	univmon "github.com/ProjectASAP/sketchlib-go/proto/univmon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SketchEnvelope is the portable container for all sketch transfers.
// Producers fill exactly one field inside sketch_state.
// Consumers check format_version first, then dispatch on the oneof.
type SketchEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version. Consumers should reject envelopes whose version exceeds
	// the highest version they understand.
	//
	//	1 = CountMin, Count, HLL, KLL, DDSketch
	//	2 = UnivMon, Hydra (reserved)
	//	3 = CocoSketch, ElasticSketch (reserved)
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Library and build info of the producing side.
	Producer *common.ProducerInfo `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Complete hashing configuration. Consumers must validate this against their
	// own configuration before performing updates or queries on the loaded sketch.
	// Mismatches do not prevent loading but will cause diverging results.
	HashSpec *common.HashSpec `protobuf:"bytes,3,opt,name=hash_spec,json=hashSpec,proto3" json:"hash_spec,omitempty"`
	// The sketch payload. Exactly one field must be set.
	//
	// Types that are valid to be assigned to SketchState:
	//
	//	*SketchEnvelope_CountMin
	//	*SketchEnvelope_CountSketch
	//	*SketchEnvelope_Hll
	//	*SketchEnvelope_Kll
	//	*SketchEnvelope_Ddsketch
	//	*SketchEnvelope_Univmon
	//	*SketchEnvelope_Hydra
	//	*SketchEnvelope_Coco
	//	*SketchEnvelope_Elastic
	SketchState   isSketchEnvelope_SketchState `protobuf_oneof:"sketch_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchEnvelope) Reset() {
	*x = SketchEnvelope{}
	mi := &file_sketchlib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchEnvelope) ProtoMessage() {}

func (x *SketchEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchEnvelope.ProtoReflect.Descriptor instead.
func (*SketchEnvelope) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{0}
}

func (x *SketchEnvelope) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SketchEnvelope) GetProducer() *common.ProducerInfo {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *SketchEnvelope) GetHashSpec() *common.HashSpec {
	if x != nil {
		return x.HashSpec
	}
	return nil
}

func (x *SketchEnvelope) GetSketchState() isSketchEnvelope_SketchState {
	if x != nil {
		return x.SketchState
	}
	return nil
}

func (x *SketchEnvelope) GetCountMin() *countminsketch.CountMinState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_CountMin); ok {
			return x.CountMin
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCountSketch() *countsketch.CountSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_CountSketch); ok {
			return x.CountSketch
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHll() *hll.HyperLogLogState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hll); ok {
			return x.Hll
		}
	}
	return nil
}

func (x *SketchEnvelope) GetKll() *kll.KLLState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Kll); ok {
			return x.Kll
		}
	}
	return nil
}

func (x *SketchEnvelope) GetDdsketch() *ddsketch.DDSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Ddsketch); ok {
			return x.Ddsketch
		}
	}
	return nil
}

func (x *SketchEnvelope) GetUnivmon() *univmon.UnivMonState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Univmon); ok {
			return x.Univmon
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHydra() *hydra.HydraState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hydra); ok {
			return x.Hydra
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCoco() *cocosketch.CocoSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Coco); ok {
			return x.Coco
		}
	}
	return nil
}

func (x *SketchEnvelope) GetElastic() *elasticsketch.ElasticState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Elastic); ok {
			return x.Elastic
		}
	}
	return nil
}

type isSketchEnvelope_SketchState interface {
	isSketchEnvelope_SketchState()
}

type SketchEnvelope_CountMin struct {
	CountMin *countminsketch.CountMinState `protobuf:"bytes,10,opt,name=count_min,json=countMin,proto3,oneof"`
}

type SketchEnvelope_CountSketch struct {
	CountSketch *countsketch.CountSketchState `protobuf:"bytes,11,opt,name=count_sketch,json=countSketch,proto3,oneof"`
}

type SketchEnvelope_Hll struct {
	Hll *hll.HyperLogLogState `protobuf:"bytes,12,opt,name=hll,proto3,oneof"`
}

type SketchEnvelope_Kll struct {
	Kll *kll.KLLState `protobuf:"bytes,13,opt,name=kll,proto3,oneof"`
}

type SketchEnvelope_Ddsketch struct {
	Ddsketch *ddsketch.DDSketchState `protobuf:"bytes,14,opt,name=ddsketch,proto3,oneof"`
}

type SketchEnvelope_Univmon struct {
	Univmon *univmon.UnivMonState `protobuf:"bytes,15,opt,name=univmon,proto3,oneof"`
}

type SketchEnvelope_Hydra struct {
	Hydra *hydra.HydraState `protobuf:"bytes,16,opt,name=hydra,proto3,oneof"`
}

type SketchEnvelope_Coco struct {
	Coco *cocosketch.CocoSketchState `protobuf:"bytes,17,opt,name=coco,proto3,oneof"`
}

type SketchEnvelope_Elastic struct {
	Elastic *elasticsketch.ElasticState `protobuf:"bytes,18,opt,name=elastic,proto3,oneof"`
}

func (*SketchEnvelope_CountMin) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_CountSketch) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hll) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Kll) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Ddsketch) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Univmon) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hydra) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Coco) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Elastic) isSketchEnvelope_SketchState() {}

var File_sketchlib_proto protoreflect.FileDescriptor

const file_sketchlib_proto_rawDesc = "" +
	"\n" +
	"\x0fsketchlib.proto\x12\fsketchlib.v1\x1a\x13common/common.proto\x1a#countminsketch/countminsketch.proto\x1a\x1dcountsketch/countsketch.proto\x1a\rhll/hll.proto\x1a\rkll/kll.proto\x1a\x17ddsketch/ddsketch.proto\x1a\x15univmon/univmon.proto\x1a\x11hydra/hydra.proto\x1a\x1bcocosketch/cocosketch.proto\x1a!elasticsketch/elasticsketch.proto\"\xad\x05\n" +
	"\x0eSketchEnvelope\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x126\n" +
	"\bproducer\x18\x02 \x01(\v2\x1a.sketchlib.v1.ProducerInfoR\bproducer\x123\n" +
	"\thash_spec\x18\x03 \x01(\v2\x16.sketchlib.v1.HashSpecR\bhashSpec\x12:\n" +
	"\tcount_min\x18\n" +
	" \x01(\v2\x1b.sketchlib.v1.CountMinStateH\x00R\bcountMin\x12C\n" +
	"\fcount_sketch\x18\v \x01(\v2\x1e.sketchlib.v1.CountSketchStateH\x00R\vcountSketch\x122\n" +
	"\x03hll\x18\f \x01(\v2\x1e.sketchlib.v1.HyperLogLogStateH\x00R\x03hll\x12*\n" +
	"\x03kll\x18\r \x01(\v2\x16.sketchlib.v1.KLLStateH\x00R\x03kll\x129\n" +
	"\bddsketch\x18\x0e \x01(\v2\x1b.sketchlib.v1.DDSketchStateH\x00R\bddsketch\x126\n" +
	"\aunivmon\x18\x0f \x01(\v2\x1a.sketchlib.v1.UnivMonStateH\x00R\aunivmon\x120\n" +
	"\x05hydra\x18\x10 \x01(\v2\x18.sketchlib.v1.HydraStateH\x00R\x05hydra\x123\n" +
	"\x04coco\x18\x11 \x01(\v2\x1d.sketchlib.v1.CocoSketchStateH\x00R\x04coco\x126\n" +
	"\aelastic\x18\x12 \x01(\v2\x1a.sketchlib.v1.ElasticStateH\x00R\aelasticB\x0e\n" +
	"\fsketch_stateJ\x04\b\x13\x10 BMZKgithub.com/ProjectASAP/sketchlib-go/proto/sketch_envelope;sketch_envelopepbb\x06proto3"

var (
	file_sketchlib_proto_rawDescOnce sync.Once
	file_sketchlib_proto_rawDescData []byte
)

func file_sketchlib_proto_rawDescGZIP() []byte {
	file_sketchlib_proto_rawDescOnce.Do(func() {
		file_sketchlib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)))
	})
	return file_sketchlib_proto_rawDescData
}

var file_sketchlib_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sketchlib_proto_goTypes = []any{
	(*SketchEnvelope)(nil),               // 0: sketchlib.v1.SketchEnvelope
	(*common.ProducerInfo)(nil),          // 1: sketchlib.v1.ProducerInfo
	(*common.HashSpec)(nil),              // 2: sketchlib.v1.HashSpec
	(*countminsketch.CountMinState)(nil), // 3: sketchlib.v1.CountMinState
	(*countsketch.CountSketchState)(nil), // 4: sketchlib.v1.CountSketchState
	(*hll.HyperLogLogState)(nil),         // 5: sketchlib.v1.HyperLogLogState
	(*kll.KLLState)(nil),                 // 6: sketchlib.v1.KLLState
	(*ddsketch.DDSketchState)(nil),       // 7: sketchlib.v1.DDSketchState
	(*univmon.UnivMonState)(nil),         // 8: sketchlib.v1.UnivMonState
	(*hydra.HydraState)(nil),             // 9: sketchlib.v1.HydraState
	(*cocosketch.CocoSketchState)(nil),   // 10: sketchlib.v1.CocoSketchState
	(*elasticsketch.ElasticState)(nil),   // 11: sketchlib.v1.ElasticState
}
var file_sketchlib_proto_depIdxs = []int32{
	1,  // 0: sketchlib.v1.SketchEnvelope.producer:type_name -> sketchlib.v1.ProducerInfo
	2,  // 1: sketchlib.v1.SketchEnvelope.hash_spec:type_name -> sketchlib.v1.HashSpec
	3,  // 2: sketchlib.v1.SketchEnvelope.count_min:type_name -> sketchlib.v1.CountMinState
	4,  // 3: sketchlib.v1.SketchEnvelope.count_sketch:type_name -> sketchlib.v1.CountSketchState
	5,  // 4: sketchlib.v1.SketchEnvelope.hll:type_name -> sketchlib.v1.HyperLogLogState
	6,  // 5: sketchlib.v1.SketchEnvelope.kll:type_name -> sketchlib.v1.KLLState
	7,  // 6: sketchlib.v1.SketchEnvelope.ddsketch:type_name -> sketchlib.v1.DDSketchState
	8,  // 7: sketchlib.v1.SketchEnvelope.univmon:type_name -> sketchlib.v1.UnivMonState
	9,  // 8: sketchlib.v1.SketchEnvelope.hydra:type_name -> sketchlib.v1.HydraState
	10, // 9: sketchlib.v1.SketchEnvelope.coco:type_name -> sketchlib.v1.CocoSketchState
	11, // 10: sketchlib.v1.SketchEnvelope.elastic:type_name -> sketchlib.v1.ElasticState
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sketchlib_proto_init() }
func file_sketchlib_proto_init() {
	if File_sketchlib_proto != nil {
		return
	}
	file_sketchlib_proto_msgTypes[0].OneofWrappers = []any{
		(*SketchEnvelope_CountMin)(nil),
		(*SketchEnvelope_CountSketch)(nil),
		(*SketchEnvelope_Hll)(nil),
		(*SketchEnvelope_Kll)(nil),
		(*SketchEnvelope_Ddsketch)(nil),
		(*SketchEnvelope_Univmon)(nil),
		(*SketchEnvelope_Hydra)(nil),
		(*SketchEnvelope_Coco)(nil),
		(*SketchEnvelope_Elastic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sketchlib_proto_goTypes,
		DependencyIndexes: file_sketchlib_proto_depIdxs,
		MessageInfos:      file_sketchlib_proto_msgTypes,
	}.Build()
	File_sketchlib_proto = out.File
	file_sketchlib_proto_goTypes = nil
	file_sketchlib_proto_depIdxs = nil
}
