// sketchlib.proto — Top-level envelope for sketchlib portable wire format.
//
// This file defines only the SketchEnvelope message. All sketch-specific
// message types live in their per-sketch proto files:
//
//   common/common.proto              — HashSpec, ProducerInfo, CounterType, ...
//   countminsketch/countminsketch.proto — CountMinState, CountMinDelta, CountMinCell
//   countsketch/countsketch.proto    — CountSketchState, TopKState, HeapEntry, CountSketchDelta, CountSketchCell
//   hll/hll.proto                    — HyperLogLogState, HLLVariant, HLLDelta, HLLRegisterUpdate
//   kll/kll.proto                    — KLLState, CoinState
//   ddsketch/ddsketch.proto          — DDSketchState, DDSketchDelta, DDSketchBucketDelta
//   univmon/univmon.proto            — UnivMonState, UnivMonLayer
//   hydra/hydra.proto                — HydraState, HydraCounterType, HydraCell
//
// Design goals:
//   - Cross-language: Go (sketchlib-go) ↔ Rust (sketchlib-rust) round-trips.
//   - Forward-compatible: new fields use reserved numbers; old readers skip them.
//   - Logical state only: no pointers, no runtime caches, no gob/msgpack artefacts.
//   - Derived values (gamma, L2 norms, capacity caches) are always recomputed on load.
//   - Flat row-major arrays for all 2-D matrices.
//   - Hash specification is explicit so consumers can detect configuration mismatches.
//
// Version history:
//   1 — initial portable format (CountMin, Count, HLL, KLL, DDSketch)
//   2 — extended to UnivMon and Hydra (reserved, not yet stable)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: sketchlib.proto

package sketch_envelopepb

import (
	cocosketch "github.com/ProjectASAP/sketchlib-go/proto/cocosketch"
	common "github.com/ProjectASAP/sketchlib-go/proto/common"
	countminsketch "github.com/ProjectASAP/sketchlib-go/proto/countminsketch"
	countsketch "github.com/ProjectASAP/sketchlib-go/proto/countsketch"
	ddsketch "github.com/ProjectASAP/sketchlib-go/proto/ddsketch"
	elasticsketch "github.com/ProjectASAP/sketchlib-go/proto/elasticsketch"
	hll "github.com/ProjectASAP/sketchlib-go/proto/hll"
	hydra "github.com/ProjectASAP/sketchlib-go/proto/hydra"
	kll "github.com/ProjectASAP/sketchlib-go/proto/kll"
	univmon "github.com/ProjectASAP/sketchlib-go/proto/univmon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SketchEnvelope is the portable container for all sketch transfers.
// Producers fill exactly one field inside sketch_state.
// Consumers check format_version first, then dispatch on the oneof.
type SketchEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version. Consumers should reject envelopes whose version exceeds
	// the highest version they understand.
	//
	//	1 = CountMin, Count, HLL, KLL, DDSketch
	//	2 = UnivMon, Hydra (reserved)
	//	3 = CocoSketch, ElasticSketch (reserved)
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Library and build info of the producing side.
	Producer *common.ProducerInfo `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Complete hashing configuration. Consumers must validate this against their
	// own configuration before performing updates or queries on the loaded sketch.
	// Mismatches do not prevent loading but will cause diverging results.
	HashSpec *common.HashSpec `protobuf:"bytes,3,opt,name=hash_spec,json=hashSpec,proto3" json:"hash_spec,omitempty"`
	// The sketch payload. Exactly one field must be set.
	//
	// Types that are valid to be assigned to SketchState:
	//
	//	*SketchEnvelope_CountMin
	//	*SketchEnvelope_CountSketch
	//	*SketchEnvelope_Hll
	//	*SketchEnvelope_Kll
	//	*SketchEnvelope_Ddsketch
	//	*SketchEnvelope_Univmon
	//	*SketchEnvelope_Hydra
	//	*SketchEnvelope_Coco
	//	*SketchEnvelope_Elastic
	SketchState isSketchEnvelope_SketchState `protobuf_oneof:"sketch_state"`
	// Geometric / NitroSketch sampling probability for the producing sketch.
	//
	// The producer admits each stream update with probability `sample_p` (using
	// geometric skip-sampling, statistically identical to per-update Bernoulli(p))
	// and stores the RAW SAMPLED sketch state — never the rescaled state. The
	// consumer applies the `× 1/sample_p` rescale at QUERY time on the count-like
	// estimators (HLL cardinality, CountMin / CountSketch frequency, SUM / COUNT);
	// quantile estimators (KLL, DDSketch) are scale-invariant under uniform
	// sampling so they carry `sample_p` but need no rescale.
	//
	// Lives on the envelope (not per-sketch state) so downstream consumers that
	// construct per-sketch state structs by literal are unaffected.
	//
	// Dual-read default: a value of 0.0 (the proto3 default for an unset field)
	// is interpreted as 1.0 (exact, no sampling) for backward compatibility with
	// producers that predate this field. With sample_p = 1.0 a 0.0/unset envelope
	// is byte-identical to the pre-sampling format.
	SampleP       float64 `protobuf:"fixed64,4,opt,name=sample_p,json=sampleP,proto3" json:"sample_p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchEnvelope) Reset() {
	*x = SketchEnvelope{}
	mi := &file_sketchlib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchEnvelope) ProtoMessage() {}

func (x *SketchEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchEnvelope.ProtoReflect.Descriptor instead.
func (*SketchEnvelope) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{0}
}

func (x *SketchEnvelope) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SketchEnvelope) GetProducer() *common.ProducerInfo {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *SketchEnvelope) GetHashSpec() *common.HashSpec {
	if x != nil {
		return x.HashSpec
	}
	return nil
}

func (x *SketchEnvelope) GetSketchState() isSketchEnvelope_SketchState {
	if x != nil {
		return x.SketchState
	}
	return nil
}

func (x *SketchEnvelope) GetCountMin() *countminsketch.CountMinState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_CountMin); ok {
			return x.CountMin
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCountSketch() *countsketch.CountSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_CountSketch); ok {
			return x.CountSketch
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHll() *hll.HyperLogLogState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hll); ok {
			return x.Hll
		}
	}
	return nil
}

func (x *SketchEnvelope) GetKll() *kll.KLLState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Kll); ok {
			return x.Kll
		}
	}
	return nil
}

func (x *SketchEnvelope) GetDdsketch() *ddsketch.DDSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Ddsketch); ok {
			return x.Ddsketch
		}
	}
	return nil
}

func (x *SketchEnvelope) GetUnivmon() *univmon.UnivMonState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Univmon); ok {
			return x.Univmon
		}
	}
	return nil
}

func (x *SketchEnvelope) GetHydra() *hydra.HydraState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Hydra); ok {
			return x.Hydra
		}
	}
	return nil
}

func (x *SketchEnvelope) GetCoco() *cocosketch.CocoSketchState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Coco); ok {
			return x.Coco
		}
	}
	return nil
}

func (x *SketchEnvelope) GetElastic() *elasticsketch.ElasticState {
	if x != nil {
		if x, ok := x.SketchState.(*SketchEnvelope_Elastic); ok {
			return x.Elastic
		}
	}
	return nil
}

func (x *SketchEnvelope) GetSampleP() float64 {
	if x != nil {
		return x.SampleP
	}
	return 0
}

type isSketchEnvelope_SketchState interface {
	isSketchEnvelope_SketchState()
}

type SketchEnvelope_CountMin struct {
	CountMin *countminsketch.CountMinState `protobuf:"bytes,10,opt,name=count_min,json=countMin,proto3,oneof"`
}

type SketchEnvelope_CountSketch struct {
	CountSketch *countsketch.CountSketchState `protobuf:"bytes,11,opt,name=count_sketch,json=countSketch,proto3,oneof"`
}

type SketchEnvelope_Hll struct {
	Hll *hll.HyperLogLogState `protobuf:"bytes,12,opt,name=hll,proto3,oneof"`
}

type SketchEnvelope_Kll struct {
	Kll *kll.KLLState `protobuf:"bytes,13,opt,name=kll,proto3,oneof"`
}

type SketchEnvelope_Ddsketch struct {
	Ddsketch *ddsketch.DDSketchState `protobuf:"bytes,14,opt,name=ddsketch,proto3,oneof"`
}

type SketchEnvelope_Univmon struct {
	Univmon *univmon.UnivMonState `protobuf:"bytes,15,opt,name=univmon,proto3,oneof"`
}

type SketchEnvelope_Hydra struct {
	Hydra *hydra.HydraState `protobuf:"bytes,16,opt,name=hydra,proto3,oneof"`
}

type SketchEnvelope_Coco struct {
	Coco *cocosketch.CocoSketchState `protobuf:"bytes,17,opt,name=coco,proto3,oneof"`
}

type SketchEnvelope_Elastic struct {
	Elastic *elasticsketch.ElasticState `protobuf:"bytes,18,opt,name=elastic,proto3,oneof"`
}

func (*SketchEnvelope_CountMin) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_CountSketch) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hll) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Kll) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Ddsketch) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Univmon) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Hydra) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Coco) isSketchEnvelope_SketchState() {}

func (*SketchEnvelope_Elastic) isSketchEnvelope_SketchState() {}

// SketchDeltaEnvelope is the top-level wire container for delta payloads.
type SketchDeltaEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies which partition this delta belongs to.
	PartitionKey string `protobuf:"bytes,1,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// Unix milliseconds of the current window start. 0 when no window (Mode 1).
	WindowStartMs int64 `protobuf:"varint,2,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	// When true, the receiver should finalize and reset its accumulator for
	// this (partition_key, window_start_ms) after applying this delta.
	IsWindowClose bool `protobuf:"varint,3,opt,name=is_window_close,json=isWindowClose,proto3" json:"is_window_close,omitempty"`
	// Types that are valid to be assigned to Delta:
	//
	//	*SketchDeltaEnvelope_CountMin
	//	*SketchDeltaEnvelope_CountSketch
	//	*SketchDeltaEnvelope_Hll
	//	*SketchDeltaEnvelope_Ddsketch
	Delta         isSketchDeltaEnvelope_Delta `protobuf_oneof:"delta"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchDeltaEnvelope) Reset() {
	*x = SketchDeltaEnvelope{}
	mi := &file_sketchlib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchDeltaEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchDeltaEnvelope) ProtoMessage() {}

func (x *SketchDeltaEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sketchlib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchDeltaEnvelope.ProtoReflect.Descriptor instead.
func (*SketchDeltaEnvelope) Descriptor() ([]byte, []int) {
	return file_sketchlib_proto_rawDescGZIP(), []int{1}
}

func (x *SketchDeltaEnvelope) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *SketchDeltaEnvelope) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *SketchDeltaEnvelope) GetIsWindowClose() bool {
	if x != nil {
		return x.IsWindowClose
	}
	return false
}

func (x *SketchDeltaEnvelope) GetDelta() isSketchDeltaEnvelope_Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *SketchDeltaEnvelope) GetCountMin() *countminsketch.CountMinDelta {
	if x != nil {
		if x, ok := x.Delta.(*SketchDeltaEnvelope_CountMin); ok {
			return x.CountMin
		}
	}
	return nil
}

func (x *SketchDeltaEnvelope) GetCountSketch() *countsketch.CountSketchDelta {
	if x != nil {
		if x, ok := x.Delta.(*SketchDeltaEnvelope_CountSketch); ok {
			return x.CountSketch
		}
	}
	return nil
}

func (x *SketchDeltaEnvelope) GetHll() *hll.HLLDelta {
	if x != nil {
		if x, ok := x.Delta.(*SketchDeltaEnvelope_Hll); ok {
			return x.Hll
		}
	}
	return nil
}

func (x *SketchDeltaEnvelope) GetDdsketch() *ddsketch.DDSketchDelta {
	if x != nil {
		if x, ok := x.Delta.(*SketchDeltaEnvelope_Ddsketch); ok {
			return x.Ddsketch
		}
	}
	return nil
}

type isSketchDeltaEnvelope_Delta interface {
	isSketchDeltaEnvelope_Delta()
}

type SketchDeltaEnvelope_CountMin struct {
	CountMin *countminsketch.CountMinDelta `protobuf:"bytes,10,opt,name=count_min,json=countMin,proto3,oneof"`
}

type SketchDeltaEnvelope_CountSketch struct {
	CountSketch *countsketch.CountSketchDelta `protobuf:"bytes,11,opt,name=count_sketch,json=countSketch,proto3,oneof"`
}

type SketchDeltaEnvelope_Hll struct {
	Hll *hll.HLLDelta `protobuf:"bytes,12,opt,name=hll,proto3,oneof"`
}

type SketchDeltaEnvelope_Ddsketch struct {
	Ddsketch *ddsketch.DDSketchDelta `protobuf:"bytes,13,opt,name=ddsketch,proto3,oneof"`
}

func (*SketchDeltaEnvelope_CountMin) isSketchDeltaEnvelope_Delta() {}

func (*SketchDeltaEnvelope_CountSketch) isSketchDeltaEnvelope_Delta() {}

func (*SketchDeltaEnvelope_Hll) isSketchDeltaEnvelope_Delta() {}

func (*SketchDeltaEnvelope_Ddsketch) isSketchDeltaEnvelope_Delta() {}

var File_sketchlib_proto protoreflect.FileDescriptor

const file_sketchlib_proto_rawDesc = "" +
	"\n" +
	"\x0fsketchlib.proto\x12\fsketchlib.v1\x1a\x13common/common.proto\x1a#countminsketch/countminsketch.proto\x1a\x1dcountsketch/countsketch.proto\x1a\rhll/hll.proto\x1a\rkll/kll.proto\x1a\x17ddsketch/ddsketch.proto\x1a\x15univmon/univmon.proto\x1a\x11hydra/hydra.proto\x1a\x1bcocosketch/cocosketch.proto\x1a!elasticsketch/elasticsketch.proto\"\xc8\x05\n" +
	"\x0eSketchEnvelope\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x126\n" +
	"\bproducer\x18\x02 \x01(\v2\x1a.sketchlib.v1.ProducerInfoR\bproducer\x123\n" +
	"\thash_spec\x18\x03 \x01(\v2\x16.sketchlib.v1.HashSpecR\bhashSpec\x12:\n" +
	"\tcount_min\x18\n" +
	" \x01(\v2\x1b.sketchlib.v1.CountMinStateH\x00R\bcountMin\x12C\n" +
	"\fcount_sketch\x18\v \x01(\v2\x1e.sketchlib.v1.CountSketchStateH\x00R\vcountSketch\x122\n" +
	"\x03hll\x18\f \x01(\v2\x1e.sketchlib.v1.HyperLogLogStateH\x00R\x03hll\x12*\n" +
	"\x03kll\x18\r \x01(\v2\x16.sketchlib.v1.KLLStateH\x00R\x03kll\x129\n" +
	"\bddsketch\x18\x0e \x01(\v2\x1b.sketchlib.v1.DDSketchStateH\x00R\bddsketch\x126\n" +
	"\aunivmon\x18\x0f \x01(\v2\x1a.sketchlib.v1.UnivMonStateH\x00R\aunivmon\x120\n" +
	"\x05hydra\x18\x10 \x01(\v2\x18.sketchlib.v1.HydraStateH\x00R\x05hydra\x123\n" +
	"\x04coco\x18\x11 \x01(\v2\x1d.sketchlib.v1.CocoSketchStateH\x00R\x04coco\x126\n" +
	"\aelastic\x18\x12 \x01(\v2\x1a.sketchlib.v1.ElasticStateH\x00R\aelastic\x12\x19\n" +
	"\bsample_p\x18\x04 \x01(\x01R\asamplePB\x0e\n" +
	"\fsketch_stateJ\x04\b\x13\x10 \"\xfb\x02\n" +
	"\x13SketchDeltaEnvelope\x12#\n" +
	"\rpartition_key\x18\x01 \x01(\tR\fpartitionKey\x12&\n" +
	"\x0fwindow_start_ms\x18\x02 \x01(\x03R\rwindowStartMs\x12&\n" +
	"\x0fis_window_close\x18\x03 \x01(\bR\risWindowClose\x12:\n" +
	"\tcount_min\x18\n" +
	" \x01(\v2\x1b.sketchlib.v1.CountMinDeltaH\x00R\bcountMin\x12C\n" +
	"\fcount_sketch\x18\v \x01(\v2\x1e.sketchlib.v1.CountSketchDeltaH\x00R\vcountSketch\x12*\n" +
	"\x03hll\x18\f \x01(\v2\x16.sketchlib.v1.HLLDeltaH\x00R\x03hll\x129\n" +
	"\bddsketch\x18\r \x01(\v2\x1b.sketchlib.v1.DDSketchDeltaH\x00R\bddsketchB\a\n" +
	"\x05deltaBMZKgithub.com/ProjectASAP/sketchlib-go/proto/sketch_envelope;sketch_envelopepbb\x06proto3"

var (
	file_sketchlib_proto_rawDescOnce sync.Once
	file_sketchlib_proto_rawDescData []byte
)

func file_sketchlib_proto_rawDescGZIP() []byte {
	file_sketchlib_proto_rawDescOnce.Do(func() {
		file_sketchlib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)))
	})
	return file_sketchlib_proto_rawDescData
}

var file_sketchlib_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sketchlib_proto_goTypes = []any{
	(*SketchEnvelope)(nil),               // 0: sketchlib.v1.SketchEnvelope
	(*SketchDeltaEnvelope)(nil),          // 1: sketchlib.v1.SketchDeltaEnvelope
	(*common.ProducerInfo)(nil),          // 2: sketchlib.v1.ProducerInfo
	(*common.HashSpec)(nil),              // 3: sketchlib.v1.HashSpec
	(*countminsketch.CountMinState)(nil), // 4: sketchlib.v1.CountMinState
	(*countsketch.CountSketchState)(nil), // 5: sketchlib.v1.CountSketchState
	(*hll.HyperLogLogState)(nil),         // 6: sketchlib.v1.HyperLogLogState
	(*kll.KLLState)(nil),                 // 7: sketchlib.v1.KLLState
	(*ddsketch.DDSketchState)(nil),       // 8: sketchlib.v1.DDSketchState
	(*univmon.UnivMonState)(nil),         // 9: sketchlib.v1.UnivMonState
	(*hydra.HydraState)(nil),             // 10: sketchlib.v1.HydraState
	(*cocosketch.CocoSketchState)(nil),   // 11: sketchlib.v1.CocoSketchState
	(*elasticsketch.ElasticState)(nil),   // 12: sketchlib.v1.ElasticState
	(*countminsketch.CountMinDelta)(nil), // 13: sketchlib.v1.CountMinDelta
	(*countsketch.CountSketchDelta)(nil), // 14: sketchlib.v1.CountSketchDelta
	(*hll.HLLDelta)(nil),                 // 15: sketchlib.v1.HLLDelta
	(*ddsketch.DDSketchDelta)(nil),       // 16: sketchlib.v1.DDSketchDelta
}
var file_sketchlib_proto_depIdxs = []int32{
	2,  // 0: sketchlib.v1.SketchEnvelope.producer:type_name -> sketchlib.v1.ProducerInfo
	3,  // 1: sketchlib.v1.SketchEnvelope.hash_spec:type_name -> sketchlib.v1.HashSpec
	4,  // 2: sketchlib.v1.SketchEnvelope.count_min:type_name -> sketchlib.v1.CountMinState
	5,  // 3: sketchlib.v1.SketchEnvelope.count_sketch:type_name -> sketchlib.v1.CountSketchState
	6,  // 4: sketchlib.v1.SketchEnvelope.hll:type_name -> sketchlib.v1.HyperLogLogState
	7,  // 5: sketchlib.v1.SketchEnvelope.kll:type_name -> sketchlib.v1.KLLState
	8,  // 6: sketchlib.v1.SketchEnvelope.ddsketch:type_name -> sketchlib.v1.DDSketchState
	9,  // 7: sketchlib.v1.SketchEnvelope.univmon:type_name -> sketchlib.v1.UnivMonState
	10, // 8: sketchlib.v1.SketchEnvelope.hydra:type_name -> sketchlib.v1.HydraState
	11, // 9: sketchlib.v1.SketchEnvelope.coco:type_name -> sketchlib.v1.CocoSketchState
	12, // 10: sketchlib.v1.SketchEnvelope.elastic:type_name -> sketchlib.v1.ElasticState
	13, // 11: sketchlib.v1.SketchDeltaEnvelope.count_min:type_name -> sketchlib.v1.CountMinDelta
	14, // 12: sketchlib.v1.SketchDeltaEnvelope.count_sketch:type_name -> sketchlib.v1.CountSketchDelta
	15, // 13: sketchlib.v1.SketchDeltaEnvelope.hll:type_name -> sketchlib.v1.HLLDelta
	16, // 14: sketchlib.v1.SketchDeltaEnvelope.ddsketch:type_name -> sketchlib.v1.DDSketchDelta
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sketchlib_proto_init() }
func file_sketchlib_proto_init() {
	if File_sketchlib_proto != nil {
		return
	}
	file_sketchlib_proto_msgTypes[0].OneofWrappers = []any{
		(*SketchEnvelope_CountMin)(nil),
		(*SketchEnvelope_CountSketch)(nil),
		(*SketchEnvelope_Hll)(nil),
		(*SketchEnvelope_Kll)(nil),
		(*SketchEnvelope_Ddsketch)(nil),
		(*SketchEnvelope_Univmon)(nil),
		(*SketchEnvelope_Hydra)(nil),
		(*SketchEnvelope_Coco)(nil),
		(*SketchEnvelope_Elastic)(nil),
	}
	file_sketchlib_proto_msgTypes[1].OneofWrappers = []any{
		(*SketchDeltaEnvelope_CountMin)(nil),
		(*SketchDeltaEnvelope_CountSketch)(nil),
		(*SketchDeltaEnvelope_Hll)(nil),
		(*SketchDeltaEnvelope_Ddsketch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sketchlib_proto_rawDesc), len(file_sketchlib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sketchlib_proto_goTypes,
		DependencyIndexes: file_sketchlib_proto_depIdxs,
		MessageInfos:      file_sketchlib_proto_msgTypes,
	}.Build()
	File_sketchlib_proto = out.File
	file_sketchlib_proto_goTypes = nil
	file_sketchlib_proto_depIdxs = nil
}
