// common.proto — Shared types used across all sketch-specific proto files.
//
// Contains: ProducerInfo, HashSpec, HashAlgorithm, SeedDerivation, CounterType.
// These are referenced by the per-sketch protos and the top-level envelope.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HashAlgorithm enumerates supported hash algorithms.
// Only XXH3_64 is cross-language stable for the current implementation.
type HashAlgorithm int32

const (
	HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED HashAlgorithm = 0
	// xxHash3 64-bit with seed (zeebo/xxh3 in Go; twox-hash XxHash3_64 in Rust).
	// This is the standard algorithm for both libraries.
	HashAlgorithm_HASH_ALGORITHM_XXH3_64 HashAlgorithm = 1
	// xxHash3 128-bit with seed. Used for HLL register indexing and packed matrix
	// hashes that exceed 64 bits.
	HashAlgorithm_HASH_ALGORITHM_XXH3_128 HashAlgorithm = 2
	// xxHash 64-bit (non-XXH3). Reserved for legacy data; not produced by either
	// current library.
	HashAlgorithm_HASH_ALGORITHM_XXHASH64 HashAlgorithm = 3
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0: "HASH_ALGORITHM_UNSPECIFIED",
		1: "HASH_ALGORITHM_XXH3_64",
		2: "HASH_ALGORITHM_XXH3_128",
		3: "HASH_ALGORITHM_XXHASH64",
	}
	HashAlgorithm_value = map[string]int32{
		"HASH_ALGORITHM_UNSPECIFIED": 0,
		"HASH_ALGORITHM_XXH3_64":     1,
		"HASH_ALGORITHM_XXH3_128":    2,
		"HASH_ALGORITHM_XXHASH64":    3,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

// SeedDerivation describes how per-row seed indices are produced.
type SeedDerivation int32

const (
	SeedDerivation_SEED_DERIVATION_UNSPECIFIED SeedDerivation = 0
	// Each row r uses seed_list[(base + r) % len(seed_list)].
	// Standard derivation for multi-row sketches (CountMin, CountSketch).
	SeedDerivation_SEED_DERIVATION_ADDITIVE_OFFSET SeedDerivation = 1
	// All rows share a single hash (Packed64 or Packed128 fast-path).
	// Applicable only when the total bit-width fits in 64 or 128 bits.
	SeedDerivation_SEED_DERIVATION_PACKED SeedDerivation = 2
)

// Enum value maps for SeedDerivation.
var (
	SeedDerivation_name = map[int32]string{
		0: "SEED_DERIVATION_UNSPECIFIED",
		1: "SEED_DERIVATION_ADDITIVE_OFFSET",
		2: "SEED_DERIVATION_PACKED",
	}
	SeedDerivation_value = map[string]int32{
		"SEED_DERIVATION_UNSPECIFIED":     0,
		"SEED_DERIVATION_ADDITIVE_OFFSET": 1,
		"SEED_DERIVATION_PACKED":          2,
	}
)

func (x SeedDerivation) Enum() *SeedDerivation {
	p := new(SeedDerivation)
	*p = x
	return p
}

func (x SeedDerivation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeedDerivation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (SeedDerivation) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x SeedDerivation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeedDerivation.Descriptor instead.
func (SeedDerivation) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

// CounterType identifies the numeric type used to store matrix counters.
// Go defaults to FLOAT64; Rust defaults to INT32.
// Determines which counts_* array is populated in CountMinState and
// CountSketchState.
type CounterType int32

const (
	CounterType_COUNTER_TYPE_UNSPECIFIED CounterType = 0
	CounterType_COUNTER_TYPE_INT32       CounterType = 1 // Rust default for CountMin / CountSketch.
	CounterType_COUNTER_TYPE_INT64       CounterType = 2
	// INT128 is stored as pairs of int64 (hi, lo) interleaved in counts_int.
	CounterType_COUNTER_TYPE_INT128  CounterType = 3
	CounterType_COUNTER_TYPE_FLOAT64 CounterType = 4 // Go default for CountMin / CountSketch.
)

// Enum value maps for CounterType.
var (
	CounterType_name = map[int32]string{
		0: "COUNTER_TYPE_UNSPECIFIED",
		1: "COUNTER_TYPE_INT32",
		2: "COUNTER_TYPE_INT64",
		3: "COUNTER_TYPE_INT128",
		4: "COUNTER_TYPE_FLOAT64",
	}
	CounterType_value = map[string]int32{
		"COUNTER_TYPE_UNSPECIFIED": 0,
		"COUNTER_TYPE_INT32":       1,
		"COUNTER_TYPE_INT64":       2,
		"COUNTER_TYPE_INT128":      3,
		"COUNTER_TYPE_FLOAT64":     4,
	}
)

func (x CounterType) Enum() *CounterType {
	p := new(CounterType)
	*p = x
	return p
}

func (x CounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[2].Descriptor()
}

func (CounterType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[2]
}

func (x CounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CounterType.Descriptor instead.
func (CounterType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

// ProducerInfo records which library version created this envelope.
type ProducerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of "sketchlib-go" or "sketchlib-rust".
	Library string `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	// Semantic version string of the producing library, e.g. "0.1.0".
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerInfo) Reset() {
	*x = ProducerInfo{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerInfo) ProtoMessage() {}

func (x *ProducerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerInfo.ProtoReflect.Descriptor instead.
func (*ProducerInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *ProducerInfo) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *ProducerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// HashSpec fully describes the hashing configuration so both sides can confirm
// they will compute identical bucket indices.
//
// Both libraries share:
//
//	canonical_seed_index = 5  (CanonicalHashSeed / CANONICAL_HASH_SEED)
//	seed_list            = the 20-entry table in hash.go / hash.rs
//	seed_derivation      = ADDITIVE_OFFSET for per-row seeds
type HashSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash algorithm used for all sketch operations.
	Algorithm HashAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=sketchlib.v1.HashAlgorithm" json:"algorithm,omitempty"`
	// Index into seed_list used as the primary (canonical) hash seed.
	// Both libraries default to 5.
	CanonicalSeedIndex uint32 `protobuf:"varint,2,opt,name=canonical_seed_index,json=canonicalSeedIndex,proto3" json:"canonical_seed_index,omitempty"`
	// Complete seed table. Must be identical on both sides for correct results.
	// Both libraries currently use exactly 20 seeds; producers always emit all 20.
	SeedList []uint64 `protobuf:"varint,3,rep,packed,name=seed_list,json=seedList,proto3" json:"seed_list,omitempty"`
	// How per-row seeds are derived from the base seed index.
	SeedDerivation SeedDerivation `protobuf:"varint,4,opt,name=seed_derivation,json=seedDerivation,proto3,enum=sketchlib.v1.SeedDerivation" json:"seed_derivation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HashSpec) Reset() {
	*x = HashSpec{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashSpec) ProtoMessage() {}

func (x *HashSpec) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashSpec.ProtoReflect.Descriptor instead.
func (*HashSpec) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *HashSpec) GetAlgorithm() HashAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
}

func (x *HashSpec) GetCanonicalSeedIndex() uint32 {
	if x != nil {
		return x.CanonicalSeedIndex
	}
	return 0
}

func (x *HashSpec) GetSeedList() []uint64 {
	if x != nil {
		return x.SeedList
	}
	return nil
}

func (x *HashSpec) GetSeedDerivation() SeedDerivation {
	if x != nil {
		return x.SeedDerivation
	}
	return SeedDerivation_SEED_DERIVATION_UNSPECIFIED
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\fsketchlib.v1\"B\n" +
	"\fProducerInfo\x12\x18\n" +
	"\alibrary\x18\x01 \x01(\tR\alibrary\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xdf\x01\n" +
	"\bHashSpec\x129\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1b.sketchlib.v1.HashAlgorithmR\talgorithm\x120\n" +
	"\x14canonical_seed_index\x18\x02 \x01(\rR\x12canonicalSeedIndex\x12\x1f\n" +
	"\tseed_list\x18\x03 \x03(\x04B\x02\x10\x01R\bseedList\x12E\n" +
	"\x0fseed_derivation\x18\x04 \x01(\x0e2\x1c.sketchlib.v1.SeedDerivationR\x0eseedDerivation*\x85\x01\n" +
	"\rHashAlgorithm\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HASH_ALGORITHM_XXH3_64\x10\x01\x12\x1b\n" +
	"\x17HASH_ALGORITHM_XXH3_128\x10\x02\x12\x1b\n" +
	"\x17HASH_ALGORITHM_XXHASH64\x10\x03*r\n" +
	"\x0eSeedDerivation\x12\x1f\n" +
	"\x1bSEED_DERIVATION_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSEED_DERIVATION_ADDITIVE_OFFSET\x10\x01\x12\x1a\n" +
	"\x16SEED_DERIVATION_PACKED\x10\x02*\x8e\x01\n" +
	"\vCounterType\x12\x1c\n" +
	"\x18COUNTER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COUNTER_TYPE_INT32\x10\x01\x12\x16\n" +
	"\x12COUNTER_TYPE_INT64\x10\x02\x12\x17\n" +
	"\x13COUNTER_TYPE_INT128\x10\x03\x12\x18\n" +
	"\x14COUNTER_TYPE_FLOAT64\x10\x04B;Z9github.com/ProjectASAP/sketchlib-go/proto/common;commonpbb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_common_proto_goTypes = []any{
	(HashAlgorithm)(0),   // 0: sketchlib.v1.HashAlgorithm
	(SeedDerivation)(0),  // 1: sketchlib.v1.SeedDerivation
	(CounterType)(0),     // 2: sketchlib.v1.CounterType
	(*ProducerInfo)(nil), // 3: sketchlib.v1.ProducerInfo
	(*HashSpec)(nil),     // 4: sketchlib.v1.HashSpec
}
var file_common_common_proto_depIdxs = []int32{
	0, // 0: sketchlib.v1.HashSpec.algorithm:type_name -> sketchlib.v1.HashAlgorithm
	1, // 1: sketchlib.v1.HashSpec.seed_derivation:type_name -> sketchlib.v1.SeedDerivation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
