package asapmsgpack

import (
	"encoding/hex"
	"reflect"
	"testing"
)

// Golden fixtures pinned to the ASAPQuery-backend Rust side's
// `sketch_core::<type>::serialize_msgpack` output. Generated by a
// throw-away print test over the matching Rust types with the same
// input values. If the Rust wire format ever shifts (field reorder,
// enum representation change, etc.), these tests fail immediately —
// that is the entire point of pinning the bytes.
//
// To regenerate: add a tests/ file in the Rust sketch-core crate that
// calls `serialize_msgpack` on the corresponding struct literal and
// prints `hex::encode(&bytes)`. See the commit message of this PR for
// the exact snippet that produced these fixtures.

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex decode %q: %v", s, err)
	}
	return b
}

// ─── CountSketch ─────────────────────────────────────────────────────

func TestCountSketchMatchesRustGolden(t *testing.T) {
	// Rust:
	//   CountSketch::from_legacy_matrix(
	//     vec![vec![1.0, -2.0], vec![3.0, -4.0]], 2, 2
	//   ).serialize_msgpack()
	golden := mustHex(t,
		"9302029292cb3ff0000000000000cbc00000000000000092cb4008000000000000cbc010000000000000")

	got, err := MarshalCountSketch(2, 2, [][]float64{
		{1.0, -2.0},
		{3.0, -4.0},
	})
	if err != nil {
		t.Fatalf("MarshalCountSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"CountSketch wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	rows, cols, matrix, err := UnmarshalCountSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalCountSketch: %v", err)
	}
	if rows != 2 || cols != 2 {
		t.Errorf("dims: got %dx%d, want 2x2", rows, cols)
	}
	want := [][]float64{{1.0, -2.0}, {3.0, -4.0}}
	if !reflect.DeepEqual(matrix, want) {
		t.Errorf("matrix mismatch: got %v, want %v", matrix, want)
	}
}

func TestCountSketchRejectsRaggedMatrix(t *testing.T) {
	_, err := MarshalCountSketch(2, 3, [][]float64{{1, 2, 3}, {4, 5}})
	if err == nil {
		t.Fatal("expected error for ragged matrix, got nil")
	}
}

// ─── DDSketch ────────────────────────────────────────────────────────

func TestDDSketchMatchesRustGolden(t *testing.T) {
	// DataPoint-level metric scalars (count/sum/min/max) are no longer
	// carried on the wire. The payload is now a 3-element array:
	//   [ alpha, store_counts, store_offset ]
	//
	// Rust:
	//   DdSketch::from_raw(0.01, vec![1, 2, 3], -2).serialize_msgpack()
	golden := mustHex(t,
		"93cb3f847ae147ae147b93010203fe")

	state := DDSketchState{
		Alpha:       0.01,
		StoreCounts: []uint64{1, 2, 3},
		StoreOffset: -2,
	}
	got, err := MarshalDDSketch(state)
	if err != nil {
		t.Fatalf("MarshalDDSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"DDSketch wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	decoded, err := UnmarshalDDSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalDDSketch: %v", err)
	}
	if !reflect.DeepEqual(decoded, state) {
		t.Errorf("round-trip mismatch\n  got  %+v\n  want %+v",
			decoded, state)
	}
}

// ─── HLLSketch ───────────────────────────────────────────────────────

// NOTE: the pre-alignment HLL golden fixtures pinned the OLD payload-only
// format (a 6-element array [variant, precision, registers-as-u8-array, hip×3]
// with no envelope). That format is gone: the ASAPv1-aligned MarshalHLLSketch
// now emits a full envelope with the variant in the kind_id, the precision in
// the metadata, and registers as msgpack `bin`. Byte-level parity for the new
// format is pinned by TestHLLClassicP12Bytes (wrapper_test.go); these tests are
// now round-trips. Cross-language golden vectors are a follow-up (see PR body).
func TestHLLSketchRegularRoundTrip(t *testing.T) {
	state := HLLSketchState{
		Variant:   HLLVariantRegular,
		Precision: 2,
		Registers: []byte{1, 2, 3, 4},
	}
	got, err := MarshalHLLSketch(state)
	if err != nil {
		t.Fatalf("MarshalHLLSketch: %v", err)
	}
	// kind_id carries the variant: Regular -> Classic (0x01 0x01).
	if !reflect.DeepEqual(got[8:10], []byte{0x01, 0x01}) {
		t.Fatalf("kind_id: got %x, want 0101", got[8:10])
	}
	decoded, err := UnmarshalHLLSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalHLLSketch: %v", err)
	}
	if !reflect.DeepEqual(decoded, state) {
		t.Errorf("round-trip mismatch\n  got  %+v\n  want %+v", decoded, state)
	}
}

func TestHLLSketchHipRoundTrip(t *testing.T) {
	state := HLLSketchState{
		Variant:   HLLVariantHip,
		Precision: 2,
		Registers: []byte{0, 0, 0, 0},
		HipKxq0:   1.5,
		HipKxq1:   2.5,
		HipEst:    42.0,
	}
	got, err := MarshalHLLSketch(state)
	if err != nil {
		t.Fatalf("MarshalHLLSketch: %v", err)
	}
	// kind_id carries the variant: Hip -> 0x01 0x03.
	if !reflect.DeepEqual(got[8:10], []byte{0x01, 0x03}) {
		t.Fatalf("kind_id: got %x, want 0103", got[8:10])
	}
	decoded, err := UnmarshalHLLSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalHLLSketch: %v", err)
	}
	if !reflect.DeepEqual(decoded, state) {
		t.Errorf("round-trip mismatch\n  got  %+v\n  want %+v", decoded, state)
	}
}

func TestHLLSketchRejectsWrongRegisterCount(t *testing.T) {
	_, err := MarshalHLLSketch(HLLSketchState{
		Variant:   HLLVariantRegular,
		Precision: 3, // expects 8 registers
		Registers: []byte{1, 2, 3, 4},
	})
	if err == nil {
		t.Fatal("expected error for wrong register count, got nil")
	}
}

// ─── CountMinSketch ──────────────────────────────────────────────────

// NOTE: the pre-alignment Count-Min golden pinned the OLD payload-only format
// ([ matrix:[][]f64, row_num, col_num ], no envelope). The ASAPv1-aligned
// MarshalCountMinSketch now emits a full envelope (kind_id 0x02 0x00,
// counter_type/mode in the metadata) with the payload [ rows, cols, counts ]
// where counts is a flat row-major array. This is now a structural + round-trip
// test; cross-language golden vectors are a follow-up (see PR body).
func TestCountMinSketchNewFormatRoundTrip(t *testing.T) {
	matrix := [][]float64{
		{0, 0, 0},
		{0, 0, 0},
	}
	got, err := MarshalCountMinSketch(2, 3, matrix)
	if err != nil {
		t.Fatalf("MarshalCountMinSketch: %v", err)
	}
	// kind_id must be the single Count-Min id 0x02 0x00.
	if !reflect.DeepEqual(got[8:10], []byte{0x02, 0x00}) {
		t.Fatalf("kind_id: got %x, want 0200", got[8:10])
	}
	// Metadata must carry counter_type=f64 and mode=fast.
	_, meta, payload, err := SplitWrapper(got)
	if err != nil {
		t.Fatalf("SplitWrapper: %v", err)
	}
	counterType, mode, err := decodeCMSMetadata(meta)
	if err != nil {
		t.Fatalf("decodeCMSMetadata: %v", err)
	}
	if counterType != CMSCounterF64 || mode != CMSModeFast {
		t.Fatalf("metadata: got %q/%q, want f64/fast", counterType, mode)
	}
	// Payload is a positional array [rows, cols, counts]; header 0x93.
	if payload[0] != 0x93 {
		t.Fatalf("payload header: 0x%02x, want 0x93 (array3)", payload[0])
	}

	gotMatrix, rowNum, colNum, err := UnmarshalCountMinSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalCountMinSketch: %v", err)
	}
	if rowNum != 2 || colNum != 3 {
		t.Errorf("dims: got %dx%d, want 2x3", rowNum, colNum)
	}
	if !reflect.DeepEqual(gotMatrix, matrix) {
		t.Errorf("matrix mismatch: got %v, want %v", gotMatrix, matrix)
	}
}

func TestCountMinSketchRoundTripWithValues(t *testing.T) {
	matrix := [][]float64{
		{1.5, -2.25, 3.125, 0},
		{-4.0625, 5.03125, -6.015625, 7.0078125},
	}
	bytes, err := MarshalCountMinSketch(2, 4, matrix)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	gotMatrix, rows, cols, err := UnmarshalCountMinSketch(bytes)
	if err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if rows != 2 || cols != 4 {
		t.Errorf("dims: got %dx%d, want 2x4", rows, cols)
	}
	if !reflect.DeepEqual(gotMatrix, matrix) {
		t.Errorf("matrix mismatch: got %v, want %v", gotMatrix, matrix)
	}
}
