package asapmsgpack

import (
	"encoding/hex"
	"reflect"
	"testing"
)

// Golden fixtures pinned to the ASAPQuery-backend Rust side's
// `sketch_core::<type>::serialize_msgpack` output. Generated by a
// throw-away print test over the matching Rust types with the same
// input values. If the Rust wire format ever shifts (field reorder,
// enum representation change, etc.), these tests fail immediately —
// that is the entire point of pinning the bytes.
//
// To regenerate: add a tests/ file in the Rust sketch-core crate that
// calls `serialize_msgpack` on the corresponding struct literal and
// prints `hex::encode(&bytes)`. See the commit message of this PR for
// the exact snippet that produced these fixtures.

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex decode %q: %v", s, err)
	}
	return b
}

// ─── DDSketch ────────────────────────────────────────────────────────

func TestDDSketchMatchesRustGolden(t *testing.T) {
	// DataPoint-level metric scalars (count/sum/min/max) are no longer
	// carried on the wire. The payload is now a 3-element array:
	//   [ alpha, store_counts, store_offset ]
	//
	// Rust:
	//   DdSketch::from_raw(0.01, vec![1, 2, 3], -2).serialize_msgpack()
	golden := mustHex(t,
		"93cb3f847ae147ae147b93010203fe")

	state := DDSketchState{
		Alpha:       0.01,
		StoreCounts: []uint64{1, 2, 3},
		StoreOffset: -2,
	}
	got, err := MarshalDDSketch(state)
	if err != nil {
		t.Fatalf("MarshalDDSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"DDSketch wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	decoded, err := UnmarshalDDSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalDDSketch: %v", err)
	}
	if !reflect.DeepEqual(decoded, state) {
		t.Errorf("round-trip mismatch\n  got  %+v\n  want %+v",
			decoded, state)
	}
}
