package asapmsgpack

import (
	"encoding/hex"
	"reflect"
	"testing"
)

// Golden fixtures pinned to the ASAPQuery-backend Rust side's
// `sketch_core::<type>::serialize_msgpack` output. Generated by a
// throw-away print test over the matching Rust types with the same
// input values. If the Rust wire format ever shifts (field reorder,
// enum representation change, etc.), these tests fail immediately —
// that is the entire point of pinning the bytes.
//
// To regenerate: add a tests/ file in the Rust sketch-core crate that
// calls `serialize_msgpack` on the corresponding struct literal and
// prints `hex::encode(&bytes)`. See the commit message of this PR for
// the exact snippet that produced these fixtures.

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex decode %q: %v", s, err)
	}
	return b
}

// ─── CountSketch ─────────────────────────────────────────────────────

func TestCountSketchMatchesRustGolden(t *testing.T) {
	// Rust:
	//   CountSketch::from_legacy_matrix(
	//     vec![vec![1.0, -2.0], vec![3.0, -4.0]], 2, 2
	//   ).serialize_msgpack()
	golden := mustHex(t,
		"9302029292cb3ff0000000000000cbc00000000000000092cb4008000000000000cbc010000000000000")

	got, err := MarshalCountSketch(2, 2, [][]float64{
		{1.0, -2.0},
		{3.0, -4.0},
	})
	if err != nil {
		t.Fatalf("MarshalCountSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"CountSketch wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	rows, cols, matrix, err := UnmarshalCountSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalCountSketch: %v", err)
	}
	if rows != 2 || cols != 2 {
		t.Errorf("dims: got %dx%d, want 2x2", rows, cols)
	}
	want := [][]float64{{1.0, -2.0}, {3.0, -4.0}}
	if !reflect.DeepEqual(matrix, want) {
		t.Errorf("matrix mismatch: got %v, want %v", matrix, want)
	}
}

func TestCountSketchRejectsRaggedMatrix(t *testing.T) {
	_, err := MarshalCountSketch(2, 3, [][]float64{{1, 2, 3}, {4, 5}})
	if err == nil {
		t.Fatal("expected error for ragged matrix, got nil")
	}
}

// ─── DDSketch ────────────────────────────────────────────────────────

func TestDDSketchMatchesRustGolden(t *testing.T) {
	// DataPoint-level metric scalars (count/sum/min/max) are no longer
	// carried on the wire. The payload is now a 3-element array:
	//   [ alpha, store_counts, store_offset ]
	//
	// Rust:
	//   DdSketch::from_raw(0.01, vec![1, 2, 3], -2).serialize_msgpack()
	golden := mustHex(t,
		"93cb3f847ae147ae147b93010203fe")

	state := DDSketchState{
		Alpha:       0.01,
		StoreCounts: []uint64{1, 2, 3},
		StoreOffset: -2,
	}
	got, err := MarshalDDSketch(state)
	if err != nil {
		t.Fatalf("MarshalDDSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"DDSketch wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	decoded, err := UnmarshalDDSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalDDSketch: %v", err)
	}
	if !reflect.DeepEqual(decoded, state) {
		t.Errorf("round-trip mismatch\n  got  %+v\n  want %+v",
			decoded, state)
	}
}

// ─── HLLSketch ───────────────────────────────────────────────────────

func TestHLLSketchRegularMatchesRustGolden(t *testing.T) {
	// Rust:
	//   HllSketch::from_raw(HllVariant::Regular, 2, vec![1, 2, 3, 4],
	//     0.0, 0.0, 0.0).serialize_msgpack()
	golden := mustHex(t,
		"96a7526567756c6172029401020304cb0000000000000000cb0000000000000000cb0000000000000000")

	state := HLLSketchState{
		Variant:   HLLVariantRegular,
		Precision: 2,
		Registers: []byte{1, 2, 3, 4},
	}
	got, err := MarshalHLLSketch(state)
	if err != nil {
		t.Fatalf("MarshalHLLSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"HLLSketch Regular wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	decoded, err := UnmarshalHLLSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalHLLSketch: %v", err)
	}
	if !reflect.DeepEqual(decoded, state) {
		t.Errorf("round-trip mismatch\n  got  %+v\n  want %+v",
			decoded, state)
	}
}

func TestHLLSketchHipMatchesRustGolden(t *testing.T) {
	// Rust:
	//   HllSketch::from_raw(HllVariant::Hip, 2, vec![0, 0, 0, 0],
	//     1.5, 2.5, 42.0).serialize_msgpack()
	golden := mustHex(t,
		"96a3486970029400000000cb3ff8000000000000cb4004000000000000cb4045000000000000")

	state := HLLSketchState{
		Variant:   HLLVariantHip,
		Precision: 2,
		Registers: []byte{0, 0, 0, 0},
		HipKxq0:   1.5,
		HipKxq1:   2.5,
		HipEst:    42.0,
	}
	got, err := MarshalHLLSketch(state)
	if err != nil {
		t.Fatalf("MarshalHLLSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"HLLSketch Hip wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}
}

func TestHLLSketchRejectsWrongRegisterCount(t *testing.T) {
	_, err := MarshalHLLSketch(HLLSketchState{
		Variant:   HLLVariantRegular,
		Precision: 3, // expects 8 registers
		Registers: []byte{1, 2, 3, 4},
	})
	if err == nil {
		t.Fatal("expected error for wrong register count, got nil")
	}
}

// ─── CountMinSketch ──────────────────────────────────────────────────

func TestCountMinSketchMatchesRustGolden(t *testing.T) {
	// Rust:
	//   let cms = CountMinSketch::new(2, 3);
	//   cms.serialize_msgpack()
	//
	// Empty 2x3 matrix (zeros). Note the field order differs from
	// CountSketch: matrix first, then row_num, then col_num.
	golden := mustHex(t,
		"939293cb0000000000000000cb0000000000000000cb000000000000000093cb0000000000000000cb0000000000000000cb00000000000000000203")

	matrix := [][]float64{
		{0, 0, 0},
		{0, 0, 0},
	}
	got, err := MarshalCountMinSketch(2, 3, matrix)
	if err != nil {
		t.Fatalf("MarshalCountMinSketch: %v", err)
	}
	if !reflect.DeepEqual(got, golden) {
		t.Fatalf(
			"CountMinSketch wire mismatch\n  got    %x\n  golden %x",
			got, golden)
	}

	gotMatrix, rowNum, colNum, err := UnmarshalCountMinSketch(got)
	if err != nil {
		t.Fatalf("UnmarshalCountMinSketch: %v", err)
	}
	if rowNum != 2 || colNum != 3 {
		t.Errorf("dims: got %dx%d, want 2x3", rowNum, colNum)
	}
	if !reflect.DeepEqual(gotMatrix, matrix) {
		t.Errorf("matrix mismatch: got %v, want %v", gotMatrix, matrix)
	}
}

func TestCountMinSketchRoundTripWithValues(t *testing.T) {
	matrix := [][]float64{
		{1.5, -2.25, 3.125, 0},
		{-4.0625, 5.03125, -6.015625, 7.0078125},
	}
	bytes, err := MarshalCountMinSketch(2, 4, matrix)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	gotMatrix, rows, cols, err := UnmarshalCountMinSketch(bytes)
	if err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if rows != 2 || cols != 4 {
		t.Errorf("dims: got %dx%d, want 2x4", rows, cols)
	}
	if !reflect.DeepEqual(gotMatrix, matrix) {
		t.Errorf("matrix mismatch: got %v, want %v", gotMatrix, matrix)
	}
}
