// hll.proto — Portable wire format for HyperLogLog sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hll/hll.proto

package hllpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HLLVariant identifies which HLL estimator algorithm the registers belong to.
type HLLVariant int32

const (
	HLLVariant_HLL_VARIANT_UNSPECIFIED HLLVariant = 0
	// Classic HLL with bias-correction tables (Flajolet et al. 2007).
	HLLVariant_HLL_VARIANT_REGULAR HLLVariant = 1
	// Otmar Ertl's improved estimator used by Apache DataFusion.
	// Not compatible with REGULAR registers.
	HLLVariant_HLL_VARIANT_DATAFUSION HLLVariant = 2
	// Kevin Lang's HyperLogLog++ Improved Proposal (HIP).
	// Requires hip_kxq0, hip_kxq1, hip_est to be populated.
	HLLVariant_HLL_VARIANT_HIP HLLVariant = 3
)

// Enum value maps for HLLVariant.
var (
	HLLVariant_name = map[int32]string{
		0: "HLL_VARIANT_UNSPECIFIED",
		1: "HLL_VARIANT_REGULAR",
		2: "HLL_VARIANT_DATAFUSION",
		3: "HLL_VARIANT_HIP",
	}
	HLLVariant_value = map[string]int32{
		"HLL_VARIANT_UNSPECIFIED": 0,
		"HLL_VARIANT_REGULAR":     1,
		"HLL_VARIANT_DATAFUSION":  2,
		"HLL_VARIANT_HIP":         3,
	}
)

func (x HLLVariant) Enum() *HLLVariant {
	p := new(HLLVariant)
	*p = x
	return p
}

func (x HLLVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HLLVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_hll_hll_proto_enumTypes[0].Descriptor()
}

func (HLLVariant) Type() protoreflect.EnumType {
	return &file_hll_hll_proto_enumTypes[0]
}

func (x HLLVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HLLVariant.Descriptor instead.
func (HLLVariant) EnumDescriptor() ([]byte, []int) {
	return file_hll_hll_proto_rawDescGZIP(), []int{0}
}

// HyperLogLogState is the portable state of a HyperLogLog cardinality sketch.
//
// Precision p determines the register count: num_registers = 2^precision.
// Both libraries default to precision = 14 (16 384 registers).
//
// The variant field is required because the three estimator algorithms are
// not interchangeable: loading a DataFusion state into a Regular estimator
// (or vice versa) produces incorrect cardinality estimates.
type HyperLogLogState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HLL estimator variant. Required.
	Variant HLLVariant `protobuf:"varint,1,opt,name=variant,proto3,enum=sketchlib.v1.HLLVariant" json:"variant,omitempty"`
	// Log₂ of the number of registers (precision parameter p).
	// Default = 14 → 16 384 registers.
	Precision uint32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// Raw register values, length = 2^precision.
	// Each byte stores the maximum (leading-zeros + 1) seen for that bucket.
	// Stored as a raw byte string for compact encoding (1 byte per register).
	Registers []byte `protobuf:"bytes,3,opt,name=registers,proto3" json:"registers,omitempty"`
	// HIP accumulator component kxq0.
	HipKxq0 float64 `protobuf:"fixed64,4,opt,name=hip_kxq0,json=hipKxq0,proto3" json:"hip_kxq0,omitempty"`
	// HIP accumulator component kxq1.
	HipKxq1 float64 `protobuf:"fixed64,5,opt,name=hip_kxq1,json=hipKxq1,proto3" json:"hip_kxq1,omitempty"`
	// HIP running cardinality estimate.
	HipEst        float64 `protobuf:"fixed64,6,opt,name=hip_est,json=hipEst,proto3" json:"hip_est,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HyperLogLogState) Reset() {
	*x = HyperLogLogState{}
	mi := &file_hll_hll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HyperLogLogState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperLogLogState) ProtoMessage() {}

func (x *HyperLogLogState) ProtoReflect() protoreflect.Message {
	mi := &file_hll_hll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperLogLogState.ProtoReflect.Descriptor instead.
func (*HyperLogLogState) Descriptor() ([]byte, []int) {
	return file_hll_hll_proto_rawDescGZIP(), []int{0}
}

func (x *HyperLogLogState) GetVariant() HLLVariant {
	if x != nil {
		return x.Variant
	}
	return HLLVariant_HLL_VARIANT_UNSPECIFIED
}

func (x *HyperLogLogState) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *HyperLogLogState) GetRegisters() []byte {
	if x != nil {
		return x.Registers
	}
	return nil
}

func (x *HyperLogLogState) GetHipKxq0() float64 {
	if x != nil {
		return x.HipKxq0
	}
	return 0
}

func (x *HyperLogLogState) GetHipKxq1() float64 {
	if x != nil {
		return x.HipKxq1
	}
	return 0
}

func (x *HyperLogLogState) GetHipEst() float64 {
	if x != nil {
		return x.HipEst
	}
	return 0
}

var File_hll_hll_proto protoreflect.FileDescriptor

const file_hll_hll_proto_rawDesc = "" +
	"\n" +
	"\rhll/hll.proto\x12\fsketchlib.v1\"\xd7\x01\n" +
	"\x10HyperLogLogState\x122\n" +
	"\avariant\x18\x01 \x01(\x0e2\x18.sketchlib.v1.HLLVariantR\avariant\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\rR\tprecision\x12\x1c\n" +
	"\tregisters\x18\x03 \x01(\fR\tregisters\x12\x19\n" +
	"\bhip_kxq0\x18\x04 \x01(\x01R\ahipKxq0\x12\x19\n" +
	"\bhip_kxq1\x18\x05 \x01(\x01R\ahipKxq1\x12\x17\n" +
	"\ahip_est\x18\x06 \x01(\x01R\x06hipEstJ\x04\b\a\x10\x10*s\n" +
	"\n" +
	"HLLVariant\x12\x1b\n" +
	"\x17HLL_VARIANT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HLL_VARIANT_REGULAR\x10\x01\x12\x1a\n" +
	"\x16HLL_VARIANT_DATAFUSION\x10\x02\x12\x13\n" +
	"\x0fHLL_VARIANT_HIP\x10\x03B5Z3github.com/ProjectASAP/sketchlib-go/proto/hll;hllpbb\x06proto3"

var (
	file_hll_hll_proto_rawDescOnce sync.Once
	file_hll_hll_proto_rawDescData []byte
)

func file_hll_hll_proto_rawDescGZIP() []byte {
	file_hll_hll_proto_rawDescOnce.Do(func() {
		file_hll_hll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hll_hll_proto_rawDesc), len(file_hll_hll_proto_rawDesc)))
	})
	return file_hll_hll_proto_rawDescData
}

var file_hll_hll_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hll_hll_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hll_hll_proto_goTypes = []any{
	(HLLVariant)(0),          // 0: sketchlib.v1.HLLVariant
	(*HyperLogLogState)(nil), // 1: sketchlib.v1.HyperLogLogState
}
var file_hll_hll_proto_depIdxs = []int32{
	0, // 0: sketchlib.v1.HyperLogLogState.variant:type_name -> sketchlib.v1.HLLVariant
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hll_hll_proto_init() }
func file_hll_hll_proto_init() {
	if File_hll_hll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hll_hll_proto_rawDesc), len(file_hll_hll_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hll_hll_proto_goTypes,
		DependencyIndexes: file_hll_hll_proto_depIdxs,
		EnumInfos:         file_hll_hll_proto_enumTypes,
		MessageInfos:      file_hll_hll_proto_msgTypes,
	}.Build()
	File_hll_hll_proto = out.File
	file_hll_hll_proto_goTypes = nil
	file_hll_hll_proto_depIdxs = nil
}
