// countminsketch.proto — Portable wire format for Count-Min Sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: countminsketch/countminsketch.proto

package countminsketchpb

import (
	common "github.com/ProjectASAP/sketchlib-go/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CountMinState is the portable state of a Count-Min Sketch.
//
// The counter matrix is stored flat in row-major order:
//
//	element [r][c] is at index r * cols + c.
//
// The Go implementation tracks auxiliary sum/L1/L2 arrays that the Rust
// implementation does not produce. These fields are optional; consumers
// that need them must recompute from raw insertions if absent.
type CountMinState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matrix dimensions. Both must be > 0.
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Indicates which counts_* field below is populated.
	CounterType common.CounterType `protobuf:"varint,3,opt,name=counter_type,json=counterType,proto3,enum=sketchlib.v1.CounterType" json:"counter_type,omitempty"`
	// Integer counters in row-major order, length = rows * cols.
	// Populated when counter_type ∈ {INT32, INT64}.
	// Use sint64 for efficient varint encoding of near-zero values.
	// For INT128 counters, values are interleaved as (hi_i, lo_i) pairs,
	// making the effective length 2 * rows * cols.
	CountsInt []int64 `protobuf:"zigzag64,4,rep,packed,name=counts_int,json=countsInt,proto3" json:"counts_int,omitempty"`
	// Floating-point counters in row-major order, length = rows * cols.
	// Populated when counter_type = FLOAT64 (Go producer).
	CountsFloat []float64 `protobuf:"fixed64,5,rep,packed,name=counts_float,json=countsFloat,proto3" json:"counts_float,omitempty"`
	// Sum-weighted counter matrix (same layout as counts_*), length = rows * cols.
	SumCounts []float64 `protobuf:"fixed64,6,rep,packed,name=sum_counts,json=sumCounts,proto3" json:"sum_counts,omitempty"`
	// Sum-of-squares counter matrix, length = rows * cols.
	Sum2Counts []float64 `protobuf:"fixed64,7,rep,packed,name=sum2_counts,json=sum2Counts,proto3" json:"sum2_counts,omitempty"`
	// Per-row L1 norms, length = rows.
	L1 []float64 `protobuf:"fixed64,8,rep,packed,name=l1,proto3" json:"l1,omitempty"`
	// Per-row L2 norms, length = rows. Recompute if absent.
	L2            []float64 `protobuf:"fixed64,9,rep,packed,name=l2,proto3" json:"l2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountMinState) Reset() {
	*x = CountMinState{}
	mi := &file_countminsketch_countminsketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountMinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountMinState) ProtoMessage() {}

func (x *CountMinState) ProtoReflect() protoreflect.Message {
	mi := &file_countminsketch_countminsketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountMinState.ProtoReflect.Descriptor instead.
func (*CountMinState) Descriptor() ([]byte, []int) {
	return file_countminsketch_countminsketch_proto_rawDescGZIP(), []int{0}
}

func (x *CountMinState) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CountMinState) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CountMinState) GetCounterType() common.CounterType {
	if x != nil {
		return x.CounterType
	}
	return common.CounterType(0)
}

func (x *CountMinState) GetCountsInt() []int64 {
	if x != nil {
		return x.CountsInt
	}
	return nil
}

func (x *CountMinState) GetCountsFloat() []float64 {
	if x != nil {
		return x.CountsFloat
	}
	return nil
}

func (x *CountMinState) GetSumCounts() []float64 {
	if x != nil {
		return x.SumCounts
	}
	return nil
}

func (x *CountMinState) GetSum2Counts() []float64 {
	if x != nil {
		return x.Sum2Counts
	}
	return nil
}

func (x *CountMinState) GetL1() []float64 {
	if x != nil {
		return x.L1
	}
	return nil
}

func (x *CountMinState) GetL2() []float64 {
	if x != nil {
		return x.L2
	}
	return nil
}

var File_countminsketch_countminsketch_proto protoreflect.FileDescriptor

const file_countminsketch_countminsketch_proto_rawDesc = "" +
	"\n" +
	"#countminsketch/countminsketch.proto\x12\fsketchlib.v1\x1a\x13common/common.proto\"\xb5\x02\n" +
	"\rCountMinState\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12<\n" +
	"\fcounter_type\x18\x03 \x01(\x0e2\x19.sketchlib.v1.CounterTypeR\vcounterType\x12!\n" +
	"\n" +
	"counts_int\x18\x04 \x03(\x12B\x02\x10\x01R\tcountsInt\x12%\n" +
	"\fcounts_float\x18\x05 \x03(\x01B\x02\x10\x01R\vcountsFloat\x12!\n" +
	"\n" +
	"sum_counts\x18\x06 \x03(\x01B\x02\x10\x01R\tsumCounts\x12#\n" +
	"\vsum2_counts\x18\a \x03(\x01B\x02\x10\x01R\n" +
	"sum2Counts\x12\x12\n" +
	"\x02l1\x18\b \x03(\x01B\x02\x10\x01R\x02l1\x12\x12\n" +
	"\x02l2\x18\t \x03(\x01B\x02\x10\x01R\x02l2J\x04\b\n" +
	"\x10\x10BKZIgithub.com/ProjectASAP/sketchlib-go/proto/countminsketch;countminsketchpbb\x06proto3"

var (
	file_countminsketch_countminsketch_proto_rawDescOnce sync.Once
	file_countminsketch_countminsketch_proto_rawDescData []byte
)

func file_countminsketch_countminsketch_proto_rawDescGZIP() []byte {
	file_countminsketch_countminsketch_proto_rawDescOnce.Do(func() {
		file_countminsketch_countminsketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_countminsketch_countminsketch_proto_rawDesc), len(file_countminsketch_countminsketch_proto_rawDesc)))
	})
	return file_countminsketch_countminsketch_proto_rawDescData
}

var file_countminsketch_countminsketch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_countminsketch_countminsketch_proto_goTypes = []any{
	(*CountMinState)(nil),   // 0: sketchlib.v1.CountMinState
	(common.CounterType)(0), // 1: sketchlib.v1.CounterType
}
var file_countminsketch_countminsketch_proto_depIdxs = []int32{
	1, // 0: sketchlib.v1.CountMinState.counter_type:type_name -> sketchlib.v1.CounterType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_countminsketch_countminsketch_proto_init() }
func file_countminsketch_countminsketch_proto_init() {
	if File_countminsketch_countminsketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_countminsketch_countminsketch_proto_rawDesc), len(file_countminsketch_countminsketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_countminsketch_countminsketch_proto_goTypes,
		DependencyIndexes: file_countminsketch_countminsketch_proto_depIdxs,
		MessageInfos:      file_countminsketch_countminsketch_proto_msgTypes,
	}.Build()
	File_countminsketch_countminsketch_proto = out.File
	file_countminsketch_countminsketch_proto_goTypes = nil
	file_countminsketch_countminsketch_proto_depIdxs = nil
}
