// ddsketch.proto — Portable wire format for DDSketch quantile sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ddsketch/ddsketch.proto

package ddsketchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DDSketchState is the portable state of a DDSketch quantile sketch.
//
// Only alpha is required to reconstruct the index mapping. Consumers must
// recompute all derived mapping values on load:
//
//	gamma        = (1.0 + alpha) / (1.0 - alpha)
//	log_gamma    = ln(gamma)
//	inv_log_gamma = 1.0 / log_gamma
//
// Bucket indices: a value v maps to bucket floor(ln(v) * inv_log_gamma).
// Stored bucket absolute_index = array_index + store_offset.
type DDSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative accuracy guarantee. Required. Must satisfy 0 < alpha < 1.
	Alpha float64 `protobuf:"fixed64,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	// Bucket count array in index order (ascending absolute bucket index).
	// Absolute index of store_counts[i] is i + store_offset.
	StoreCounts []uint64 `protobuf:"varint,2,rep,packed,name=store_counts,json=storeCounts,proto3" json:"store_counts,omitempty"`
	// Absolute bucket index corresponding to store_counts[0].
	// May be negative (values < 1.0 map to negative bucket indices).
	StoreOffset int32 `protobuf:"zigzag32,3,opt,name=store_offset,json=storeOffset,proto3" json:"store_offset,omitempty"`
	// Total number of values added.
	Count uint64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Sum of all values added (for mean computation).
	Sum float64 `protobuf:"fixed64,5,opt,name=sum,proto3" json:"sum,omitempty"`
	// Minimum value observed. +Inf when the sketch is empty.
	Min float64 `protobuf:"fixed64,6,opt,name=min,proto3" json:"min,omitempty"`
	// Maximum value observed. -Inf when the sketch is empty.
	Max           float64 `protobuf:"fixed64,7,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchState) Reset() {
	*x = DDSketchState{}
	mi := &file_ddsketch_ddsketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchState) ProtoMessage() {}

func (x *DDSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_ddsketch_ddsketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchState.ProtoReflect.Descriptor instead.
func (*DDSketchState) Descriptor() ([]byte, []int) {
	return file_ddsketch_ddsketch_proto_rawDescGZIP(), []int{0}
}

func (x *DDSketchState) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *DDSketchState) GetStoreCounts() []uint64 {
	if x != nil {
		return x.StoreCounts
	}
	return nil
}

func (x *DDSketchState) GetStoreOffset() int32 {
	if x != nil {
		return x.StoreOffset
	}
	return 0
}

func (x *DDSketchState) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DDSketchState) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *DDSketchState) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DDSketchState) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// DDSketchDelta carries only the buckets that changed above threshold T.
// count/sum are additive deltas. min/max are lossless scalars transmitted
// only when they changed (min can only decrease, max can only increase).
type DDSketchDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*DDSketchBucketDelta `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	DCount        int64                  `protobuf:"varint,2,opt,name=d_count,json=dCount,proto3" json:"d_count,omitempty"`
	DSum          float64                `protobuf:"fixed64,3,opt,name=d_sum,json=dSum,proto3" json:"d_sum,omitempty"`
	NewMin        float64                `protobuf:"fixed64,4,opt,name=new_min,json=newMin,proto3" json:"new_min,omitempty"`
	NewMax        float64                `protobuf:"fixed64,5,opt,name=new_max,json=newMax,proto3" json:"new_max,omitempty"`
	MinChanged    bool                   `protobuf:"varint,6,opt,name=min_changed,json=minChanged,proto3" json:"min_changed,omitempty"`
	MaxChanged    bool                   `protobuf:"varint,7,opt,name=max_changed,json=maxChanged,proto3" json:"max_changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchDelta) Reset() {
	*x = DDSketchDelta{}
	mi := &file_ddsketch_ddsketch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchDelta) ProtoMessage() {}

func (x *DDSketchDelta) ProtoReflect() protoreflect.Message {
	mi := &file_ddsketch_ddsketch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchDelta.ProtoReflect.Descriptor instead.
func (*DDSketchDelta) Descriptor() ([]byte, []int) {
	return file_ddsketch_ddsketch_proto_rawDescGZIP(), []int{1}
}

func (x *DDSketchDelta) GetBuckets() []*DDSketchBucketDelta {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *DDSketchDelta) GetDCount() int64 {
	if x != nil {
		return x.DCount
	}
	return 0
}

func (x *DDSketchDelta) GetDSum() float64 {
	if x != nil {
		return x.DSum
	}
	return 0
}

func (x *DDSketchDelta) GetNewMin() float64 {
	if x != nil {
		return x.NewMin
	}
	return 0
}

func (x *DDSketchDelta) GetNewMax() float64 {
	if x != nil {
		return x.NewMax
	}
	return 0
}

func (x *DDSketchDelta) GetMinChanged() bool {
	if x != nil {
		return x.MinChanged
	}
	return false
}

func (x *DDSketchDelta) GetMaxChanged() bool {
	if x != nil {
		return x.MaxChanged
	}
	return false
}

// DDSketchBucketDelta is the delta for one log-scale bucket.
type DDSketchBucketDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"zigzag32,1,opt,name=index,proto3" json:"index,omitempty"`               // signed bucket index (negative for values < 1)
	DCount        uint64                 `protobuf:"varint,2,opt,name=d_count,json=dCount,proto3" json:"d_count,omitempty"` // Δcount ≥ threshold T
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchBucketDelta) Reset() {
	*x = DDSketchBucketDelta{}
	mi := &file_ddsketch_ddsketch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchBucketDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchBucketDelta) ProtoMessage() {}

func (x *DDSketchBucketDelta) ProtoReflect() protoreflect.Message {
	mi := &file_ddsketch_ddsketch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchBucketDelta.ProtoReflect.Descriptor instead.
func (*DDSketchBucketDelta) Descriptor() ([]byte, []int) {
	return file_ddsketch_ddsketch_proto_rawDescGZIP(), []int{2}
}

func (x *DDSketchBucketDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DDSketchBucketDelta) GetDCount() uint64 {
	if x != nil {
		return x.DCount
	}
	return 0
}

var File_ddsketch_ddsketch_proto protoreflect.FileDescriptor

const file_ddsketch_ddsketch_proto_rawDesc = "" +
	"\n" +
	"\x17ddsketch/ddsketch.proto\x12\fsketchlib.v1\"\xc1\x01\n" +
	"\rDDSketchState\x12\x14\n" +
	"\x05alpha\x18\x01 \x01(\x01R\x05alpha\x12%\n" +
	"\fstore_counts\x18\x02 \x03(\x04B\x02\x10\x01R\vstoreCounts\x12!\n" +
	"\fstore_offset\x18\x03 \x01(\x11R\vstoreOffset\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\x12\x10\n" +
	"\x03sum\x18\x05 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03min\x18\x06 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\a \x01(\x01R\x03maxJ\x04\b\b\x10\x10\"\xee\x01\n" +
	"\rDDSketchDelta\x12;\n" +
	"\abuckets\x18\x01 \x03(\v2!.sketchlib.v1.DDSketchBucketDeltaR\abuckets\x12\x17\n" +
	"\ad_count\x18\x02 \x01(\x03R\x06dCount\x12\x13\n" +
	"\x05d_sum\x18\x03 \x01(\x01R\x04dSum\x12\x17\n" +
	"\anew_min\x18\x04 \x01(\x01R\x06newMin\x12\x17\n" +
	"\anew_max\x18\x05 \x01(\x01R\x06newMax\x12\x1f\n" +
	"\vmin_changed\x18\x06 \x01(\bR\n" +
	"minChanged\x12\x1f\n" +
	"\vmax_changed\x18\a \x01(\bR\n" +
	"maxChanged\"D\n" +
	"\x13DDSketchBucketDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x11R\x05index\x12\x17\n" +
	"\ad_count\x18\x02 \x01(\x04R\x06dCountB?Z=github.com/ProjectASAP/sketchlib-go/proto/ddsketch;ddsketchpbb\x06proto3"

var (
	file_ddsketch_ddsketch_proto_rawDescOnce sync.Once
	file_ddsketch_ddsketch_proto_rawDescData []byte
)

func file_ddsketch_ddsketch_proto_rawDescGZIP() []byte {
	file_ddsketch_ddsketch_proto_rawDescOnce.Do(func() {
		file_ddsketch_ddsketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ddsketch_ddsketch_proto_rawDesc), len(file_ddsketch_ddsketch_proto_rawDesc)))
	})
	return file_ddsketch_ddsketch_proto_rawDescData
}

var file_ddsketch_ddsketch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ddsketch_ddsketch_proto_goTypes = []any{
	(*DDSketchState)(nil),       // 0: sketchlib.v1.DDSketchState
	(*DDSketchDelta)(nil),       // 1: sketchlib.v1.DDSketchDelta
	(*DDSketchBucketDelta)(nil), // 2: sketchlib.v1.DDSketchBucketDelta
}
var file_ddsketch_ddsketch_proto_depIdxs = []int32{
	2, // 0: sketchlib.v1.DDSketchDelta.buckets:type_name -> sketchlib.v1.DDSketchBucketDelta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ddsketch_ddsketch_proto_init() }
func file_ddsketch_ddsketch_proto_init() {
	if File_ddsketch_ddsketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ddsketch_ddsketch_proto_rawDesc), len(file_ddsketch_ddsketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddsketch_ddsketch_proto_goTypes,
		DependencyIndexes: file_ddsketch_ddsketch_proto_depIdxs,
		MessageInfos:      file_ddsketch_ddsketch_proto_msgTypes,
	}.Build()
	File_ddsketch_ddsketch_proto = out.File
	file_ddsketch_ddsketch_proto_goTypes = nil
	file_ddsketch_ddsketch_proto_depIdxs = nil
}
