// ddsketch.proto — Portable wire format for DDSketch quantile sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ddsketch/ddsketch.proto

package ddsketchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DDSketchState is the portable state of a DDSketch quantile sketch.
//
// Only alpha is required to reconstruct the index mapping. Consumers must
// recompute all derived mapping values on load:
//
//	gamma        = (1.0 + alpha) / (1.0 - alpha)
//	log_gamma    = ln(gamma)
//	inv_log_gamma = 1.0 / log_gamma
//
// Bucket indices: a value v maps to bucket floor(ln(v) * inv_log_gamma).
// Stored bucket absolute_index = array_index + store_offset.
//
// DataPoint-level metric scalars (count/sum/min/max) are intentionally NOT
// carried on the wire: count is recoverable by summing store_counts, and
// min/max/quantiles are derived from the bucket distribution within the
// relative-accuracy guarantee. sum is not recoverable and is not transmitted.
type DDSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative accuracy guarantee. Required. Must satisfy 0 < alpha < 1.
	Alpha float64 `protobuf:"fixed64,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	// Bucket count array in index order (ascending absolute bucket index).
	// Absolute index of store_counts[i] is i + store_offset.
	StoreCounts []uint64 `protobuf:"varint,2,rep,packed,name=store_counts,json=storeCounts,proto3" json:"store_counts,omitempty"`
	// Absolute bucket index corresponding to store_counts[0].
	// May be negative (values < 1.0 map to negative bucket indices).
	StoreOffset   int32 `protobuf:"zigzag32,3,opt,name=store_offset,json=storeOffset,proto3" json:"store_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchState) Reset() {
	*x = DDSketchState{}
	mi := &file_ddsketch_ddsketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchState) ProtoMessage() {}

func (x *DDSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_ddsketch_ddsketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchState.ProtoReflect.Descriptor instead.
func (*DDSketchState) Descriptor() ([]byte, []int) {
	return file_ddsketch_ddsketch_proto_rawDescGZIP(), []int{0}
}

func (x *DDSketchState) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *DDSketchState) GetStoreCounts() []uint64 {
	if x != nil {
		return x.StoreCounts
	}
	return nil
}

func (x *DDSketchState) GetStoreOffset() int32 {
	if x != nil {
		return x.StoreOffset
	}
	return 0
}

// DDSketchDelta carries only the buckets that changed above threshold T.
//
// DataPoint-level metric scalars (d_count/d_sum/new_min/new_max/min_changed/
// max_changed) are intentionally NOT carried on the wire: the count delta is
// recoverable by summing bucket deltas, and min/max/quantiles are derived from
// the bucket distribution within the relative-accuracy guarantee.
type DDSketchDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*DDSketchBucketDelta `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchDelta) Reset() {
	*x = DDSketchDelta{}
	mi := &file_ddsketch_ddsketch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchDelta) ProtoMessage() {}

func (x *DDSketchDelta) ProtoReflect() protoreflect.Message {
	mi := &file_ddsketch_ddsketch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchDelta.ProtoReflect.Descriptor instead.
func (*DDSketchDelta) Descriptor() ([]byte, []int) {
	return file_ddsketch_ddsketch_proto_rawDescGZIP(), []int{1}
}

func (x *DDSketchDelta) GetBuckets() []*DDSketchBucketDelta {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// DDSketchBucketDelta is the delta for one log-scale bucket.
type DDSketchBucketDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"zigzag32,1,opt,name=index,proto3" json:"index,omitempty"`               // signed bucket index (negative for values < 1)
	DCount        uint64                 `protobuf:"varint,2,opt,name=d_count,json=dCount,proto3" json:"d_count,omitempty"` // Δcount ≥ threshold T
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDSketchBucketDelta) Reset() {
	*x = DDSketchBucketDelta{}
	mi := &file_ddsketch_ddsketch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDSketchBucketDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDSketchBucketDelta) ProtoMessage() {}

func (x *DDSketchBucketDelta) ProtoReflect() protoreflect.Message {
	mi := &file_ddsketch_ddsketch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDSketchBucketDelta.ProtoReflect.Descriptor instead.
func (*DDSketchBucketDelta) Descriptor() ([]byte, []int) {
	return file_ddsketch_ddsketch_proto_rawDescGZIP(), []int{2}
}

func (x *DDSketchBucketDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DDSketchBucketDelta) GetDCount() uint64 {
	if x != nil {
		return x.DCount
	}
	return 0
}

var File_ddsketch_ddsketch_proto protoreflect.FileDescriptor

const file_ddsketch_ddsketch_proto_rawDesc = "" +
	"\n" +
	"\x17ddsketch/ddsketch.proto\x12\fsketchlib.v1\"\x8d\x01\n" +
	"\rDDSketchState\x12\x14\n" +
	"\x05alpha\x18\x01 \x01(\x01R\x05alpha\x12%\n" +
	"\fstore_counts\x18\x02 \x03(\x04B\x02\x10\x01R\vstoreCounts\x12!\n" +
	"\fstore_offset\x18\x03 \x01(\x11R\vstoreOffsetJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\x10\"p\n" +
	"\rDDSketchDelta\x12;\n" +
	"\abuckets\x18\x01 \x03(\v2!.sketchlib.v1.DDSketchBucketDeltaR\abucketsJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\b\"D\n" +
	"\x13DDSketchBucketDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x11R\x05index\x12\x17\n" +
	"\ad_count\x18\x02 \x01(\x04R\x06dCountB?Z=github.com/ProjectASAP/sketchlib-go/proto/ddsketch;ddsketchpbb\x06proto3"

var (
	file_ddsketch_ddsketch_proto_rawDescOnce sync.Once
	file_ddsketch_ddsketch_proto_rawDescData []byte
)

func file_ddsketch_ddsketch_proto_rawDescGZIP() []byte {
	file_ddsketch_ddsketch_proto_rawDescOnce.Do(func() {
		file_ddsketch_ddsketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ddsketch_ddsketch_proto_rawDesc), len(file_ddsketch_ddsketch_proto_rawDesc)))
	})
	return file_ddsketch_ddsketch_proto_rawDescData
}

var file_ddsketch_ddsketch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ddsketch_ddsketch_proto_goTypes = []any{
	(*DDSketchState)(nil),       // 0: sketchlib.v1.DDSketchState
	(*DDSketchDelta)(nil),       // 1: sketchlib.v1.DDSketchDelta
	(*DDSketchBucketDelta)(nil), // 2: sketchlib.v1.DDSketchBucketDelta
}
var file_ddsketch_ddsketch_proto_depIdxs = []int32{
	2, // 0: sketchlib.v1.DDSketchDelta.buckets:type_name -> sketchlib.v1.DDSketchBucketDelta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ddsketch_ddsketch_proto_init() }
func file_ddsketch_ddsketch_proto_init() {
	if File_ddsketch_ddsketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ddsketch_ddsketch_proto_rawDesc), len(file_ddsketch_ddsketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddsketch_ddsketch_proto_goTypes,
		DependencyIndexes: file_ddsketch_ddsketch_proto_depIdxs,
		MessageInfos:      file_ddsketch_ddsketch_proto_msgTypes,
	}.Build()
	File_ddsketch_ddsketch_proto = out.File
	file_ddsketch_ddsketch_proto_goTypes = nil
	file_ddsketch_ddsketch_proto_depIdxs = nil
}
