// univmon.proto — Portable wire format for Universal Monitoring (UnivMon) sketch state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: univmon/univmon.proto

package univmonpb

import (
	countsketch "github.com/ProjectASAP/sketchlib-go/proto/countsketch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UnivMonState is the portable state of a Universal Monitoring (UnivMon) sketch.
//
// UnivMon is a hierarchy of L Count Sketches paired with L heavy-hitter heaps.
// An item's hash trailing-zero count determines which layers receive it, giving
// each layer a geometrically decreasing sample of the stream.
//
// All layers share the same sketch dimensions and heap capacity.
type UnivMonState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of layers L in the hierarchy (inclusive of all levels).
	LayerSize uint32 `protobuf:"varint,1,opt,name=layer_size,json=layerSize,proto3" json:"layer_size,omitempty"`
	// Count Sketch dimensions shared by all layers.
	SketchRows uint32 `protobuf:"varint,2,opt,name=sketch_rows,json=sketchRows,proto3" json:"sketch_rows,omitempty"`
	SketchCols uint32 `protobuf:"varint,3,opt,name=sketch_cols,json=sketchCols,proto3" json:"sketch_cols,omitempty"`
	// Heavy-hitter heap capacity shared by all layers.
	HeapSize uint32 `protobuf:"varint,4,opt,name=heap_size,json=heapSize,proto3" json:"heap_size,omitempty"`
	// Total items inserted across all layers (the "bucket size" counter).
	BucketSize uint64 `protobuf:"varint,5,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	// Per-layer state, in order from layer 0 (finest) to layer_size-1 (coarsest).
	// Length must equal layer_size.
	Layers        []*UnivMonLayer `protobuf:"bytes,6,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnivMonState) Reset() {
	*x = UnivMonState{}
	mi := &file_univmon_univmon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnivMonState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnivMonState) ProtoMessage() {}

func (x *UnivMonState) ProtoReflect() protoreflect.Message {
	mi := &file_univmon_univmon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnivMonState.ProtoReflect.Descriptor instead.
func (*UnivMonState) Descriptor() ([]byte, []int) {
	return file_univmon_univmon_proto_rawDescGZIP(), []int{0}
}

func (x *UnivMonState) GetLayerSize() uint32 {
	if x != nil {
		return x.LayerSize
	}
	return 0
}

func (x *UnivMonState) GetSketchRows() uint32 {
	if x != nil {
		return x.SketchRows
	}
	return 0
}

func (x *UnivMonState) GetSketchCols() uint32 {
	if x != nil {
		return x.SketchCols
	}
	return 0
}

func (x *UnivMonState) GetHeapSize() uint32 {
	if x != nil {
		return x.HeapSize
	}
	return 0
}

func (x *UnivMonState) GetBucketSize() uint64 {
	if x != nil {
		return x.BucketSize
	}
	return 0
}

func (x *UnivMonState) GetLayers() []*UnivMonLayer {
	if x != nil {
		return x.Layers
	}
	return nil
}

// UnivMonLayer is the joint state of one UnivMon layer.
type UnivMonLayer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Count Sketch accumulating items at this layer.
	Sketch *countsketch.CountSketchState `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	// The heavy-hitter heap for this layer.
	Heap          *countsketch.TopKState `protobuf:"bytes,2,opt,name=heap,proto3" json:"heap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnivMonLayer) Reset() {
	*x = UnivMonLayer{}
	mi := &file_univmon_univmon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnivMonLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnivMonLayer) ProtoMessage() {}

func (x *UnivMonLayer) ProtoReflect() protoreflect.Message {
	mi := &file_univmon_univmon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnivMonLayer.ProtoReflect.Descriptor instead.
func (*UnivMonLayer) Descriptor() ([]byte, []int) {
	return file_univmon_univmon_proto_rawDescGZIP(), []int{1}
}

func (x *UnivMonLayer) GetSketch() *countsketch.CountSketchState {
	if x != nil {
		return x.Sketch
	}
	return nil
}

func (x *UnivMonLayer) GetHeap() *countsketch.TopKState {
	if x != nil {
		return x.Heap
	}
	return nil
}

var File_univmon_univmon_proto protoreflect.FileDescriptor

const file_univmon_univmon_proto_rawDesc = "" +
	"\n" +
	"\x15univmon/univmon.proto\x12\fsketchlib.v1\x1a\x1dcountsketch/countsketch.proto\"\xe7\x01\n" +
	"\fUnivMonState\x12\x1d\n" +
	"\n" +
	"layer_size\x18\x01 \x01(\rR\tlayerSize\x12\x1f\n" +
	"\vsketch_rows\x18\x02 \x01(\rR\n" +
	"sketchRows\x12\x1f\n" +
	"\vsketch_cols\x18\x03 \x01(\rR\n" +
	"sketchCols\x12\x1b\n" +
	"\theap_size\x18\x04 \x01(\rR\bheapSize\x12\x1f\n" +
	"\vbucket_size\x18\x05 \x01(\x04R\n" +
	"bucketSize\x122\n" +
	"\x06layers\x18\x06 \x03(\v2\x1a.sketchlib.v1.UnivMonLayerR\x06layersJ\x04\b\a\x10\x10\"s\n" +
	"\fUnivMonLayer\x126\n" +
	"\x06sketch\x18\x01 \x01(\v2\x1e.sketchlib.v1.CountSketchStateR\x06sketch\x12+\n" +
	"\x04heap\x18\x02 \x01(\v2\x17.sketchlib.v1.TopKStateR\x04heapB=Z;github.com/ProjectASAP/sketchlib-go/proto/univmon;univmonpbb\x06proto3"

var (
	file_univmon_univmon_proto_rawDescOnce sync.Once
	file_univmon_univmon_proto_rawDescData []byte
)

func file_univmon_univmon_proto_rawDescGZIP() []byte {
	file_univmon_univmon_proto_rawDescOnce.Do(func() {
		file_univmon_univmon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_univmon_univmon_proto_rawDesc), len(file_univmon_univmon_proto_rawDesc)))
	})
	return file_univmon_univmon_proto_rawDescData
}

var file_univmon_univmon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_univmon_univmon_proto_goTypes = []any{
	(*UnivMonState)(nil),                 // 0: sketchlib.v1.UnivMonState
	(*UnivMonLayer)(nil),                 // 1: sketchlib.v1.UnivMonLayer
	(*countsketch.CountSketchState)(nil), // 2: sketchlib.v1.CountSketchState
	(*countsketch.TopKState)(nil),        // 3: sketchlib.v1.TopKState
}
var file_univmon_univmon_proto_depIdxs = []int32{
	1, // 0: sketchlib.v1.UnivMonState.layers:type_name -> sketchlib.v1.UnivMonLayer
	2, // 1: sketchlib.v1.UnivMonLayer.sketch:type_name -> sketchlib.v1.CountSketchState
	3, // 2: sketchlib.v1.UnivMonLayer.heap:type_name -> sketchlib.v1.TopKState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_univmon_univmon_proto_init() }
func file_univmon_univmon_proto_init() {
	if File_univmon_univmon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_univmon_univmon_proto_rawDesc), len(file_univmon_univmon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_univmon_univmon_proto_goTypes,
		DependencyIndexes: file_univmon_univmon_proto_depIdxs,
		MessageInfos:      file_univmon_univmon_proto_msgTypes,
	}.Build()
	File_univmon_univmon_proto = out.File
	file_univmon_univmon_proto_goTypes = nil
	file_univmon_univmon_proto_depIdxs = nil
}
