// hydra.proto — Portable wire format for Hydra multi-sketch framework state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hydra/hydra.proto

package hydrapb

import (
	countminsketch "github.com/ProjectASAP/sketchlib-go/proto/countminsketch"
	countsketch "github.com/ProjectASAP/sketchlib-go/proto/countsketch"
	hll "github.com/ProjectASAP/sketchlib-go/proto/hll"
	kll "github.com/ProjectASAP/sketchlib-go/proto/kll"
	univmon "github.com/ProjectASAP/sketchlib-go/proto/univmon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HydraCounterType identifies the sketch algorithm used inside Hydra cells.
type HydraCounterType int32

const (
	HydraCounterType_HYDRA_COUNTER_TYPE_UNSPECIFIED  HydraCounterType = 0
	HydraCounterType_HYDRA_COUNTER_TYPE_COUNT_MIN    HydraCounterType = 1
	HydraCounterType_HYDRA_COUNTER_TYPE_COUNT_SKETCH HydraCounterType = 2
	HydraCounterType_HYDRA_COUNTER_TYPE_HLL          HydraCounterType = 3
	HydraCounterType_HYDRA_COUNTER_TYPE_KLL          HydraCounterType = 4
	HydraCounterType_HYDRA_COUNTER_TYPE_UNIVMON      HydraCounterType = 5
)

// Enum value maps for HydraCounterType.
var (
	HydraCounterType_name = map[int32]string{
		0: "HYDRA_COUNTER_TYPE_UNSPECIFIED",
		1: "HYDRA_COUNTER_TYPE_COUNT_MIN",
		2: "HYDRA_COUNTER_TYPE_COUNT_SKETCH",
		3: "HYDRA_COUNTER_TYPE_HLL",
		4: "HYDRA_COUNTER_TYPE_KLL",
		5: "HYDRA_COUNTER_TYPE_UNIVMON",
	}
	HydraCounterType_value = map[string]int32{
		"HYDRA_COUNTER_TYPE_UNSPECIFIED":  0,
		"HYDRA_COUNTER_TYPE_COUNT_MIN":    1,
		"HYDRA_COUNTER_TYPE_COUNT_SKETCH": 2,
		"HYDRA_COUNTER_TYPE_HLL":          3,
		"HYDRA_COUNTER_TYPE_KLL":          4,
		"HYDRA_COUNTER_TYPE_UNIVMON":      5,
	}
)

func (x HydraCounterType) Enum() *HydraCounterType {
	p := new(HydraCounterType)
	*p = x
	return p
}

func (x HydraCounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HydraCounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_hydra_hydra_proto_enumTypes[0].Descriptor()
}

func (HydraCounterType) Type() protoreflect.EnumType {
	return &file_hydra_hydra_proto_enumTypes[0]
}

func (x HydraCounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HydraCounterType.Descriptor instead.
func (HydraCounterType) EnumDescriptor() ([]byte, []int) {
	return file_hydra_hydra_proto_rawDescGZIP(), []int{0}
}

// HydraState is the portable state of a Hydra multi-sketch framework.
//
// Hydra maintains a grid of row_num child sketches (cells), each of the
// same type (counter_type). Items are routed to a specific row cell using a
// position hash derived from the item's subkey. An optional global "big
// counter" sketch aggregates the full stream.
//
// Current implementations set col_num = 1 (one sketch per row). The field is
// included for schema completeness and future extensions.
type HydraState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of sketch rows (D / number of subpopulations).
	RowNum uint32 `protobuf:"varint,1,opt,name=row_num,json=rowNum,proto3" json:"row_num,omitempty"`
	// Number of sketch columns per row. Currently always 1.
	ColNum uint32 `protobuf:"varint,2,opt,name=col_num,json=colNum,proto3" json:"col_num,omitempty"`
	// The sketch type used for every cell.
	CounterType HydraCounterType `protobuf:"varint,3,opt,name=counter_type,json=counterType,proto3,enum=sketchlib.v1.HydraCounterType" json:"counter_type,omitempty"`
	// Serialized cells in row-major order, length = row_num * col_num.
	// Each cell's oneof field must match counter_type.
	Cells []*HydraCell `protobuf:"bytes,4,rep,name=cells,proto3" json:"cells,omitempty"`
	// Optional global sketch covering the entire stream.
	// Absent when global counter is disabled (enable_global_counter = false).
	BigCounter *HydraCell `protobuf:"bytes,5,opt,name=big_counter,json=bigCounter,proto3" json:"big_counter,omitempty"`
	// Seed index used for subpopulation routing (Go: seedHydra, Rust: HYDRA_SEED).
	// Both libraries default to 6.
	SeedIndex uint32 `protobuf:"varint,6,opt,name=seed_index,json=seedIndex,proto3" json:"seed_index,omitempty"`
	// True when per-cell TopK tracking is enabled.
	EnableTopk bool `protobuf:"varint,7,opt,name=enable_topk,json=enableTopk,proto3" json:"enable_topk,omitempty"`
	// True when fanout subkey expansion is active.
	FanoutSubkeys bool `protobuf:"varint,8,opt,name=fanout_subkeys,json=fanoutSubkeys,proto3" json:"fanout_subkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HydraState) Reset() {
	*x = HydraState{}
	mi := &file_hydra_hydra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HydraState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HydraState) ProtoMessage() {}

func (x *HydraState) ProtoReflect() protoreflect.Message {
	mi := &file_hydra_hydra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HydraState.ProtoReflect.Descriptor instead.
func (*HydraState) Descriptor() ([]byte, []int) {
	return file_hydra_hydra_proto_rawDescGZIP(), []int{0}
}

func (x *HydraState) GetRowNum() uint32 {
	if x != nil {
		return x.RowNum
	}
	return 0
}

func (x *HydraState) GetColNum() uint32 {
	if x != nil {
		return x.ColNum
	}
	return 0
}

func (x *HydraState) GetCounterType() HydraCounterType {
	if x != nil {
		return x.CounterType
	}
	return HydraCounterType_HYDRA_COUNTER_TYPE_UNSPECIFIED
}

func (x *HydraState) GetCells() []*HydraCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *HydraState) GetBigCounter() *HydraCell {
	if x != nil {
		return x.BigCounter
	}
	return nil
}

func (x *HydraState) GetSeedIndex() uint32 {
	if x != nil {
		return x.SeedIndex
	}
	return 0
}

func (x *HydraState) GetEnableTopk() bool {
	if x != nil {
		return x.EnableTopk
	}
	return false
}

func (x *HydraState) GetFanoutSubkeys() bool {
	if x != nil {
		return x.FanoutSubkeys
	}
	return false
}

// HydraCell holds the serialized state of one Hydra grid cell.
// Exactly one field in the oneof must be set, and it must match the parent
// HydraState.counter_type.
type HydraCell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sketch:
	//
	//	*HydraCell_CountMin
	//	*HydraCell_CountSketch
	//	*HydraCell_Hll
	//	*HydraCell_Kll
	//	*HydraCell_Univmon
	Sketch        isHydraCell_Sketch `protobuf_oneof:"sketch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HydraCell) Reset() {
	*x = HydraCell{}
	mi := &file_hydra_hydra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HydraCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HydraCell) ProtoMessage() {}

func (x *HydraCell) ProtoReflect() protoreflect.Message {
	mi := &file_hydra_hydra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HydraCell.ProtoReflect.Descriptor instead.
func (*HydraCell) Descriptor() ([]byte, []int) {
	return file_hydra_hydra_proto_rawDescGZIP(), []int{1}
}

func (x *HydraCell) GetSketch() isHydraCell_Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

func (x *HydraCell) GetCountMin() *countminsketch.CountMinState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_CountMin); ok {
			return x.CountMin
		}
	}
	return nil
}

func (x *HydraCell) GetCountSketch() *countsketch.CountSketchState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_CountSketch); ok {
			return x.CountSketch
		}
	}
	return nil
}

func (x *HydraCell) GetHll() *hll.HyperLogLogState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_Hll); ok {
			return x.Hll
		}
	}
	return nil
}

func (x *HydraCell) GetKll() *kll.KLLState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_Kll); ok {
			return x.Kll
		}
	}
	return nil
}

func (x *HydraCell) GetUnivmon() *univmon.UnivMonState {
	if x != nil {
		if x, ok := x.Sketch.(*HydraCell_Univmon); ok {
			return x.Univmon
		}
	}
	return nil
}

type isHydraCell_Sketch interface {
	isHydraCell_Sketch()
}

type HydraCell_CountMin struct {
	CountMin *countminsketch.CountMinState `protobuf:"bytes,1,opt,name=count_min,json=countMin,proto3,oneof"`
}

type HydraCell_CountSketch struct {
	CountSketch *countsketch.CountSketchState `protobuf:"bytes,2,opt,name=count_sketch,json=countSketch,proto3,oneof"`
}

type HydraCell_Hll struct {
	Hll *hll.HyperLogLogState `protobuf:"bytes,3,opt,name=hll,proto3,oneof"`
}

type HydraCell_Kll struct {
	Kll *kll.KLLState `protobuf:"bytes,4,opt,name=kll,proto3,oneof"`
}

type HydraCell_Univmon struct {
	Univmon *univmon.UnivMonState `protobuf:"bytes,5,opt,name=univmon,proto3,oneof"`
}

func (*HydraCell_CountMin) isHydraCell_Sketch() {}

func (*HydraCell_CountSketch) isHydraCell_Sketch() {}

func (*HydraCell_Hll) isHydraCell_Sketch() {}

func (*HydraCell_Kll) isHydraCell_Sketch() {}

func (*HydraCell_Univmon) isHydraCell_Sketch() {}

var File_hydra_hydra_proto protoreflect.FileDescriptor

const file_hydra_hydra_proto_rawDesc = "" +
	"\n" +
	"\x11hydra/hydra.proto\x12\fsketchlib.v1\x1a#countminsketch/countminsketch.proto\x1a\x1dcountsketch/countsketch.proto\x1a\rhll/hll.proto\x1a\rkll/kll.proto\x1a\x15univmon/univmon.proto\"\xd7\x02\n" +
	"\n" +
	"HydraState\x12\x17\n" +
	"\arow_num\x18\x01 \x01(\rR\x06rowNum\x12\x17\n" +
	"\acol_num\x18\x02 \x01(\rR\x06colNum\x12A\n" +
	"\fcounter_type\x18\x03 \x01(\x0e2\x1e.sketchlib.v1.HydraCounterTypeR\vcounterType\x12-\n" +
	"\x05cells\x18\x04 \x03(\v2\x17.sketchlib.v1.HydraCellR\x05cells\x128\n" +
	"\vbig_counter\x18\x05 \x01(\v2\x17.sketchlib.v1.HydraCellR\n" +
	"bigCounter\x12\x1d\n" +
	"\n" +
	"seed_index\x18\x06 \x01(\rR\tseedIndex\x12\x1f\n" +
	"\venable_topk\x18\a \x01(\bR\n" +
	"enableTopk\x12%\n" +
	"\x0efanout_subkeys\x18\b \x01(\bR\rfanoutSubkeysJ\x04\b\t\x10\x10\"\xae\x02\n" +
	"\tHydraCell\x12:\n" +
	"\tcount_min\x18\x01 \x01(\v2\x1b.sketchlib.v1.CountMinStateH\x00R\bcountMin\x12C\n" +
	"\fcount_sketch\x18\x02 \x01(\v2\x1e.sketchlib.v1.CountSketchStateH\x00R\vcountSketch\x122\n" +
	"\x03hll\x18\x03 \x01(\v2\x1e.sketchlib.v1.HyperLogLogStateH\x00R\x03hll\x12*\n" +
	"\x03kll\x18\x04 \x01(\v2\x16.sketchlib.v1.KLLStateH\x00R\x03kll\x126\n" +
	"\aunivmon\x18\x05 \x01(\v2\x1a.sketchlib.v1.UnivMonStateH\x00R\aunivmonB\b\n" +
	"\x06sketch*\xd5\x01\n" +
	"\x10HydraCounterType\x12\"\n" +
	"\x1eHYDRA_COUNTER_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cHYDRA_COUNTER_TYPE_COUNT_MIN\x10\x01\x12#\n" +
	"\x1fHYDRA_COUNTER_TYPE_COUNT_SKETCH\x10\x02\x12\x1a\n" +
	"\x16HYDRA_COUNTER_TYPE_HLL\x10\x03\x12\x1a\n" +
	"\x16HYDRA_COUNTER_TYPE_KLL\x10\x04\x12\x1e\n" +
	"\x1aHYDRA_COUNTER_TYPE_UNIVMON\x10\x05B9Z7github.com/ProjectASAP/sketchlib-go/proto/hydra;hydrapbb\x06proto3"

var (
	file_hydra_hydra_proto_rawDescOnce sync.Once
	file_hydra_hydra_proto_rawDescData []byte
)

func file_hydra_hydra_proto_rawDescGZIP() []byte {
	file_hydra_hydra_proto_rawDescOnce.Do(func() {
		file_hydra_hydra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hydra_hydra_proto_rawDesc), len(file_hydra_hydra_proto_rawDesc)))
	})
	return file_hydra_hydra_proto_rawDescData
}

var file_hydra_hydra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hydra_hydra_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hydra_hydra_proto_goTypes = []any{
	(HydraCounterType)(0),                // 0: sketchlib.v1.HydraCounterType
	(*HydraState)(nil),                   // 1: sketchlib.v1.HydraState
	(*HydraCell)(nil),                    // 2: sketchlib.v1.HydraCell
	(*countminsketch.CountMinState)(nil), // 3: sketchlib.v1.CountMinState
	(*countsketch.CountSketchState)(nil), // 4: sketchlib.v1.CountSketchState
	(*hll.HyperLogLogState)(nil),         // 5: sketchlib.v1.HyperLogLogState
	(*kll.KLLState)(nil),                 // 6: sketchlib.v1.KLLState
	(*univmon.UnivMonState)(nil),         // 7: sketchlib.v1.UnivMonState
}
var file_hydra_hydra_proto_depIdxs = []int32{
	0, // 0: sketchlib.v1.HydraState.counter_type:type_name -> sketchlib.v1.HydraCounterType
	2, // 1: sketchlib.v1.HydraState.cells:type_name -> sketchlib.v1.HydraCell
	2, // 2: sketchlib.v1.HydraState.big_counter:type_name -> sketchlib.v1.HydraCell
	3, // 3: sketchlib.v1.HydraCell.count_min:type_name -> sketchlib.v1.CountMinState
	4, // 4: sketchlib.v1.HydraCell.count_sketch:type_name -> sketchlib.v1.CountSketchState
	5, // 5: sketchlib.v1.HydraCell.hll:type_name -> sketchlib.v1.HyperLogLogState
	6, // 6: sketchlib.v1.HydraCell.kll:type_name -> sketchlib.v1.KLLState
	7, // 7: sketchlib.v1.HydraCell.univmon:type_name -> sketchlib.v1.UnivMonState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_hydra_hydra_proto_init() }
func file_hydra_hydra_proto_init() {
	if File_hydra_hydra_proto != nil {
		return
	}
	file_hydra_hydra_proto_msgTypes[1].OneofWrappers = []any{
		(*HydraCell_CountMin)(nil),
		(*HydraCell_CountSketch)(nil),
		(*HydraCell_Hll)(nil),
		(*HydraCell_Kll)(nil),
		(*HydraCell_Univmon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hydra_hydra_proto_rawDesc), len(file_hydra_hydra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hydra_hydra_proto_goTypes,
		DependencyIndexes: file_hydra_hydra_proto_depIdxs,
		EnumInfos:         file_hydra_hydra_proto_enumTypes,
		MessageInfos:      file_hydra_hydra_proto_msgTypes,
	}.Build()
	File_hydra_hydra_proto = out.File
	file_hydra_hydra_proto_goTypes = nil
	file_hydra_hydra_proto_depIdxs = nil
}
