// cocosketch.proto — Portable wire format for CocoSketch flow-size estimator state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cocosketch/cocosketch.proto

package cocosketchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CocoSketchState is the portable state of a CocoSketch flow-size estimator.
//
// The bucket table is stored flat in row-major order (d rows × width cols).
// Element [r][c] is at index r * width + c.
type CocoSketchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of hash rows.
	D uint32 `protobuf:"varint,1,opt,name=d,proto3" json:"d,omitempty"`
	// Number of buckets per row.
	Width uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// Full hash stored in each bucket, length = d * width.
	// Zero means the bucket is empty (has_keys[i] == false).
	Hashes []uint64 `protobuf:"varint,3,rep,packed,name=hashes,proto3" json:"hashes,omitempty"`
	// Cumulative count value per bucket, length = d * width.
	Vals []uint64 `protobuf:"varint,4,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	// Whether each bucket holds a valid key entry, length = d * width.
	HasKeys       []bool `protobuf:"varint,5,rep,packed,name=has_keys,json=hasKeys,proto3" json:"has_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CocoSketchState) Reset() {
	*x = CocoSketchState{}
	mi := &file_cocosketch_cocosketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CocoSketchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CocoSketchState) ProtoMessage() {}

func (x *CocoSketchState) ProtoReflect() protoreflect.Message {
	mi := &file_cocosketch_cocosketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CocoSketchState.ProtoReflect.Descriptor instead.
func (*CocoSketchState) Descriptor() ([]byte, []int) {
	return file_cocosketch_cocosketch_proto_rawDescGZIP(), []int{0}
}

func (x *CocoSketchState) GetD() uint32 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *CocoSketchState) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CocoSketchState) GetHashes() []uint64 {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *CocoSketchState) GetVals() []uint64 {
	if x != nil {
		return x.Vals
	}
	return nil
}

func (x *CocoSketchState) GetHasKeys() []bool {
	if x != nil {
		return x.HasKeys
	}
	return nil
}

var File_cocosketch_cocosketch_proto protoreflect.FileDescriptor

const file_cocosketch_cocosketch_proto_rawDesc = "" +
	"\n" +
	"\x1bcocosketch/cocosketch.proto\x12\fsketchlib.v1\"\x8e\x01\n" +
	"\x0fCocoSketchState\x12\f\n" +
	"\x01d\x18\x01 \x01(\rR\x01d\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x1a\n" +
	"\x06hashes\x18\x03 \x03(\x04B\x02\x10\x01R\x06hashes\x12\x16\n" +
	"\x04vals\x18\x04 \x03(\x04B\x02\x10\x01R\x04vals\x12\x1d\n" +
	"\bhas_keys\x18\x05 \x03(\bB\x02\x10\x01R\ahasKeysJ\x04\b\x06\x10\x10BCZAgithub.com/ProjectASAP/sketchlib-go/proto/cocosketch;cocosketchpbb\x06proto3"

var (
	file_cocosketch_cocosketch_proto_rawDescOnce sync.Once
	file_cocosketch_cocosketch_proto_rawDescData []byte
)

func file_cocosketch_cocosketch_proto_rawDescGZIP() []byte {
	file_cocosketch_cocosketch_proto_rawDescOnce.Do(func() {
		file_cocosketch_cocosketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cocosketch_cocosketch_proto_rawDesc), len(file_cocosketch_cocosketch_proto_rawDesc)))
	})
	return file_cocosketch_cocosketch_proto_rawDescData
}

var file_cocosketch_cocosketch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cocosketch_cocosketch_proto_goTypes = []any{
	(*CocoSketchState)(nil), // 0: sketchlib.v1.CocoSketchState
}
var file_cocosketch_cocosketch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cocosketch_cocosketch_proto_init() }
func file_cocosketch_cocosketch_proto_init() {
	if File_cocosketch_cocosketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cocosketch_cocosketch_proto_rawDesc), len(file_cocosketch_cocosketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cocosketch_cocosketch_proto_goTypes,
		DependencyIndexes: file_cocosketch_cocosketch_proto_depIdxs,
		MessageInfos:      file_cocosketch_cocosketch_proto_msgTypes,
	}.Build()
	File_cocosketch_cocosketch_proto = out.File
	file_cocosketch_cocosketch_proto_goTypes = nil
	file_cocosketch_cocosketch_proto_depIdxs = nil
}
